import 'dart:ui';

/// Parsed representation of `assets/theme/theme_config.json`.
///
/// All 45 Material Design 3 color roles are supported as optional overrides.
/// Any role omitted or set to `null` in the JSON falls back to the value
/// generated by `ColorScheme.fromSeed(seed)`.
///
/// JSON shape:
/// ```json
/// {
///   "fontFamily": "Poppins",
///   "light": { "seed": "#FF595E", "primary": null, ... },
///   "dark":  { "seed": "#6A4C93", "primary": null, ... }
/// }
/// ```
class AppThemeConfig {
  final Color lightSeed;
  final Color darkSeed;
  final String? fontFamily;

  /// Per-role overrides applied on top of the seed-generated light scheme.
  final Map<String, Color> lightOverrides;

  /// Per-role overrides applied on top of the seed-generated dark scheme.
  final Map<String, Color> darkOverrides;

  const AppThemeConfig({
    required this.lightSeed,
    required this.darkSeed,
    this.fontFamily,
    this.lightOverrides = const {},
    this.darkOverrides = const {},
  });

  static const AppThemeConfig defaults = AppThemeConfig(
    lightSeed: Color(0xFF6750A4),
    darkSeed: Color(0xFF6750A4),
  );

  factory AppThemeConfig.fromJson(Map<String, dynamic> json) {
    // If activeTheme is set, delegate to the matching preset in _themes.
    final activeKey = json['activeTheme'] as String?;
    if (activeKey != null) {
      final themes = (json['_themes'] as Map?)?.cast<String, dynamic>() ?? {};
      if (themes.containsKey(activeKey) && themes[activeKey] is Map) {
        return AppThemeConfig.fromJson(
          (themes[activeKey] as Map).cast<String, dynamic>(),
        );
      }
    }

    final lightJson = (json['light'] as Map?)?.cast<String, dynamic>() ?? {};
    final darkJson = (json['dark'] as Map?)?.cast<String, dynamic>() ?? {};

    final lightSeed = _parseColor(lightJson['seed'] as String? ?? '#6750A4');

    return AppThemeConfig(
      lightSeed: lightSeed,
      darkSeed: _parseColor(
        darkJson['seed'] as String? ??
            lightJson['seed'] as String? ??
            '#6750A4',
      ),
      fontFamily: json['fontFamily'] as String?,
      lightOverrides: _parseOverrides(lightJson),
      darkOverrides: _parseOverrides(darkJson),
    );
  }

  /// Extracts every key except `seed` that has a non-null string hex value.
  static Map<String, Color> _parseOverrides(Map<String, dynamic> json) {
    final result = <String, Color>{};
    for (final entry in json.entries) {
      if (entry.key == 'seed') continue;
      if (entry.value is String) {
        result[entry.key] = _parseColor(entry.value as String);
      }
    }
    return result;
  }

  static Color _parseColor(String hex) {
    final cleaned = hex.replaceFirst('#', '');
    final padded = cleaned.length == 6 ? 'FF$cleaned' : cleaned;
    return Color(int.parse(padded, radix: 16));
  }
}
