import 'dart:ui';

import 'app_shapes_extension.dart';
import 'app_theme_presets.dart';

/// Parsed representation of `assets/theme/theme_config.json`.
///
/// All 45 Material Design 3 color roles are supported as optional overrides.
/// Any role omitted or set to `null` in the JSON falls back to the value
/// generated by `ColorScheme.fromSeed(seed)`.
///
/// JSON shape:
/// ```json
/// {
///   "fontFamily": "Poppins",
///   "light": { "seed": "#FF595E", "primary": null, ... },
///   "dark":  { "seed": "#6A4C93", "primary": null, ... }
/// }
/// ```
class AppThemeConfig {
  final Color lightSeed;
  final Color darkSeed;
  final String? fontFamily;

  /// Per-role overrides applied on top of the seed-generated light scheme.
  final Map<String, Color> lightOverrides;

  /// Per-role overrides applied on top of the seed-generated dark scheme.
  final Map<String, Color> darkOverrides;

  /// Brand corner radii for buttons/chips/cards/inputs/sheets. Drives both the
  /// component themes (raw Material) and the atoms. Omitted → [AppShapes.standard].
  final AppShapes shapes;

  /// Visual-density adjustment applied to every Material widget (compact ≈ -2 …
  /// standard 0 … comfortable ≈ 1). Omitted → 0 (standard).
  final double density;

  const AppThemeConfig({
    required this.lightSeed,
    required this.darkSeed,
    this.fontFamily,
    this.lightOverrides = const {},
    this.darkOverrides = const {},
    this.shapes = AppShapes.standard,
    this.density = 0,
  });

  static const AppThemeConfig defaults = AppThemeConfig(
    lightSeed: Color(0xFF6750A4),
    darkSeed: Color(0xFF6750A4),
  );

  factory AppThemeConfig.fromJson(Map<String, dynamic> json) {
    // If activeTheme is set, resolve the named preset and build from it.
    // Look-up order: an inline `_themes` block in this file (back-compat),
    // then the shared presets in `app_theme_presets.dart` (kThemePresets).
    final activeKey = json['activeTheme'] as String?;
    if (activeKey != null) {
      final inline = (json['_themes'] as Map?)?.cast<String, dynamic>() ?? {};
      final preset = (inline[activeKey] is Map)
          ? (inline[activeKey] as Map).cast<String, dynamic>()
          : kThemePresets[activeKey];
      if (preset != null) return AppThemeConfig._fromThemeMap(preset);
    }

    return AppThemeConfig._fromThemeMap(json);
  }

  /// Builds a config from a single theme map: `fontFamily` + `light`/`dark`
  /// role maps. Does not consult `activeTheme`/`_themes` (already resolved).
  factory AppThemeConfig._fromThemeMap(Map<String, dynamic> json) {
    final lightJson = (json['light'] as Map?)?.cast<String, dynamic>() ?? {};
    final darkJson = (json['dark'] as Map?)?.cast<String, dynamic>() ?? {};

    final lightSeed = _parseColor(lightJson['seed'] as String? ?? '#6750A4');

    return AppThemeConfig(
      lightSeed: lightSeed,
      darkSeed: _parseColor(
        darkJson['seed'] as String? ??
            lightJson['seed'] as String? ??
            '#6750A4',
      ),
      fontFamily: json['fontFamily'] as String?,
      lightOverrides: _parseOverrides(lightJson),
      darkOverrides: _parseOverrides(darkJson),
      shapes: _parseShapes(json),
      density: (json['density'] as num?)?.toDouble() ?? 0,
    );
  }

  /// Reads an optional `shape` block (`{ button, chip, card, input, sheet }`),
  /// falling back to [AppShapes.standard] for the block and any missing key.
  static AppShapes _parseShapes(Map<String, dynamic> json) {
    final s = (json['shape'] as Map?)?.cast<String, dynamic>();
    if (s == null) return AppShapes.standard;
    double pick(String key, double fallback) {
      final v = s[key];
      return v is num ? v.toDouble() : fallback;
    }

    const base = AppShapes.standard;
    return base.copyWith(
      buttonRadius: pick('button', base.buttonRadius),
      chipRadius: pick('chip', base.chipRadius),
      cardRadius: pick('card', base.cardRadius),
      inputRadius: pick('input', base.inputRadius),
      sheetRadius: pick('sheet', base.sheetRadius),
    );
  }

  /// Extracts every key except `seed` that has a non-null string hex value.
  static Map<String, Color> _parseOverrides(Map<String, dynamic> json) {
    final result = <String, Color>{};
    for (final entry in json.entries) {
      if (entry.key == 'seed') continue;
      if (entry.value is String) {
        result[entry.key] = _parseColor(entry.value as String);
      }
    }
    return result;
  }

  static Color _parseColor(String hex) {
    final cleaned = hex.replaceFirst('#', '');
    final padded = cleaned.length == 6 ? 'FF$cleaned' : cleaned;
    return Color(int.parse(padded, radix: 16));
  }
}
