// The **France** sample catalog — a realistic French supermarket
// (Carrefour/Intermarché-style aisles, real French brands, € retail pricing),
// seeded in French because catalog content is single-valued (see
// docs/explanation/content-i18n-plan.md).
//
// Prices are French shelf prices, NOT converted from another market. The
// storefront's price filter uses per-currency bands (2/5/10 for euros — see
// cordelia's ProductPriceFilter), and a catalog that leaves a band empty makes
// that chip unmatched; npm run verify:seed-bands enforces the spread.
//
// Image sources (every URL is verified live by scripts/verify-seed-images.mjs
// — re-run it whenever this file changes):
// - Products: real French product photos from Open Food Facts
//   (images.openfoodfacts.org) — © Open Food Facts contributors, CC-BY-SA
//   4.0. Barcodes were harvested from OFF's French catalogue and every path
//   re-resolved through its product endpoint, because the search index returns
//   unpadded paths and stale revisions for short codes. Loose produce and the
//   whole Entretien aisle carry imageUrl "" — OFF is a packaged-*food*
//   database — and every consumer renders a placeholder.
// - Banners: landscape photography from Unsplash.
// - Brand logos: Google's favicon endpoint / DiceBear monograms.

import {
  OFF_IMAGE_BASE,
  type GrocerySeed,
} from "./seed-types";

const IMG = OFF_IMAGE_BASE;

export const FRANCE_SEED: GrocerySeed = {
  categories: [
    {
      slug: "fruits-legumes",
      name: "Fruits & Légumes",
      imageUrl: `${IMG}/308/368/114/8626/front_fr.33.400.jpg`,
      groupName: "Alimentation",
    },
    {
      slug: "cremerie",
      name: "Crèmerie & Œufs",
      imageUrl: `${IMG}/322/802/117/0039/front_fr.182.400.jpg`,
      groupName: "Alimentation",
    },
    {
      slug: "pain-petit-dejeuner",
      name: "Pain & Petit-déjeuner",
      imageUrl: `${IMG}/339/246/048/0827/front_fr.132.400.jpg`,
      groupName: "Alimentation",
    },
    {
      slug: "epicerie-salee",
      name: "Épicerie salée",
      imageUrl: `${IMG}/303/835/001/3606/front_fr.225.400.jpg`,
      groupName: "Alimentation",
    },
    {
      slug: "huiles-condiments",
      name: "Huiles & Condiments",
      imageUrl: `${IMG}/317/805/000/0749/front_fr.121.400.jpg`,
      groupName: "Alimentation",
    },
    {
      slug: "surgeles-traiteur",
      name: "Surgelés & Traiteur",
      imageUrl: `${IMG}/359/974/100/6305/front_fr.36.400.jpg`,
      groupName: "Alimentation",
    },
    {
      slug: "confiserie-biscuits",
      name: "Confiserie & Biscuits",
      imageUrl: `${IMG}/301/776/000/2073/front_fr.61.400.jpg`,
      groupName: "Snacks & Boissons",
    },
    {
      slug: "boissons",
      name: "Boissons & Eaux",
      imageUrl: `${IMG}/306/832/012/0256/front_en.61.400.jpg`,
      groupName: "Snacks & Boissons",
    },
    {
      slug: "cafe-the",
      name: "Café & Thé",
      imageUrl: `${IMG}/800/007/020/0289/front_fr.120.400.jpg`,
      groupName: "Snacks & Boissons",
    },
    {
      slug: "entretien-maison",
      name: "Entretien & Maison",
      imageUrl: "",
      groupName: "Entretien",
    },
  ],

  brands: [
    { slug: "lactel", name: "Lactel", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://lactel.fr&size=128" },
    { slug: "elle-et-vire", name: "Elle & Vire", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://elle-et-vire.com&size=128" },
    { slug: "president", name: "Président", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=President&size=128&fontWeight=600" },
    { slug: "boursin", name: "Boursin", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://boursin.fr&size=128" },
    { slug: "kiri", name: "Kiri", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Kiri&size=128&fontWeight=600" },
    { slug: "danone", name: "Danone", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://danone.fr&size=128" },
    { slug: "yoplait", name: "Yoplait", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://yoplait.fr&size=128" },
    { slug: "la-laitiere", name: "La Laitière", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=La%20Laitiere&size=128&fontWeight=600" },
    { slug: "sojasun", name: "Sojasun", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://sojasun.com&size=128" },
    { slug: "bridelice", name: "Bridélice", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Bridelice&size=128&fontWeight=600" },
    { slug: "alpro", name: "Alpro", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://alpro.com&size=128" },
    { slug: "la-boulangere", name: "La Boulangère", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://laboulangere.com&size=128" },
    { slug: "heudebert", name: "Heudebert", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Heudebert&size=128&fontWeight=600" },
    { slug: "bjorg", name: "Bjorg", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://bjorg.fr&size=128" },
    { slug: "belvita", name: "Belvita", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Belvita&size=128&fontWeight=600" },
    { slug: "jordans", name: "Jordans", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Jordans&size=128&fontWeight=600" },
    { slug: "nestle", name: "Nestlé", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://nestle.fr&size=128" },
    { slug: "bonne-maman", name: "Bonne Maman", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://bonnemaman.fr&size=128" },
    { slug: "nutella", name: "Nutella", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://nutella.com&size=128" },
    { slug: "francine", name: "Francine", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://francine.com&size=128" },
    { slug: "panzani", name: "Panzani", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://panzani.fr&size=128" },
    { slug: "rana", name: "Giovanni Rana", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Giovanni%20Rana&size=128&fontWeight=600" },
    { slug: "petit-navire", name: "Petit Navire", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://petitnavire.fr&size=128" },
    { slug: "saupiquet", name: "Saupiquet", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://saupiquet.fr&size=128" },
    { slug: "sodebo", name: "Sodebo", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://sodebo.com&size=128" },
    { slug: "mutti", name: "Mutti", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://mutti-parma.com&size=128" },
    { slug: "knorr", name: "Knorr", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://knorr.com&size=128" },
    { slug: "amora", name: "Amora", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Amora&size=128&fontWeight=600" },
    { slug: "raynal", name: "Raynal et Roquelaure", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Raynal%20et%20Roquelaure&size=128&fontWeight=600" },
    { slug: "daucy", name: "d'aucy", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://daucy.fr&size=128" },
    { slug: "daddy", name: "Daddy", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://daddy.fr&size=128" },
    { slug: "puget", name: "Puget", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://puget.fr&size=128" },
    { slug: "lesieur", name: "Lesieur", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://lesieur.fr&size=128" },
    { slug: "maille", name: "Maille", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://maille.com&size=128" },
    { slug: "benedicta", name: "Bénédicta", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Benedicta&size=128&fontWeight=600" },
    { slug: "findus", name: "Findus", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://findus.fr&size=128" },
    { slug: "marie", name: "Marie", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Marie&size=128&fontWeight=600" },
    { slug: "buitoni", name: "Buitoni", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Buitoni&size=128&fontWeight=600" },
    { slug: "carte-dor", name: "Carte d'Or", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Carte%20dOr&size=128&fontWeight=600" },
    { slug: "fleury-michon", name: "Fleury Michon", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://fleurymichon.fr&size=128" },
    { slug: "herta", name: "Herta", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://herta.fr&size=128" },
    { slug: "cote-dor", name: "Côte d'Or", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Côte%20dOr&size=128&fontWeight=600" },
    { slug: "milka", name: "Milka", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://milka.fr&size=128" },
    { slug: "lindt", name: "Lindt", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://lindt.fr&size=128" },
    { slug: "lu", name: "LU", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://lu.fr&size=128" },
    { slug: "st-michel", name: "St Michel", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=St%20Michel&size=128&fontWeight=600" },
    { slug: "bn", name: "BN", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=BN&size=128&fontWeight=600" },
    { slug: "haribo", name: "Haribo", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://haribo.com&size=128" },
    { slug: "kinder", name: "Kinder", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://kinder.com&size=128" },
    { slug: "gerble", name: "Gerblé", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://gerble.fr&size=128" },
    { slug: "wasa", name: "Wasa", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://wasa.com&size=128" },
    { slug: "brets", name: "Bret's", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://brets.fr&size=128" },
    { slug: "evian", name: "evian", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://evian.com&size=128" },
    { slug: "vittel", name: "Vittel", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Vittel&size=128&fontWeight=600" },
    { slug: "volvic", name: "Volvic", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://volvic.fr&size=128" },
    { slug: "badoit", name: "Badoit", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Badoit&size=128&fontWeight=600" },
    { slug: "perrier", name: "Perrier", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://perrier.com&size=128" },
    { slug: "cristaline", name: "Cristaline", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://cristaline.fr&size=128" },
    { slug: "oasis", name: "Oasis", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Oasis&size=128&fontWeight=600" },
    { slug: "tropicana", name: "Tropicana", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Tropicana&size=128&fontWeight=600" },
    { slug: "lipton", name: "Lipton", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://lipton.com&size=128" },
    { slug: "fanta", name: "Fanta", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://fanta.fr&size=128" },
    { slug: "andros", name: "Andros", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://andros.fr&size=128" },
    { slug: "carte-noire", name: "Carte Noire", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://cartenoire.fr&size=128" },
    { slug: "malongo", name: "Malongo", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://malongo.com&size=128" },
    { slug: "ricore", name: "Ricoré", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Ricore&size=128&fontWeight=600" },
    { slug: "elephant", name: "Éléphant", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Élephant&size=128&fontWeight=600" },
    { slug: "tramier", name: "Tramier", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Tramier&size=128&fontWeight=600" },
    { slug: "cassegrain", name: "Cassegrain", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Cassegrain&size=128&fontWeight=600" },
    { slug: "bonduelle", name: "Bonduelle", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://bonduelle.fr&size=128" },
    { slug: "tipiak", name: "Tipiak", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://tipiak.fr&size=128" },
  ],

  products: [
    {
      slug: "bananes",
      name: "Bananes",
      imageUrl: "",
      price: 1.85,
      unitValue: 1000,
      unitType: "g",
      description:
        "Bananes mûres à point, issues du commerce équitable.",
      stock: 120,
      categorySlugs: ["fruits-legumes"],
      isPopular: true,
    },
    {
      slug: "pommes-gala",
      name: "Pommes Gala",
      imageUrl: "",
      price: 2.49,
      unitValue: 1000,
      unitType: "g",
      description:
        "Pommes Gala croquantes et sucrées, origine France.",
      stock: 110,
      categorySlugs: ["fruits-legumes"],
    },
    {
      slug: "tomates-grappe",
      name: "Tomates grappe",
      imageUrl: "",
      price: 2.99,
      originalPrice: 3.49,
      unitValue: 1000,
      unitType: "g",
      description:
        "Tomates en grappe cueillies mûres, savoureuses en salade.",
      stock: 85,
      categorySlugs: ["fruits-legumes"],
      isPopular: true,
    },
    {
      slug: "courgettes",
      name: "Courgettes",
      imageUrl: "",
      price: 2.29,
      unitValue: 1000,
      unitType: "g",
      description:
        "Courgettes fermes, idéales poêlées ou en ratatouille.",
      stock: 75,
      categorySlugs: ["fruits-legumes"],
    },
    {
      slug: "carottes",
      name: "Carottes",
      imageUrl: "",
      price: 1.29,
      unitValue: 1000,
      unitType: "g",
      description:
        "Carottes de plein champ, lavées et prêtes à cuisiner.",
      stock: 100,
      categorySlugs: ["fruits-legumes"],
    },
    {
      slug: "pommes-de-terre",
      name: "Pommes de terre à chair ferme",
      imageUrl: "",
      price: 2.19,
      unitValue: 2000,
      unitType: "g",
      description:
        "Pommes de terre à chair ferme, parfaites en salade ou rissolées.",
      stock: 90,
      categorySlugs: ["fruits-legumes"],
    },
    {
      slug: "oignons",
      name: "Oignons jaunes",
      imageUrl: "",
      price: 1.19,
      unitValue: 1000,
      unitType: "g",
      description:
        "Oignons jaunes doux, la base de toutes les cuissons.",
      stock: 105,
      categorySlugs: ["fruits-legumes"],
    },
    {
      slug: "cassegrain-haricots-verts",
      name: "Cassegrain Haricots Verts extra-fins",
      imageUrl: `${IMG}/308/368/109/4923/front_fr.83.400.jpg`,
      price: 1.79,
      unitValue: 220,
      unitType: "g",
      description:
        "Haricots verts extra-fins, prêts à réchauffer.",
      stock: 80,
      categorySlugs: ["fruits-legumes"],
      brandSlug: "cassegrain",
    },
    {
      slug: "cassegrain-courgettes",
      name: "Cassegrain Courgettes à la provençale",
      imageUrl: `${IMG}/308/368/109/4459/front_en.41.400.jpg`,
      price: 2.49,
      unitValue: 375,
      unitType: "g",
      description:
        "Courgettes cuisinées à la provençale, à l'huile d'olive.",
      stock: 70,
      categorySlugs: ["fruits-legumes"],
      brandSlug: "cassegrain",
    },
    {
      slug: "bonduelle-carottes-rapees",
      name: "Bonduelle Carottes râpées au citron",
      imageUrl: `${IMG}/308/368/114/8626/front_fr.33.400.jpg`,
      price: 1.99,
      originalPrice: 2.39,
      unitValue: 500,
      unitType: "g",
      description:
        "Carottes râpées relevées au citron de Sicile, prêtes à servir.",
      stock: 75,
      categorySlugs: ["fruits-legumes"],
      brandSlug: "bonduelle",
      isPopular: true,
    },
    {
      slug: "cassegrain-petits-pois",
      name: "Cassegrain Petits Pois & Carottes",
      imageUrl: `${IMG}/308/368/048/2042/front_fr.87.400.jpg`,
      price: 1.69,
      unitValue: 200,
      unitType: "g",
      description:
        "Petits pois et carottes à l'étuvée, façon maison.",
      stock: 85,
      categorySlugs: ["fruits-legumes"],
      brandSlug: "cassegrain",
    },
    {
      slug: "tramier-olives",
      name: "Tramier Olives vertes dénoyautées",
      imageUrl: `${IMG}/301/723/300/1008/front_fr.72.400.jpg`,
      price: 2.39,
      unitValue: 160,
      unitType: "g",
      description:
        "Olives vertes dénoyautées, à l'apéritif ou en cuisine.",
      stock: 65,
      categorySlugs: ["fruits-legumes"],
      brandSlug: "tramier",
    },
    {
      slug: "lactel-matin-leger",
      name: "Lactel Matin Léger",
      imageUrl: `${IMG}/342/827/398/0046/front_en.150.400.jpg`,
      price: 1.15,
      unitValue: 1000,
      unitType: "ml",
      description:
        "Lait demi-écrémé allégé en lactose, plus digeste au petit-déjeuner.",
      stock: 140,
      categorySlugs: ["cremerie"],
      brandSlug: "lactel",
      sizeVariants: [
        { value: 1000, price: 1.15 },
        { value: 500, price: 0.75 },
      ],
      isPopular: true,
    },
    {
      slug: "elle-vire-beurre",
      name: "Elle & Vire Beurre Tendre Doux",
      imageUrl: `${IMG}/345/179/098/8677/front_en.186.400.jpg`,
      price: 2.95,
      originalPrice: 3.35,
      unitValue: 250,
      unitType: "g",
      description:
        "Beurre doux extra-tendre, tartinable à la sortie du réfrigérateur.",
      stock: 80,
      categorySlugs: ["cremerie"],
      brandSlug: "elle-et-vire",
      isPopular: true,
    },
    {
      slug: "president-camembert",
      name: "Président Camembert",
      imageUrl: `${IMG}/322/802/117/0039/front_fr.182.400.jpg`,
      price: 2.85,
      unitValue: 250,
      unitType: "g",
      description:
        "Camembert au lait pasteurisé, crémeux à cœur.",
      stock: 75,
      categorySlugs: ["cremerie"],
      brandSlug: "president",
      isPopular: true,
    },
    {
      slug: "president-emmental-rape",
      name: "Président Emmental râpé",
      imageUrl: `${IMG}/322/802/117/0046/front_fr.154.400.jpg`,
      price: 2.45,
      unitValue: 200,
      unitType: "g",
      description:
        "Emmental finement râpé, prêt à gratiner.",
      stock: 90,
      categorySlugs: ["cremerie"],
      brandSlug: "president",
    },
    {
      slug: "boursin",
      name: "Boursin Ail & Fines Herbes",
      imageUrl: `${IMG}/317/546/000/0017/front_en.200.400.jpg`,
      price: 2.55,
      unitValue: 150,
      unitType: "g",
      description:
        "Fromage frais à l'ail et aux fines herbes, à tartiner.",
      stock: 85,
      categorySlugs: ["cremerie"],
      brandSlug: "boursin",
      isPopular: true,
    },
    {
      slug: "kiri",
      name: "Kiri Crème",
      imageUrl: `${IMG}/307/378/113/1888/front_en.39.400.jpg`,
      price: 2.29,
      unitValue: 144,
      unitType: "g",
      description:
        "Huit portions de fromage frais à la crème, douces et fondantes.",
      stock: 80,
      categorySlugs: ["cremerie"],
      brandSlug: "kiri",
    },
    {
      slug: "danone-activia",
      name: "Danone Activia Noix de Coco",
      imageUrl: `${IMG}/303/349/135/0863/front_fr.123.400.jpg`,
      price: 2.19,
      unitValue: 500,
      unitType: "g",
      description:
        "Yaourts au bifidus saveur noix de coco, sans sucres ajoutés.",
      stock: 70,
      categorySlugs: ["cremerie"],
      brandSlug: "danone",
    },
    {
      slug: "yoplait-skyr",
      name: "Yoplait Skyr Nature",
      imageUrl: `${IMG}/332/977/007/7003/front_en.164.400.jpg`,
      price: 2.79,
      unitValue: 850,
      unitType: "g",
      description:
        "Skyr nature à la texture épaisse, riche en protéines.",
      stock: 65,
      categorySlugs: ["cremerie"],
      brandSlug: "yoplait",
    },
    {
      slug: "la-laitiere-yaourt-vanille",
      name: "La Laitière Yaourt à la Vanille",
      imageUrl: `${IMG}/302/329/002/1286/front_fr.44.400.jpg`,
      price: 3.19,
      unitValue: 1000,
      unitType: "g",
      description:
        "Huit yaourts onctueux à la vanille, recette à l'ancienne.",
      stock: 60,
      categorySlugs: ["cremerie"],
      brandSlug: "la-laitiere",
    },
    {
      slug: "sojasun-framboise",
      name: "Sojasun Framboise Passion",
      imageUrl: `${IMG}/327/322/008/2188/front_fr.121.400.jpg`,
      price: 2.49,
      unitValue: 400,
      unitType: "g",
      description:
        "Desserts au soja framboise-passion, sans lactose.",
      stock: 55,
      categorySlugs: ["cremerie"],
      brandSlug: "sojasun",
    },
    {
      slug: "bridelice-creme",
      name: "Bridélice Crème légère 18 %",
      imageUrl: `${IMG}/315/525/120/5388/front_en.351.400.jpg`,
      price: 2.29,
      unitValue: 600,
      unitType: "ml",
      description:
        "Crème légère semi-épaisse à 18 % de matière grasse, en trois briquettes.",
      stock: 70,
      categorySlugs: ["cremerie"],
      brandSlug: "bridelice",
    },
    {
      slug: "alpro-amande",
      name: "Alpro Amande Grillée sans sucres",
      imageUrl: `${IMG}/541/118/811/2709/front_en.927.400.jpg`,
      price: 2.35,
      unitValue: 1000,
      unitType: "ml",
      description:
        "Boisson à l'amande grillée sans sucres ajoutés.",
      stock: 65,
      categorySlugs: ["cremerie"],
      brandSlug: "alpro",
    },
    {
      slug: "oeufs-plein-air",
      name: "Œufs de poules élevées en plein air",
      imageUrl: "",
      price: 3.15,
      unitValue: 10,
      unitType: "pcs",
      description:
        "Dix œufs frais de poules élevées en plein air, calibre moyen.",
      stock: 95,
      categorySlugs: ["cremerie"],
      isPopular: true,
    },
    {
      slug: "baguette-tradition",
      name: "Baguette de tradition",
      imageUrl: "",
      price: 1.2,
      unitValue: 1,
      unitType: "pcs",
      description:
        "Baguette de tradition française cuite sur place, croûte croustillante.",
      stock: 130,
      categorySlugs: ["pain-petit-dejeuner"],
      isPopular: true,
    },
    {
      slug: "la-boulangere-baguettes",
      name: "La Boulangère Baguettes viennoises",
      imageUrl: `${IMG}/376/004/979/0672/front_fr.83.400.jpg`,
      price: 2.15,
      unitValue: 340,
      unitType: "g",
      description:
        "Quatre baguettes viennoises complètes, moelleuses au petit-déjeuner.",
      stock: 70,
      categorySlugs: ["pain-petit-dejeuner"],
      brandSlug: "la-boulangere",
    },
    {
      slug: "heudebert-biscottes",
      name: "Heudebert Biscottes 6 céréales",
      imageUrl: `${IMG}/339/246/048/0827/front_fr.132.400.jpg`,
      price: 1.95,
      unitValue: 300,
      unitType: "g",
      description:
        "Biscottes aux six céréales, croustillantes et légères.",
      stock: 85,
      categorySlugs: ["pain-petit-dejeuner"],
      brandSlug: "heudebert",
    },
    {
      slug: "bjorg-pain-complet",
      name: "Bjorg Pain complet 3 céréales",
      imageUrl: `${IMG}/322/982/001/9192/front_fr.192.400.jpg`,
      price: 2.65,
      unitValue: 500,
      unitType: "g",
      description:
        "Pain de mie complet bio aux trois céréales, tranché.",
      stock: 65,
      categorySlugs: ["pain-petit-dejeuner"],
      brandSlug: "bjorg",
    },
    {
      slug: "belvita-original",
      name: "Belvita Original",
      imageUrl: `${IMG}/762/221/071/3902/front_fr.140.400.jpg`,
      price: 3.29,
      originalPrice: 3.79,
      unitValue: 650,
      unitType: "g",
      description:
        "Biscuits du petit-déjeuner aux céréales complètes.",
      stock: 75,
      categorySlugs: ["pain-petit-dejeuner"],
      brandSlug: "belvita",
      isPopular: true,
    },
    {
      slug: "jordans-muesli",
      name: "Jordans Muesli fruits & noix",
      imageUrl: `${IMG}/501/047/734/8678/front_fr.226.400.jpg`,
      price: 4.19,
      unitValue: 750,
      unitType: "g",
      description:
        "Muesli croustillant à 30 % de fruits et de noix.",
      stock: 55,
      categorySlugs: ["pain-petit-dejeuner"],
      brandSlug: "jordans",
    },
    {
      slug: "nestle-chocapic",
      name: "Nestlé Chocapic Bio",
      imageUrl: `${IMG}/761/303/666/9146/front_en.213.400.jpg`,
      price: 3.49,
      unitValue: 375,
      unitType: "g",
      description:
        "Céréales bio au chocolat, source de fibres.",
      stock: 70,
      categorySlugs: ["pain-petit-dejeuner"],
      brandSlug: "nestle",
    },
    {
      slug: "bonne-maman-framboises",
      name: "Bonne Maman Confiture Framboises",
      imageUrl: `${IMG}/304/532/000/1570/front_fr.46.400.jpg`,
      price: 3.25,
      unitValue: 370,
      unitType: "g",
      description:
        "Confiture de framboises préparée comme à la maison.",
      stock: 80,
      categorySlugs: ["pain-petit-dejeuner"],
      brandSlug: "bonne-maman",
      isPopular: true,
    },
    {
      slug: "bonne-maman-madeleines",
      name: "Bonne Maman Madeleines pur beurre",
      imageUrl: `${IMG}/317/853/040/2728/front_en.112.400.jpg`,
      price: 3.45,
      unitValue: 300,
      unitType: "g",
      description:
        "Douze madeleines pur beurre, moelleuses et dorées.",
      stock: 65,
      categorySlugs: ["pain-petit-dejeuner"],
      brandSlug: "bonne-maman",
    },
    {
      slug: "nutella-biscuits",
      name: "Nutella Biscuits",
      imageUrl: `${IMG}/800/050/031/0427/front_fr.550.400.jpg`,
      price: 2.99,
      unitValue: 304,
      unitType: "g",
      description:
        "Biscuits croquants au cœur onctueux de Nutella.",
      stock: 90,
      categorySlugs: ["pain-petit-dejeuner"],
      brandSlug: "nutella",
      isPopular: true,
    },
    {
      slug: "andros-compote-pomme",
      name: "Andros Compote Pomme Nature",
      imageUrl: `${IMG}/360/858/078/9758/front_fr.80.400.jpg`,
      price: 2.79,
      unitValue: 730,
      unitType: "g",
      description:
        "Compote de pommes sans sucres ajoutés, en coupelles.",
      stock: 75,
      categorySlugs: ["pain-petit-dejeuner"],
      brandSlug: "andros",
    },
    {
      slug: "francine-farine",
      name: "Francine Farine de blé",
      imageUrl: `${IMG}/306/811/070/3232/front_fr.112.400.jpg`,
      price: 1.55,
      unitValue: 1000,
      unitType: "g",
      description:
        "Farine de blé première extraction, pour pâtisserie et sauces.",
      stock: 110,
      categorySlugs: ["pain-petit-dejeuner"],
      brandSlug: "francine",
    },
    {
      slug: "panzani-torti",
      name: "Panzani Torti",
      imageUrl: `${IMG}/303/835/001/3606/front_fr.225.400.jpg`,
      price: 1.35,
      originalPrice: 1.65,
      unitValue: 500,
      unitType: "g",
      description:
        "Torti de blé dur, cuisson 9 minutes.",
      stock: 130,
      categorySlugs: ["epicerie-salee"],
      brandSlug: "panzani",
      sizeVariants: [
        { value: 500, price: 1.35, originalPrice: 1.65 },
        { value: 1000, price: 2.45 },
      ],
      isPopular: true,
    },
    {
      slug: "rana-tortellini",
      name: "Giovanni Rana Tortellini ricotta & épinards",
      imageUrl: `${IMG}/800/166/571/4372/front_fr.3.400.jpg`,
      price: 3.49,
      unitValue: 250,
      unitType: "g",
      description:
        "Tortellini frais farcis ricotta et épinards, cuisson 3 minutes.",
      stock: 60,
      categorySlugs: ["epicerie-salee"],
      brandSlug: "rana",
    },
    {
      slug: "petit-navire-thon",
      name: "Petit Navire Thon entier au naturel",
      imageUrl: `${IMG}/301/908/123/9640/front_fr.82.400.jpg`,
      price: 2.79,
      unitValue: 93,
      unitType: "g",
      description:
        "Thon albacore entier au naturel, pêché à la ligne.",
      stock: 95,
      categorySlugs: ["epicerie-salee"],
      brandSlug: "petit-navire",
    },
    {
      slug: "saupiquet-maquereaux",
      name: "Saupiquet Filets de maquereaux à la moutarde",
      imageUrl: `${IMG}/316/595/705/8010/front_en.90.400.jpg`,
      price: 2.35,
      unitValue: 169,
      unitType: "g",
      description:
        "Filets de maquereaux à la moutarde de Dijon.",
      stock: 80,
      categorySlugs: ["epicerie-salee"],
      brandSlug: "saupiquet",
    },
    {
      slug: "sodebo-pastabox",
      name: "Sodebo PastaBox Bolognaise",
      imageUrl: `${IMG}/324/227/227/0157/front_fr.84.400.jpg`,
      price: 3.29,
      unitValue: 330,
      unitType: "g",
      description:
        "Pâtes fraîches à la bolognaise, prêtes en 1 minute.",
      stock: 70,
      categorySlugs: ["epicerie-salee"],
      brandSlug: "sodebo",
    },
    {
      slug: "mutti-pulpe",
      name: "Mutti Pulpe fine de tomates",
      imageUrl: `${IMG}/000/008/004/2556/front_en.449.400.jpg`,
      price: 1.35,
      unitValue: 400,
      unitType: "g",
      description:
        "Pulpe fine de tomates 100 % italiennes.",
      stock: 120,
      categorySlugs: ["epicerie-salee"],
      brandSlug: "mutti",
      isPopular: true,
    },
    {
      slug: "knorr-bouillon",
      name: "Knorr Bouillon de légumes",
      imageUrl: `${IMG}/871/256/643/2127/front_fr.73.400.jpg`,
      price: 2.19,
      unitValue: 109,
      unitType: "g",
      description:
        "Bouillon de légumes en cubes, pour soupes et risottos.",
      stock: 100,
      categorySlugs: ["epicerie-salee"],
      brandSlug: "knorr",
    },
    {
      slug: "amora-cornichons",
      name: "Amora Cornichons extra-fins",
      imageUrl: `${IMG}/871/120/046/0755/front_en.73.400.jpg`,
      price: 2.45,
      unitValue: 205,
      unitType: "g",
      description:
        "Cornichons extra-fins croquants, au vinaigre.",
      stock: 85,
      categorySlugs: ["epicerie-salee"],
      brandSlug: "amora",
    },
    {
      slug: "raynal-lentilles",
      name: "Raynal Lentilles cuisinées à l'auvergnate",
      imageUrl: `${IMG}/302/169/020/1123/front_fr.115.400.jpg`,
      price: 2.89,
      unitValue: 410,
      unitType: "g",
      description:
        "Lentilles vertes cuisinées à l'auvergnate, plat complet.",
      stock: 60,
      categorySlugs: ["epicerie-salee"],
      brandSlug: "raynal",
    },
    {
      slug: "daucy-pois-chiches",
      name: "d'aucy Curry de pois chiches",
      imageUrl: `${IMG}/301/780/050/9937/front_fr.83.400.jpg`,
      price: 2.59,
      unitValue: 380,
      unitType: "g",
      description:
        "Pois chiches au curry doux, prêts à réchauffer.",
      stock: 65,
      categorySlugs: ["epicerie-salee"],
      brandSlug: "daucy",
    },
    {
      slug: "daddy-sucre",
      name: "Daddy Sucre en poudre",
      imageUrl: `${IMG}/316/543/371/4010/front_fr.117.400.jpg`,
      price: 1.65,
      unitValue: 750,
      unitType: "g",
      description:
        "Sucre en poudre de betterave française.",
      stock: 115,
      categorySlugs: ["epicerie-salee"],
      brandSlug: "daddy",
    },
    {
      slug: "riz-long-grain",
      name: "Riz long grain",
      imageUrl: "",
      price: 2.35,
      unitValue: 1000,
      unitType: "g",
      description:
        "Riz long grain à cuisson rapide, grains bien détachés.",
      stock: 100,
      categorySlugs: ["epicerie-salee"],
    },
    {
      slug: "puget-huile-olive",
      name: "Puget Huile d'olive vierge extra",
      imageUrl: `${IMG}/317/805/000/0749/front_fr.121.400.jpg`,
      price: 8.45,
      originalPrice: 9.45,
      unitValue: 1000,
      unitType: "ml",
      description:
        "Huile d'olive vierge extra, fruitée et douce.",
      stock: 55,
      categorySlugs: ["huiles-condiments"],
      brandSlug: "puget",
      isPopular: true,
    },
    {
      slug: "lesieur-isio4",
      name: "Lesieur Isio 4",
      imageUrl: `${IMG}/326/547/400/0018/front_fr.125.400.jpg`,
      price: 4.29,
      unitValue: 1000,
      unitType: "ml",
      description:
        "Mélange de quatre huiles riche en oméga 3, pour cuisson et assaisonnement.",
      stock: 75,
      categorySlugs: ["huiles-condiments"],
      brandSlug: "lesieur",
    },
    {
      slug: "amora-moutarde",
      name: "Amora Moutarde de Dijon forte",
      imageUrl: `${IMG}/325/054/661/0271/front_en.177.400.jpg`,
      price: 1.85,
      unitValue: 265,
      unitType: "g",
      description:
        "Moutarde de Dijon forte, relevée comme il faut.",
      stock: 100,
      categorySlugs: ["huiles-condiments"],
      brandSlug: "amora",
      isPopular: true,
    },
    {
      slug: "maille-vinaigrette",
      name: "Maille Vinaigrette légère 3 vinaigres",
      imageUrl: `${IMG}/871/410/084/6155/front_en.98.400.jpg`,
      price: 2.75,
      unitValue: 360,
      unitType: "ml",
      description:
        "Vinaigrette légère aux trois vinaigres, prête à l'emploi.",
      stock: 70,
      categorySlugs: ["huiles-condiments"],
      brandSlug: "maille",
    },
    {
      slug: "benedicta-bearnaise",
      name: "Bénédicta Sauce Béarnaise",
      imageUrl: `${IMG}/366/060/300/4774/front_fr.105.400.jpg`,
      price: 2.45,
      unitValue: 260,
      unitType: "g",
      description:
        "Sauce béarnaise onctueuse, à l'estragon.",
      stock: 65,
      categorySlugs: ["huiles-condiments"],
      brandSlug: "benedicta",
    },
    {
      slug: "benedicta-mayonnaise",
      name: "Bénédicta Mayonnaise",
      imageUrl: `${IMG}/366/060/308/1973/front_fr.36.400.jpg`,
      price: 2.15,
      unitValue: 175,
      unitType: "g",
      description:
        "Mayonnaise nature à la moutarde de Dijon.",
      stock: 80,
      categorySlugs: ["huiles-condiments"],
      brandSlug: "benedicta",
    },
    {
      slug: "sel-de-mer",
      name: "Sel de mer fin",
      imageUrl: "",
      price: 0.95,
      unitValue: 500,
      unitType: "g",
      description:
        "Sel de mer fin récolté par évaporation naturelle.",
      stock: 120,
      categorySlugs: ["huiles-condiments"],
    },
    {
      slug: "poivre-moulu",
      name: "Poivre noir moulu",
      imageUrl: "",
      price: 1.55,
      unitValue: 100,
      unitType: "g",
      description:
        "Poivre noir moulu, puissant et parfumé.",
      stock: 95,
      categorySlugs: ["huiles-condiments"],
    },
    {
      slug: "vinaigre-vin",
      name: "Vinaigre de vin blanc",
      imageUrl: "",
      price: 1.35,
      unitValue: 500,
      unitType: "ml",
      description:
        "Vinaigre de vin blanc doux, pour salades et marinades.",
      stock: 85,
      categorySlugs: ["huiles-condiments"],
    },
    {
      slug: "findus-croustibat",
      name: "Findus Croustibat",
      imageUrl: `${IMG}/359/974/100/6305/front_fr.36.400.jpg`,
      price: 4.29,
      originalPrice: 4.99,
      unitValue: 540,
      unitType: "g",
      description:
        "Panés de filets de colin, croustillants au four.",
      stock: 65,
      categorySlugs: ["surgeles-traiteur"],
      brandSlug: "findus",
      isPopular: true,
    },
    {
      slug: "marie-pizza-tartiflette",
      name: "Marie Pizza Tartiflette",
      imageUrl: `${IMG}/324/883/072/1628/front_fr.18.400.jpg`,
      price: 3.79,
      unitValue: 550,
      unitType: "g",
      description:
        "Pizza tartiflette au reblochon et lardons, cuite au four.",
      stock: 60,
      categorySlugs: ["surgeles-traiteur"],
      brandSlug: "marie",
    },
    {
      slug: "buitoni-piccolinis",
      name: "Buitoni Piccolinis Jambon Fromage",
      imageUrl: `${IMG}/844/529/058/1129/front_fr.68.400.jpg`,
      price: 3.15,
      unitValue: 270,
      unitType: "g",
      description:
        "Neuf mini-pizzas jambon-fromage, prêtes en 12 minutes.",
      stock: 70,
      categorySlugs: ["surgeles-traiteur"],
      brandSlug: "buitoni",
    },
    {
      slug: "carte-dor-vanille",
      name: "Carte d'Or Crème glacée Vanille",
      imageUrl: `${IMG}/871/132/738/5603/front_fr.126.400.jpg`,
      price: 3.95,
      unitValue: 472,
      unitType: "g",
      description:
        "Crème glacée à la vanille de Madagascar.",
      stock: 55,
      categorySlugs: ["surgeles-traiteur"],
      brandSlug: "carte-dor",
      isPopular: true,
    },
    {
      slug: "fleury-michon-moelleux",
      name: "Fleury Michon Le Moelleux",
      imageUrl: `${IMG}/330/274/005/7052/front_fr.25.400.jpg`,
      price: 3.35,
      unitValue: 190,
      unitType: "g",
      description:
        "Blanc de poulet moelleux, tranché et prêt à garnir.",
      stock: 75,
      categorySlugs: ["surgeles-traiteur"],
      brandSlug: "fleury-michon",
    },
    {
      slug: "fleury-michon-allumettes",
      name: "Fleury Michon Allumettes de jambon",
      imageUrl: `${IMG}/309/575/891/4010/front_fr.197.400.jpg`,
      price: 2.25,
      unitValue: 150,
      unitType: "g",
      description:
        "Allumettes de jambon, pour quiches et salades.",
      stock: 85,
      categorySlugs: ["surgeles-traiteur"],
      brandSlug: "fleury-michon",
    },
    {
      slug: "herta-knacki",
      name: "Herta Knacki 100 % pur porc",
      imageUrl: `${IMG}/315/423/080/1368/front_fr.71.400.jpg`,
      price: 2.95,
      unitValue: 350,
      unitType: "g",
      description:
        "Saucisses Knacki 100 % pur porc, à réchauffer.",
      stock: 90,
      categorySlugs: ["surgeles-traiteur"],
      brandSlug: "herta",
      isPopular: true,
    },
    {
      slug: "epinards-haches",
      name: "Épinards hachés surgelés",
      imageUrl: "",
      price: 1.45,
      unitValue: 450,
      unitType: "g",
      description:
        "Épinards hachés en portions, surgelés après récolte.",
      stock: 85,
      categorySlugs: ["surgeles-traiteur"],
    },
    {
      slug: "frites-four",
      name: "Frites au four",
      imageUrl: "",
      price: 2.45,
      unitValue: 1000,
      unitType: "g",
      description:
        "Frites précuites à dorer au four, sans friture.",
      stock: 95,
      categorySlugs: ["surgeles-traiteur"],
    },
    {
      slug: "cote-dor-noir-noisettes",
      name: "Côte d'Or Noir Noisettes entières",
      imageUrl: `${IMG}/762/221/099/5087/front_fr.242.400.jpg`,
      price: 2.65,
      unitValue: 180,
      unitType: "g",
      description:
        "Chocolat noir aux noisettes entières.",
      stock: 85,
      categorySlugs: ["confiserie-biscuits"],
      brandSlug: "cote-dor",
    },
    {
      slug: "milka-lait-alpin",
      name: "Milka Chocolat au lait du Pays Alpin",
      imageUrl: `${IMG}/304/514/010/5502/front_fr.625.400.jpg`,
      price: 1.55,
      originalPrice: 1.85,
      unitValue: 100,
      unitType: "g",
      description:
        "Tablette de chocolat au lait alpin, fondante.",
      stock: 120,
      categorySlugs: ["confiserie-biscuits"],
      brandSlug: "milka",
      isPopular: true,
    },
    {
      slug: "lindt-noir-70",
      name: "Lindt Excellence Noir 70 %",
      imageUrl: `${IMG}/304/692/002/2651/front_en.159.400.jpg`,
      price: 2.35,
      unitValue: 100,
      unitType: "g",
      description:
        "Chocolat noir intense à 70 % de cacao.",
      stock: 80,
      categorySlugs: ["confiserie-biscuits"],
      brandSlug: "lindt",
    },
    {
      slug: "lu-petit-ecolier",
      name: "LU Petit Écolier chocolat au lait",
      imageUrl: `${IMG}/301/776/000/2073/front_fr.61.400.jpg`,
      price: 1.85,
      unitValue: 150,
      unitType: "g",
      description:
        "Biscuits sablés nappés de chocolat au lait.",
      stock: 110,
      categorySlugs: ["confiserie-biscuits"],
      brandSlug: "lu",
      isPopular: true,
    },
    {
      slug: "lu-petit-beurre",
      name: "LU Véritable Petit Beurre",
      imageUrl: `${IMG}/301/776/000/0062/front_en.70.400.jpg`,
      price: 1.65,
      unitValue: 300,
      unitType: "g",
      description:
        "Le Petit Beurre à 52 dents, depuis 1886.",
      stock: 105,
      categorySlugs: ["confiserie-biscuits"],
      brandSlug: "lu",
    },
    {
      slug: "st-michel-galettes",
      name: "St Michel Galettes au bon beurre",
      imageUrl: `${IMG}/302/347/000/1015/front_fr.306.400.jpg`,
      price: 2.15,
      unitValue: 130,
      unitType: "g",
      description:
        "Vingt galettes bretonnes au bon beurre.",
      stock: 75,
      categorySlugs: ["confiserie-biscuits"],
      brandSlug: "st-michel",
    },
    {
      slug: "bn-chocolat",
      name: "BN Biscuits goût chocolat",
      imageUrl: `${IMG}/306/199/014/3365/front_en.95.400.jpg`,
      price: 1.95,
      unitValue: 285,
      unitType: "g",
      description:
        "Biscuits fourrés au chocolat, le goûter des enfants.",
      stock: 90,
      categorySlugs: ["confiserie-biscuits"],
      brandSlug: "bn",
    },
    {
      slug: "haribo-dragibus",
      name: "Haribo Dragibus Soft",
      imageUrl: `${IMG}/310/322/004/8658/front_en.39.400.jpg`,
      price: 2.29,
      unitValue: 300,
      unitType: "g",
      description:
        "Les Dragibus tendres, en sachet familial.",
      stock: 100,
      categorySlugs: ["confiserie-biscuits"],
      brandSlug: "haribo",
      isPopular: true,
    },
    {
      slug: "kinder-bueno",
      name: "Kinder Bueno",
      imageUrl: `${IMG}/000/008/005/2760/front_en.503.400.jpg`,
      price: 1.19,
      unitValue: 43,
      unitType: "g",
      description:
        "Deux barres gaufrées au lait et aux noisettes.",
      stock: 140,
      categorySlugs: ["confiserie-biscuits"],
      brandSlug: "kinder",
    },
    {
      slug: "gerble-sesame",
      name: "Gerblé Sésame",
      imageUrl: `${IMG}/317/568/001/1480/front_fr.325.400.jpg`,
      price: 2.85,
      unitValue: 230,
      unitType: "g",
      description:
        "Biscuits au sésame, source de fibres.",
      stock: 60,
      categorySlugs: ["confiserie-biscuits"],
      brandSlug: "gerble",
    },
    {
      slug: "wasa-tartine",
      name: "Wasa Tartine croustillante",
      imageUrl: `${IMG}/730/040/048/1595/front_fr.265.400.jpg`,
      price: 2.25,
      unitValue: 275,
      unitType: "g",
      description:
        "Tartines croustillantes de seigle, à garnir.",
      stock: 70,
      categorySlugs: ["confiserie-biscuits"],
      brandSlug: "wasa",
    },
    {
      slug: "tipiak-meli-melo",
      name: "Tipiak Méli-mélo gourmand",
      imageUrl: `${IMG}/360/090/000/5067/front_fr.447.400.jpg`,
      price: 2.79,
      unitValue: 330,
      unitType: "g",
      description:
        "Mélange de graines et de fruits secs à grignoter à l'apéritif.",
      stock: 70,
      categorySlugs: ["confiserie-biscuits"],
      brandSlug: "tipiak",
    },
    {
      slug: "brets-chips-vinaigre",
      name: "Bret's Chips Sel & Vinaigre",
      imageUrl: `${IMG}/349/791/110/5127/front_fr.214.400.jpg`,
      price: 1.79,
      unitValue: 125,
      unitType: "g",
      description:
        "Chips saveur sel et vinaigre, coupées épaisses.",
      stock: 95,
      categorySlugs: ["confiserie-biscuits"],
      brandSlug: "brets",
    },
    {
      slug: "milka-pate-tartiner",
      name: "Milka Pâte à tartiner noisettes",
      imageUrl: `${IMG}/762/220/151/5447/front_fr.50.400.jpg`,
      price: 4.49,
      unitValue: 740,
      unitType: "g",
      description:
        "Pâte à tartiner Milka aux noisettes, en grand pot.",
      stock: 65,
      categorySlugs: ["confiserie-biscuits"],
      brandSlug: "milka",
    },
    {
      slug: "evian",
      name: "evian Eau minérale naturelle",
      imageUrl: `${IMG}/306/832/012/0256/front_en.61.400.jpg`,
      price: 0.95,
      unitValue: 1500,
      unitType: "ml",
      description:
        "Eau minérale naturelle des Alpes, filtrée par la roche.",
      stock: 200,
      categorySlugs: ["boissons"],
      brandSlug: "evian",
      sizeVariants: [
        { value: 1500, price: 0.95 },
        { value: 1000, price: 0.75 },
      ],
      isPopular: true,
    },
    {
      slug: "vittel",
      name: "Vittel Eau minérale",
      imageUrl: `${IMG}/761/303/624/9928/front_fr.520.400.jpg`,
      price: 0.89,
      unitValue: 1500,
      unitType: "ml",
      description:
        "Eau minérale naturelle, légère au quotidien.",
      stock: 190,
      categorySlugs: ["boissons"],
      brandSlug: "vittel",
    },
    {
      slug: "volvic-zest-citron",
      name: "Volvic Zest Citron",
      imageUrl: `${IMG}/305/764/037/9048/front_fr.96.400.jpg`,
      price: 1.29,
      unitValue: 1500,
      unitType: "ml",
      description:
        "Eau aromatisée au citron, sans sucres.",
      stock: 130,
      categorySlugs: ["boissons"],
      brandSlug: "volvic",
    },
    {
      slug: "badoit",
      name: "Badoit",
      imageUrl: `${IMG}/306/832/011/4453/front_de.106.400.jpg`,
      price: 1.15,
      unitValue: 1000,
      unitType: "ml",
      description:
        "Eau minérale finement pétillante, à table.",
      stock: 140,
      categorySlugs: ["boissons"],
      brandSlug: "badoit",
    },
    {
      slug: "perrier",
      name: "Perrier",
      imageUrl: `${IMG}/761/303/583/3272/front_en.149.400.jpg`,
      price: 1.09,
      unitValue: 1000,
      unitType: "ml",
      description:
        "Eau gazeuse aux bulles vives, la référence de l'apéritif.",
      stock: 150,
      categorySlugs: ["boissons"],
      brandSlug: "perrier",
      isPopular: true,
    },
    {
      slug: "cristaline",
      name: "Cristaline Eau de source",
      imageUrl: `${IMG}/327/408/000/5003/front_en.797.400.jpg`,
      price: 0.45,
      unitValue: 1500,
      unitType: "ml",
      description:
        "Eau de source française, le format quotidien.",
      stock: 220,
      categorySlugs: ["boissons"],
      brandSlug: "cristaline",
    },
    {
      slug: "oasis-tropical",
      name: "Oasis Tropical",
      imageUrl: `${IMG}/312/448/019/1182/front_en.145.400.jpg`,
      price: 2.19,
      unitValue: 2000,
      unitType: "ml",
      description:
        "Boisson aux fruits tropicaux, sans colorants.",
      stock: 120,
      categorySlugs: ["boissons"],
      brandSlug: "oasis",
      isPopular: true,
    },
    {
      slug: "tropicana-orange",
      name: "Tropicana 100 % oranges pressées",
      imageUrl: `${IMG}/350/211/000/9449/front_en.151.400.jpg`,
      price: 3.29,
      originalPrice: 3.79,
      unitValue: 1000,
      unitType: "ml",
      description:
        "Jus d'oranges pressées sans pulpe, non concentré.",
      stock: 95,
      categorySlugs: ["boissons"],
      brandSlug: "tropicana",
      isPopular: true,
    },
    {
      slug: "lipton-ice-tea",
      name: "Lipton Ice Tea",
      imageUrl: `${IMG}/316/893/017/1058/front_fr.30.400.jpg`,
      price: 2.25,
      unitValue: 1750,
      unitType: "ml",
      description:
        "Thé glacé saveur pêche, à partager.",
      stock: 110,
      categorySlugs: ["boissons"],
      brandSlug: "lipton",
    },
    {
      slug: "fanta-citron",
      name: "Fanta Citron frappé",
      imageUrl: `${IMG}/544/900/000/6004/front_en.181.400.jpg`,
      price: 0.95,
      unitValue: 330,
      unitType: "ml",
      description:
        "Fanta citron en canette, bien frais.",
      stock: 160,
      categorySlugs: ["boissons"],
      brandSlug: "fanta",
    },
    {
      slug: "carte-noire",
      name: "Carte Noire Café moulu",
      imageUrl: `${IMG}/800/007/020/0289/front_fr.120.400.jpg`,
      price: 4.65,
      originalPrice: 5.29,
      unitValue: 250,
      unitType: "g",
      description:
        "Café moulu pur arabica, torréfaction intense.",
      stock: 85,
      categorySlugs: ["cafe-the"],
      brandSlug: "carte-noire",
      isPopular: true,
    },
    {
      slug: "malongo-arabica",
      name: "Malongo Café moulu pur arabica",
      imageUrl: `${IMG}/318/757/001/5447/front_fr.108.400.jpg`,
      price: 5.95,
      unitValue: 250,
      unitType: "g",
      description:
        "Café moulu pur arabica de petits producteurs, commerce équitable.",
      stock: 60,
      categorySlugs: ["cafe-the"],
      brandSlug: "malongo",
    },
    {
      slug: "ricore",
      name: "Ricoré",
      imageUrl: `${IMG}/761/303/265/5495/front_fr.365.400.jpg`,
      price: 4.29,
      unitValue: 260,
      unitType: "g",
      description:
        "L'ami du petit-déjeuner : chicorée et café soluble.",
      stock: 80,
      categorySlugs: ["cafe-the"],
      brandSlug: "ricore",
      isPopular: true,
    },
    {
      slug: "elephant-infusion",
      name: "Éléphant Infusion Detox",
      imageUrl: `${IMG}/871/132/750/1119/front_fr.56.400.jpg`,
      price: 2.85,
      unitValue: 34,
      unitType: "g",
      description:
        "Infusion à froid cranberry-framboise, sans caféine.",
      stock: 70,
      categorySlugs: ["cafe-the"],
      brandSlug: "elephant",
    },
    {
      slug: "cafe-moulu-maison",
      name: "Café moulu maison",
      imageUrl: "",
      price: 3.95,
      unitValue: 500,
      unitType: "g",
      description:
        "Café moulu équilibré, pour cafetière filtre.",
      stock: 90,
      categorySlugs: ["cafe-the"],
    },
    {
      slug: "the-vert",
      name: "Thé vert nature",
      imageUrl: "",
      price: 2.45,
      unitValue: 25,
      unitType: "pcs",
      description:
        "Vingt-cinq sachets de thé vert nature.",
      stock: 85,
      categorySlugs: ["cafe-the"],
    },
    {
      slug: "dosettes-espresso",
      name: "Dosettes espresso",
      imageUrl: "",
      price: 4.95,
      unitValue: 40,
      unitType: "pcs",
      description:
        "Quarante dosettes souples compatibles, torréfaction espresso.",
      stock: 75,
      categorySlugs: ["cafe-the"],
    },
    {
      slug: "liquide-vaisselle",
      name: "Liquide vaisselle Citron",
      imageUrl: "",
      price: 1.35,
      unitValue: 500,
      unitType: "ml",
      description:
        "Liquide vaisselle dégraissant au citron, mousse longue durée.",
      stock: 100,
      categorySlugs: ["entretien-maison"],
    },
    {
      slug: "nettoyant-multi-usage",
      name: "Nettoyant multi-usage",
      imageUrl: "",
      price: 1.85,
      unitValue: 1000,
      unitType: "ml",
      description:
        "Nettoyant multi-usage pour toutes surfaces lavables.",
      stock: 90,
      categorySlugs: ["entretien-maison"],
    },
    {
      slug: "papier-toilette",
      name: "Papier toilette 3 épaisseurs",
      imageUrl: "",
      price: 4.15,
      originalPrice: 4.79,
      unitValue: 12,
      unitType: "pcs",
      description:
        "Douze rouleaux trois épaisseurs, doux et résistants.",
      stock: 120,
      categorySlugs: ["entretien-maison"],
      isPopular: true,
    },
    {
      slug: "essuie-tout",
      name: "Essuie-tout",
      imageUrl: "",
      price: 2.65,
      unitValue: 4,
      unitType: "pcs",
      description:
        "Quatre rouleaux d'essuie-tout très absorbants.",
      stock: 110,
      categorySlugs: ["entretien-maison"],
    },
    {
      slug: "sacs-poubelle",
      name: "Sacs poubelle 50 l",
      imageUrl: "",
      price: 2.35,
      unitValue: 20,
      unitType: "pcs",
      description:
        "Vingt sacs poubelle résistants avec liens coulissants.",
      stock: 95,
      categorySlugs: ["entretien-maison"],
    },
    {
      slug: "lessive-liquide",
      name: "Lessive liquide",
      imageUrl: "",
      price: 12.49,
      originalPrice: 14.29,
      unitValue: 3000,
      unitType: "ml",
      description:
        "Lessive liquide pour 60 lavages, efficace dès 20 °C.",
      stock: 60,
      categorySlugs: ["entretien-maison"],
      isPopular: true,
    },
    {
      slug: "tablettes-lave-vaisselle",
      name: "Tablettes lave-vaisselle tout-en-un",
      imageUrl: "",
      price: 13.99,
      unitValue: 60,
      unitType: "pcs",
      description:
        "Soixante tablettes tout-en-un avec sel et liquide de rinçage.",
      stock: 70,
      categorySlugs: ["entretien-maison"],
    },
    {
      slug: "dentifrice",
      name: "Dentifrice protection complète",
      imageUrl: "",
      price: 2.05,
      unitValue: 75,
      unitType: "ml",
      description:
        "Dentifrice au fluor pour une protection quotidienne contre les caries.",
      stock: 105,
      categorySlugs: ["entretien-maison"],
    },
  ],

  coupons: [
    {
      code: "BIENVENUE10",
      type: "percent",
      value: 10,
      scope: "store",
      minOrderValue: 20,
      maxDiscount: 5,
      usageLimit: 500,
      perUserLimit: 1,
    },
    {
      code: "PRIMEUR5",
      type: "percent",
      value: 5,
      scope: "category",
      targetCategorySlugs: ["fruits-legumes"],
      minOrderValue: 10,
      maxDiscount: 3,
      usageLimit: 300,
      perUserLimit: 2,
    },
    {
      code: "CAFE15",
      type: "percent",
      value: 15,
      scope: "category",
      targetCategorySlugs: ["cafe-the"],
      minOrderValue: 15,
      maxDiscount: 5,
      usageLimit: 200,
      perUserLimit: 1,
    },
    {
      code: "GOURMAND2",
      type: "flat",
      value: 2,
      scope: "category",
      targetCategorySlugs: ["confiserie-biscuits"],
      minOrderValue: 12,
      maxDiscount: 2,
      usageLimit: 250,
      perUserLimit: 2,
    },
    {
      code: "MAISON3",
      type: "flat",
      value: 3,
      scope: "category",
      targetCategorySlugs: ["entretien-maison"],
      minOrderValue: 25,
      maxDiscount: 3,
      usageLimit: 150,
      perUserLimit: 1,
    },
    {
      code: "SURGELE1",
      type: "flat",
      value: 1,
      scope: "product",
      targetProductSlugs: ["findus-croustibat", "marie-pizza-tartiflette", "buitoni-piccolinis"],
      minOrderValue: 6,
      maxDiscount: 1,
      usageLimit: 400,
      perUserLimit: 3,
    },
    {
      code: "LIVRAISON",
      type: "flat",
      value: 4,
      scope: "store",
      minOrderValue: 40,
      maxDiscount: 4,
      usageLimit: 400,
      perUserLimit: 1,
    },
  ],

  banners: [
    {
      title: "Le marché chaque matin",
      subtitle: "Fruits et légumes livrés du jour",
      imageUrl:
        "https://images.unsplash.com/photo-1542838132-92c53300491e?w=1200&q=80",
      targetCategorySlug: "fruits-legumes",
      sortOrder: 0,
      backgroundColor: "#1F6F4A",
    },
    {
      title: "L'heure du café",
      subtitle: "Jusqu'à 15 % sur le café moulu et les dosettes",
      imageUrl:
        "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=1200&q=80",
      targetCategorySlug: "cafe-the",
      sortOrder: 1,
      backgroundColor: "#4A2C1A",
    },
    {
      title: "Pause gourmande",
      subtitle: "Chocolats et biscuits en promotion",
      imageUrl:
        "https://images.unsplash.com/photo-1481391319762-47dff72954d9?w=1200&q=80",
      targetCategorySlug: "confiserie-biscuits",
      sortOrder: 2,
      backgroundColor: "#7A1F3D",
    },
    {
      title: "Les placards pleins",
      subtitle: "Pâtes, riz et conserves en format familial",
      imageUrl:
        "https://images.unsplash.com/photo-1556909212-d5b604d0c90d?w=1200&q=80",
      targetCategorySlug: "epicerie-salee",
      sortOrder: 3,
      backgroundColor: "#2A4C7A",
    },
  ],
};
