// The **Germany** sample catalog — a realistic German supermarket
// (Rewe/Edeka-style aisles, real German brands, € retail pricing), seeded in
// German because catalog content is single-valued (see
// docs/explanation/content-i18n-plan.md).
//
// Prices are German shelf prices, NOT the India catalog's rupee figures
// converted. That matters beyond realism: the storefront's price filter uses
// per-currency bands (2/5/10 for euros — see cordelia's ProductPriceFilter),
// and converted rupee prices would pile into a single band and make the filter
// inert.
//
// Image sources (every URL is verified live by scripts/verify-seed-images.mjs
// — re-run it whenever this file changes):
// - Products: real German product photos from Open Food Facts
//   (images.openfoodfacts.org) — © Open Food Facts contributors, CC-BY-SA
//   4.0. Barcodes were harvested from OFF's German catalogue; fresh produce
//   and the whole Haushalt aisle carry imageUrl "" because OFF is a
//   packaged-*food* database, and every consumer renders a placeholder.
// - Banners: landscape photography from Unsplash.
// - Brand logos: Google's favicon endpoint / DiceBear monograms.

import {
  OFF_IMAGE_BASE,
  type GrocerySeed,
} from "./seed-types";

const IMG = OFF_IMAGE_BASE;

export const GERMANY_SEED: GrocerySeed = {
  categories: [
    {
      slug: "obst-gemuese",
      name: "Obst & Gemüse",
      imageUrl: `${IMG}/425/129/111/3221/front_de.52.400.jpg`,
      groupName: "Lebensmittel",
    },
    {
      slug: "milch-kaese-eier",
      name: "Milch, Käse & Eier",
      imageUrl: `${IMG}/400/195/416/1010/front_de.328.400.jpg`,
      groupName: "Lebensmittel",
    },
    {
      slug: "brot-fruehstueck",
      name: "Brot & Frühstück",
      imageUrl: `${IMG}/400/924/901/9923/front_de.121.400.jpg`,
      groupName: "Lebensmittel",
    },
    {
      slug: "nudeln-reis-konserven",
      name: "Nudeln, Reis & Konserven",
      imageUrl: `${IMG}/807/680/208/5738/front_en.3506.400.jpg`,
      groupName: "Lebensmittel",
    },
    {
      slug: "oel-essig-gewuerze",
      name: "Öl, Essig & Gewürze",
      imageUrl: `${IMG}/800/001/000/5141/front_en.66.400.jpg`,
      groupName: "Lebensmittel",
    },
    {
      slug: "tiefkuehl-fertiggerichte",
      name: "Tiefkühl & Fertiggerichte",
      imageUrl: `${IMG}/400/172/403/9143/front_de.83.400.jpg`,
      groupName: "Lebensmittel",
    },
    {
      slug: "suesswaren-snacks",
      name: "Süßwaren & Snacks",
      imageUrl: `${IMG}/400/041/770/2005/front_en.262.400.jpg`,
      groupName: "Snacks & Getränke",
    },
    {
      slug: "getraenke",
      name: "Getränke & Wasser",
      imageUrl: `${IMG}/544/900/021/4911/front_fr.335.400.jpg`,
      groupName: "Snacks & Getränke",
    },
    {
      slug: "kaffee-tee",
      name: "Kaffee & Tee",
      imageUrl: `${IMG}/400/816/710/3714/front_de.90.400.jpg`,
      groupName: "Snacks & Getränke",
    },
    {
      slug: "haushalt-reinigung",
      name: "Haushalt & Reinigung",
      imageUrl: "",
      groupName: "Haushalt",
    },
  ],

  brands: [
    { slug: "kerrygold", name: "Kerrygold", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://kerrygold.de&size=128" },
    { slug: "mueller", name: "Müller", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://muellermilch.de&size=128" },
    { slug: "danone", name: "Danone", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://danone.de&size=128" },
    { slug: "alpro", name: "Alpro", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://alpro.com&size=128" },
    { slug: "oatly", name: "Oatly", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://oatly.com&size=128" },
    { slug: "galbani", name: "Galbani", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Galbani&size=128&fontWeight=600" },
    { slug: "philadelphia", name: "Philadelphia", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Philadelphia&size=128&fontWeight=600" },
    { slug: "president", name: "Président", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=President&size=128&fontWeight=600" },
    { slug: "ehrmann", name: "Ehrmann", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://ehrmann.de&size=128" },
    { slug: "golden-toast", name: "Golden Toast", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://goldentoast.de&size=128" },
    { slug: "koelln", name: "Kölln", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://koelln.de&size=128" },
    { slug: "wasa", name: "Wasa", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://wasa.com&size=128" },
    { slug: "schaer", name: "Schär", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://schaer.com&size=128" },
    { slug: "barilla", name: "Barilla", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://barilla.com&size=128" },
    { slug: "rummo", name: "Rummo", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Rummo&size=128&fontWeight=600" },
    { slug: "mutti", name: "Mutti", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://mutti-parma.com&size=128" },
    { slug: "bonduelle", name: "Bonduelle", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://bonduelle.de&size=128" },
    { slug: "hengstenberg", name: "Hengstenberg", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://hengstenberg.de&size=128" },
    { slug: "maille", name: "Maille", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Maille&size=128&fontWeight=600" },
    { slug: "heinz", name: "Heinz", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://heinz.com&size=128" },
    { slug: "bertolli", name: "Bertolli", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Bertolli&size=128&fontWeight=600" },
    { slug: "monini", name: "Monini", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Monini&size=128&fontWeight=600" },
    { slug: "rapso", name: "Rapso", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Rapso&size=128&fontWeight=600" },
    { slug: "maggi", name: "Maggi", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://maggi.de&size=128" },
    { slug: "dr-oetker", name: "Dr. Oetker", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://oetker.de&size=128" },
    { slug: "ritter-sport", name: "Ritter Sport", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://ritter-sport.de&size=128" },
    { slug: "milka", name: "Milka", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://milka.de&size=128" },
    { slug: "lindt", name: "Lindt", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://lindt.de&size=128" },
    { slug: "haribo", name: "Haribo", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://haribo.com&size=128" },
    { slug: "katjes", name: "Katjes", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://katjes.de&size=128" },
    { slug: "bahlsen", name: "Bahlsen", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://bahlsen.de&size=128" },
    { slug: "storck", name: "Storck", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://storck.de&size=128" },
    { slug: "ferrero", name: "Ferrero", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://ferrero.de&size=128" },
    { slug: "coca-cola", name: "Coca-Cola", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://coca-cola.de&size=128" },
    { slug: "hohes-c", name: "hohes C", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=hohes%20C&size=128&fontWeight=600" },
    { slug: "gerolsteiner", name: "Gerolsteiner", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://gerolsteiner.de&size=128" },
    { slug: "red-bull", name: "Red Bull", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://redbull.com&size=128" },
    { slug: "dallmayr", name: "Dallmayr", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://dallmayr.com&size=128" },
    { slug: "jacobs", name: "Jacobs", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://jacobs.de&size=128" },
    { slug: "lavazza", name: "Lavazza", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://lavazza.com&size=128" },
    { slug: "nescafe", name: "Nescafé", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://nescafe.com&size=128" },
    { slug: "teekanne", name: "Teekanne", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://teekanne.de&size=128" },
    { slug: "seeberger", name: "Seeberger", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://seeberger.de&size=128" },
    { slug: "schwartau", name: "Schwartau", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://schwartau.de&size=128" },
    { slug: "schogetten", name: "Schogetten", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://schogetten.de&size=128" },
    { slug: "moevenpick", name: "Mövenpick", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Mövenpick&size=128&fontWeight=600" },
    { slug: "segafredo", name: "Segafredo", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://segafredo.de&size=128" },
    { slug: "messmer", name: "Meßmer", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://messmer.de&size=128" },
    { slug: "volvic", name: "Volvic", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://volvic.de&size=128" },
    { slug: "pfanner", name: "Pfanner", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://pfanner.com&size=128" },
    { slug: "balisto", name: "Balisto", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Balisto&size=128&fontWeight=600" },
    { slug: "snickers", name: "Snickers", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://snickers.com&size=128" },
    { slug: "funny-frisch", name: "funny-frisch", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://funny-frisch.de&size=128" },
    { slug: "kathi", name: "Kathi", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://kathi.de&size=128" },
    { slug: "diamant", name: "Diamant", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://diamant-zucker.de&size=128" },
  ],

  products: [
    {
      slug: "bananen",
      name: "Bananen",
      imageUrl: `${IMG}/425/129/111/3221/front_de.52.400.jpg`,
      price: 1.79,
      unitValue: 1000,
      unitType: "g",
      description:
        "Süße, samtige Bananen aus fairem Handel. Reifegrad zum Sofortverzehr.",
      stock: 120,
      categorySlugs: ["obst-gemuese"],
      isPopular: true,
    },
    {
      slug: "cherrytomaten",
      name: "Cherrystrauchtomaten",
      imageUrl: `${IMG}/000/002/024/2145/front_en.38.400.jpg`,
      price: 1.99,
      originalPrice: 2.49,
      unitValue: 500,
      unitType: "g",
      description:
        "Aromatische Cherrytomaten am Strauch, sonnengereift.",
      stock: 80,
      categorySlugs: ["obst-gemuese"],
      isPopular: true,
    },
    {
      slug: "salatgurke-bio",
      name: "Salatgurke Bio",
      imageUrl: `${IMG}/000/002/023/9756/front_ro.126.400.jpg`,
      price: 1.29,
      unitValue: 1,
      unitType: "pcs",
      description:
        "Knackige Bio-Salatgurke aus deutschem Anbau.",
      stock: 90,
      categorySlugs: ["obst-gemuese"],
    },
    {
      slug: "avocado",
      name: "Avocado",
      imageUrl: `${IMG}/433/718/560/2986/front_de.12.400.jpg`,
      price: 1.49,
      unitValue: 2,
      unitType: "pcs",
      description:
        "Cremige Hass-Avocados, genussreif in zwei bis drei Tagen.",
      stock: 60,
      categorySlugs: ["obst-gemuese"],
    },
    {
      slug: "heidelbeeren",
      name: "Heidelbeeren",
      imageUrl: `${IMG}/000/002/030/5819/front_en.56.400.jpg`,
      price: 2.49,
      originalPrice: 2.99,
      unitValue: 250,
      unitType: "g",
      description:
        "Süße Heidelbeeren, handverlesen und sofort genussfertig.",
      stock: 45,
      categorySlugs: ["obst-gemuese"],
      isPopular: true,
    },
    {
      slug: "eisbergsalat",
      name: "Eisbergsalat",
      imageUrl: `${IMG}/000/002/020/1852/front_en.27.400.jpg`,
      price: 0.99,
      unitValue: 1,
      unitType: "pcs",
      description:
        "Knackiger Eisbergsalat, gewaschen und geputzt.",
      stock: 70,
      categorySlugs: ["obst-gemuese"],
    },
    {
      slug: "aepfel-elstar",
      name: "Äpfel Elstar",
      imageUrl: "",
      price: 2.49,
      unitValue: 1000,
      unitType: "g",
      description:
        "Saftig-säuerliche Elstar-Äpfel aus deutschem Anbau.",
      stock: 100,
      categorySlugs: ["obst-gemuese"],
    },
    {
      slug: "kartoffeln-festkochend",
      name: "Kartoffeln festkochend",
      imageUrl: "",
      price: 2.29,
      unitValue: 2000,
      unitType: "g",
      description:
        "Festkochende Speisekartoffeln — ideal für Salat und Bratkartoffeln.",
      stock: 85,
      categorySlugs: ["obst-gemuese"],
    },
    {
      slug: "moehren",
      name: "Möhren",
      imageUrl: "",
      price: 1.19,
      unitValue: 1000,
      unitType: "g",
      description:
        "Süße Möhren aus regionalem Anbau, gewaschen.",
      stock: 95,
      categorySlugs: ["obst-gemuese"],
    },
    {
      slug: "zwiebeln",
      name: "Zwiebeln",
      imageUrl: "",
      price: 1.09,
      unitValue: 1000,
      unitType: "g",
      description:
        "Milde Speisezwiebeln für jeden Kochtag.",
      stock: 110,
      categorySlugs: ["obst-gemuese"],
    },
    {
      slug: "kerrygold-butter",
      name: "Kerrygold Markenbutter",
      imageUrl: `${IMG}/400/195/416/1010/front_de.328.400.jpg`,
      price: 2.79,
      originalPrice: 3.29,
      unitValue: 250,
      unitType: "g",
      description:
        "Streichzarte Butter aus irischer Weidemilch.",
      stock: 70,
      categorySlugs: ["milch-kaese-eier"],
      brandSlug: "kerrygold",
      isPopular: true,
    },
    {
      slug: "vollmilch-frisch",
      name: "Frische Vollmilch 3,5 %",
      imageUrl: `${IMG}/406/146/286/5015/front_de.30.400.jpg`,
      price: 1.19,
      unitValue: 1000,
      unitType: "ml",
      description:
        "Frische Weidemilch mit 3,5 % Fett, länger haltbar.",
      stock: 140,
      categorySlugs: ["milch-kaese-eier"],
      sizeVariants: [
        { value: 1000, price: 1.19 },
        { value: 500, price: 0.79 },
      ],
      isPopular: true,
    },
    {
      slug: "alpro-mandeldrink",
      name: "Alpro Mandeldrink Original",
      imageUrl: `${IMG}/541/118/811/0835/front_en.669.400.jpg`,
      price: 2.29,
      unitValue: 1000,
      unitType: "ml",
      description:
        "Ungesüßter Mandeldrink, von Natur aus laktosefrei.",
      stock: 65,
      categorySlugs: ["milch-kaese-eier"],
      brandSlug: "alpro",
    },
    {
      slug: "oatly-barista",
      name: "Oatly Hafer Barista Edition",
      imageUrl: `${IMG}/739/437/661/6228/front_en.197.400.jpg`,
      price: 2.49,
      unitValue: 1000,
      unitType: "ml",
      description:
        "Hafergetränk, das im Milchschaum stabil bleibt — für Espresso zu Hause.",
      stock: 60,
      categorySlugs: ["milch-kaese-eier"],
      brandSlug: "oatly",
      isPopular: true,
    },
    {
      slug: "danone-skyr",
      name: "Danone Skyr Natur",
      imageUrl: `${IMG}/303/349/145/4080/front_fr.134.400.jpg`,
      price: 1.99,
      unitValue: 480,
      unitType: "g",
      description:
        "Cremiger Skyr nach isländischer Art, fettarm und proteinreich.",
      stock: 75,
      categorySlugs: ["milch-kaese-eier"],
      brandSlug: "danone",
    },
    {
      slug: "mueller-kefir",
      name: "Müller Kefir mild",
      imageUrl: `${IMG}/402/550/018/6821/front_de.127.400.jpg`,
      price: 1.29,
      unitValue: 500,
      unitType: "ml",
      description:
        "Mild gesäuerter Kefir, gerührt und trinkfertig.",
      stock: 55,
      categorySlugs: ["milch-kaese-eier"],
      brandSlug: "mueller",
    },
    {
      slug: "galbani-mozzarella",
      name: "Galbani Mozzarella",
      imageUrl: `${IMG}/800/043/013/8719/front_en.91.400.jpg`,
      price: 0.99,
      originalPrice: 1.29,
      unitValue: 125,
      unitType: "g",
      description:
        "Klassischer Mozzarella in Lake — für Caprese und Pizza.",
      stock: 90,
      categorySlugs: ["milch-kaese-eier"],
      brandSlug: "galbani",
      isPopular: true,
    },
    {
      slug: "philadelphia-original",
      name: "Philadelphia Original",
      imageUrl: `${IMG}/762/230/044/1937/front_en.146.400.jpg`,
      price: 2.19,
      unitValue: 150,
      unitType: "g",
      description:
        "Frischkäse, streichzart und mild.",
      stock: 80,
      categorySlugs: ["milch-kaese-eier"],
      brandSlug: "philadelphia",
    },
    {
      slug: "president-emmentaler",
      name: "Président Emmentaler gerieben",
      imageUrl: `${IMG}/322/802/117/0046/front_fr.154.400.jpg`,
      price: 2.49,
      unitValue: 200,
      unitType: "g",
      description:
        "Fein geriebener Emmentaler — gratinfertig.",
      stock: 60,
      categorySlugs: ["milch-kaese-eier"],
      brandSlug: "president",
    },
    {
      slug: "ehrmann-protein",
      name: "Ehrmann High Protein Pudding",
      imageUrl: `${IMG}/400/297/124/7503/front_en.162.400.jpg`,
      price: 1.49,
      unitValue: 200,
      unitType: "g",
      description:
        "Schokoladenpudding mit 20 g Protein und ohne Zuckerzusatz.",
      stock: 70,
      categorySlugs: ["milch-kaese-eier"],
      brandSlug: "ehrmann",
    },
    {
      slug: "eier-freiland",
      name: "Freilandeier Größe M",
      imageUrl: `${IMG}/405/648/929/2494/front_en.15.400.jpg`,
      price: 3.29,
      unitValue: 10,
      unitType: "pcs",
      description:
        "Zehn Freilandeier aus regionaler Haltung, Größe M.",
      stock: 65,
      categorySlugs: ["milch-kaese-eier"],
      isPopular: true,
    },
    {
      slug: "golden-toast-vollkorn",
      name: "Golden Toast Vollkorn-Toast",
      imageUrl: `${IMG}/400/924/901/9923/front_de.121.400.jpg`,
      price: 1.79,
      unitValue: 500,
      unitType: "g",
      description:
        "Weicher Vollkorn-Toast, in Scheiben — bleibt tagelang frisch.",
      stock: 85,
      categorySlugs: ["brot-fruehstueck"],
      brandSlug: "golden-toast",
      isPopular: true,
    },
    {
      slug: "koelln-haferflocken",
      name: "Kölln Blütenzarte Haferflocken",
      imageUrl: `${IMG}/400/054/000/0108/front_de.345.400.jpg`,
      price: 1.49,
      unitValue: 500,
      unitType: "g",
      description:
        "Zarte Haferflocken für Müsli, Porridge und Gebäck.",
      stock: 95,
      categorySlugs: ["brot-fruehstueck"],
      brandSlug: "koelln",
      isPopular: true,
    },
    {
      slug: "wasa-original",
      name: "Wasa Knäckebrot Original",
      imageUrl: `${IMG}/730/040/011/8101/front_en.112.400.jpg`,
      price: 2.19,
      unitValue: 275,
      unitType: "g",
      description:
        "Knuspriges Roggen-Knäckebrot, herzhaft belegbar.",
      stock: 70,
      categorySlugs: ["brot-fruehstueck"],
      brandSlug: "wasa",
    },
    {
      slug: "schaer-landbrot",
      name: "Schär Landbrot Mehrkorn",
      imageUrl: `${IMG}/800/869/802/2214/front_de.64.400.jpg`,
      price: 3.49,
      unitValue: 250,
      unitType: "g",
      description:
        "Glutenfreies Mehrkornbrot mit Chia und Leinsamen, in Scheiben.",
      stock: 40,
      categorySlugs: ["brot-fruehstueck"],
      brandSlug: "schaer",
    },
    {
      slug: "schwartau-erdbeere",
      name: "Schwartau Erdbeere Extra",
      imageUrl: `${IMG}/401/180/084/3113/front_de.37.400.jpg`,
      price: 2.49,
      unitValue: 280,
      unitType: "g",
      description:
        "Fruchtiger Erdbeeraufstrich ohne Zuckerzusatz.",
      stock: 60,
      categorySlugs: ["brot-fruehstueck"],
      brandSlug: "schwartau",
    },
    {
      slug: "bauernbrot",
      name: "Bauernbrot Roggenmisch",
      imageUrl: "",
      price: 2.79,
      unitValue: 750,
      unitType: "g",
      description:
        "Kräftiges Roggenmischbrot mit knuspriger Kruste, täglich frisch.",
      stock: 50,
      categorySlugs: ["brot-fruehstueck"],
      isPopular: true,
    },
    {
      slug: "weizenbroetchen",
      name: "Weizenbrötchen",
      imageUrl: "",
      price: 1.8,
      unitValue: 6,
      unitType: "pcs",
      description:
        "Sechs ofenfrische Weizenbrötchen zum Aufbacken.",
      stock: 80,
      categorySlugs: ["brot-fruehstueck"],
    },
    {
      slug: "barilla-penne",
      name: "Barilla Penne Rigate",
      imageUrl: `${IMG}/807/680/208/5738/front_en.3506.400.jpg`,
      price: 1.49,
      originalPrice: 1.79,
      unitValue: 500,
      unitType: "g",
      description:
        "Bronzegezogene Penne Rigate, al dente in 11 Minuten.",
      stock: 130,
      categorySlugs: ["nudeln-reis-konserven"],
      brandSlug: "barilla",
      sizeVariants: [
        { value: 500, price: 1.49, originalPrice: 1.79 },
        { value: 1000, price: 2.69 },
      ],
      isPopular: true,
    },
    {
      slug: "barilla-spaghetti-vollkorn",
      name: "Barilla Spaghetti Vollkorn",
      imageUrl: `${IMG}/807/680/952/9419/front_fr.1666.400.jpg`,
      price: 1.79,
      unitValue: 500,
      unitType: "g",
      description:
        "Vollkorn-Spaghetti mit vollem Getreidegeschmack.",
      stock: 100,
      categorySlugs: ["nudeln-reis-konserven"],
      brandSlug: "barilla",
    },
    {
      slug: "barilla-linsen-spaghetti",
      name: "Barilla Rote Linsen Spaghetti",
      imageUrl: `${IMG}/807/680/957/7021/front_en.79.400.jpg`,
      price: 2.49,
      unitValue: 250,
      unitType: "g",
      description:
        "Spaghetti aus roten Linsen — glutenfrei und proteinreich.",
      stock: 55,
      categorySlugs: ["nudeln-reis-konserven"],
      brandSlug: "barilla",
    },
    {
      slug: "rummo-gnocchi",
      name: "Rummo Gnocchi di Patate",
      imageUrl: `${IMG}/800/834/320/1179/front_en.74.400.jpg`,
      price: 1.99,
      unitValue: 500,
      unitType: "g",
      description:
        "Kartoffel-Gnocchi, in drei Minuten gar.",
      stock: 65,
      categorySlugs: ["nudeln-reis-konserven"],
      brandSlug: "rummo",
    },
    {
      slug: "mutti-polpa",
      name: "Mutti Polpa Tomatenfruchtfleisch",
      imageUrl: `${IMG}/000/008/004/2556/front_en.449.400.jpg`,
      price: 1.29,
      unitValue: 400,
      unitType: "g",
      description:
        "Fein gehacktes Tomatenfruchtfleisch aus 100 % italienischen Tomaten.",
      stock: 120,
      categorySlugs: ["nudeln-reis-konserven"],
      brandSlug: "mutti",
      isPopular: true,
    },
    {
      slug: "bonduelle-bohnen",
      name: "Bonduelle Grüne Bohnen",
      imageUrl: `${IMG}/308/368/113/1925/front_fr.43.400.jpg`,
      price: 1.99,
      unitValue: 590,
      unitType: "g",
      description:
        "Dampfgegarte grüne Bohnen, ohne Zuckerzusatz.",
      stock: 70,
      categorySlugs: ["nudeln-reis-konserven"],
      brandSlug: "bonduelle",
    },
    {
      slug: "heinz-baked-beans",
      name: "Heinz Baked Beans",
      imageUrl: `${IMG}/500/015/702/4886/front_en.35.400.jpg`,
      price: 1.79,
      unitValue: 415,
      unitType: "g",
      description:
        "Weiße Bohnen in Tomatensauce — der Klassiker zum Frühstück.",
      stock: 60,
      categorySlugs: ["nudeln-reis-konserven"],
      brandSlug: "heinz",
    },
    {
      slug: "maille-cornichons",
      name: "Maille Cornichons Extra Fins",
      imageUrl: `${IMG}/871/256/624/6526/front_fr.142.400.jpg`,
      price: 2.79,
      unitValue: 380,
      unitType: "g",
      description:
        "Feine, knackige Cornichons in Weinessig.",
      stock: 50,
      categorySlugs: ["nudeln-reis-konserven"],
      brandSlug: "maille",
    },
    {
      slug: "hengstenberg-knax",
      name: "Hengstenberg Knax Gewürzgurken",
      imageUrl: `${IMG}/000/004/008/1410/front_de.178.400.jpg`,
      price: 2.29,
      unitValue: 670,
      unitType: "g",
      description:
        "Knackige Gewürzgurken nach Originalrezept.",
      stock: 65,
      categorySlugs: ["nudeln-reis-konserven"],
      brandSlug: "hengstenberg",
    },
    {
      slug: "kathi-weizenmehl",
      name: "Kathi Weizenmehl Type 405",
      imageUrl: `${IMG}/401/236/701/2608/front_en.28.400.jpg`,
      price: 0.89,
      unitValue: 1000,
      unitType: "g",
      description:
        "Weizenmehl Type 405 zum Backen und Binden.",
      stock: 130,
      categorySlugs: ["nudeln-reis-konserven"],
      brandSlug: "kathi",
    },
    {
      slug: "diamant-zucker",
      name: "Diamant Kristallzucker",
      imageUrl: `${IMG}/400/838/114/1004/front_de.99.400.jpg`,
      price: 2.29,
      unitValue: 2000,
      unitType: "g",
      description:
        "Feiner Kristallzucker aus deutschen Zuckerrüben.",
      stock: 120,
      categorySlugs: ["nudeln-reis-konserven"],
      brandSlug: "diamant",
    },
    {
      slug: "basmatireis",
      name: "Basmatireis",
      imageUrl: "",
      price: 2.99,
      unitValue: 1000,
      unitType: "g",
      description:
        "Langkorn-Basmatireis, locker und aromatisch.",
      stock: 90,
      categorySlugs: ["nudeln-reis-konserven"],
    },
    {
      slug: "bertolli-olivenoel",
      name: "Bertolli Olivenöl Extra Vergine",
      imageUrl: `${IMG}/800/001/000/5141/front_en.66.400.jpg`,
      price: 5.99,
      originalPrice: 6.99,
      unitValue: 500,
      unitType: "ml",
      description:
        "Kaltgepresstes Olivenöl extra vergine, fruchtig-mild.",
      stock: 60,
      categorySlugs: ["oel-essig-gewuerze"],
      brandSlug: "bertolli",
      isPopular: true,
    },
    {
      slug: "monini-olivenoel",
      name: "Monini Olivenöl Classico",
      imageUrl: `${IMG}/000/008/005/3835/front_de.84.400.jpg`,
      price: 8.99,
      unitValue: 1000,
      unitType: "ml",
      description:
        "Italienisches Olivenöl für Salat und zum Braten.",
      stock: 40,
      categorySlugs: ["oel-essig-gewuerze"],
      brandSlug: "monini",
    },
    {
      slug: "rapso-rapsoel",
      name: "Rapso Rapsöl",
      imageUrl: `${IMG}/900/146/620/7911/front_en.24.400.jpg`,
      price: 2.49,
      unitValue: 750,
      unitType: "ml",
      description:
        "Mildes Rapsöl, hitzestabil und neutral im Geschmack.",
      stock: 85,
      categorySlugs: ["oel-essig-gewuerze"],
      brandSlug: "rapso",
    },
    {
      slug: "maggi-wuerze",
      name: "Maggi Würze",
      imageUrl: `${IMG}/303/371/008/4913/front_en.257.400.jpg`,
      price: 2.79,
      unitValue: 200,
      unitType: "ml",
      description:
        "Die klassische Würze — ein paar Tropfen für Suppen und Eintöpfe.",
      stock: 75,
      categorySlugs: ["oel-essig-gewuerze"],
      brandSlug: "maggi",
    },
    {
      slug: "meersalz",
      name: "Meersalz fein",
      imageUrl: "",
      price: 0.89,
      unitValue: 500,
      unitType: "g",
      description:
        "Feines Meersalz aus natürlicher Verdunstung.",
      stock: 120,
      categorySlugs: ["oel-essig-gewuerze"],
    },
    {
      slug: "pfeffer-schwarz",
      name: "Schwarzer Pfeffer gemahlen",
      imageUrl: "",
      price: 1.49,
      unitValue: 100,
      unitType: "g",
      description:
        "Gemahlener schwarzer Pfeffer, kräftig und aromatisch.",
      stock: 90,
      categorySlugs: ["oel-essig-gewuerze"],
    },
    {
      slug: "weinessig",
      name: "Weißweinessig",
      imageUrl: `${IMG}/401/846/244/1206/front_en.5.400.jpg`,
      price: 1.39,
      unitValue: 500,
      unitType: "ml",
      description:
        "Milder Weißweinessig für Salat und Marinaden.",
      stock: 70,
      categorySlugs: ["oel-essig-gewuerze"],
    },
    {
      slug: "oetker-pizza-vegetale",
      name: "Dr. Oetker Ristorante Pizza Vegetale",
      imageUrl: `${IMG}/400/172/403/9143/front_de.83.400.jpg`,
      price: 3.29,
      originalPrice: 3.99,
      unitValue: 385,
      unitType: "g",
      description:
        "Dünner Boden, reichlich Gemüse — in 12 Minuten fertig.",
      stock: 80,
      categorySlugs: ["tiefkuehl-fertiggerichte"],
      brandSlug: "dr-oetker",
      isPopular: true,
    },
    {
      slug: "oetker-pizza-formaggi",
      name: "Dr. Oetker Pizza Quattro Formaggi",
      imageUrl: `${IMG}/400/172/403/8870/front_de.97.400.jpg`,
      price: 3.29,
      unitValue: 340,
      unitType: "g",
      description:
        "Vier Käsesorten auf knusprigem Boden.",
      stock: 75,
      categorySlugs: ["tiefkuehl-fertiggerichte"],
      brandSlug: "dr-oetker",
    },
    {
      slug: "oetker-pizza-tonno",
      name: "Dr. Oetker Ristorante Pizza Tonno",
      imageUrl: `${IMG}/400/172/403/8993/front_en.177.400.jpg`,
      price: 3.29,
      unitValue: 355,
      unitType: "g",
      description:
        "Pizza mit Thunfisch und Zwiebeln, dünn und knusprig.",
      stock: 70,
      categorySlugs: ["tiefkuehl-fertiggerichte"],
      brandSlug: "dr-oetker",
    },
    {
      slug: "snickers-ice",
      name: "Snickers Ice Cream Riegel",
      imageUrl: `${IMG}/500/015/954/1336/front_en.52.400.jpg`,
      price: 3.49,
      unitValue: 273,
      unitType: "g",
      description:
        "Sechs Eisriegel mit Erdnüssen und Karamell.",
      stock: 45,
      categorySlugs: ["tiefkuehl-fertiggerichte"],
      brandSlug: "snickers",
    },
    {
      slug: "rahmspinat",
      name: "Rahmspinat",
      imageUrl: `${IMG}/410/442/011/2162/front_en.39.400.jpg`,
      price: 1.19,
      unitValue: 450,
      unitType: "g",
      description:
        "Tiefgekühlter Rahmspinat in Portionsblöcken.",
      stock: 85,
      categorySlugs: ["tiefkuehl-fertiggerichte"],
    },
    {
      slug: "pommes-frites",
      name: "Pommes Frites Backofen",
      imageUrl: "",
      price: 2.19,
      unitValue: 1000,
      unitType: "g",
      description:
        "Vorgebackene Pommes für den Backofen, ohne Frittieren.",
      stock: 90,
      categorySlugs: ["tiefkuehl-fertiggerichte"],
    },
    {
      slug: "erbsen-tk",
      name: "Erbsen tiefgekühlt",
      imageUrl: "",
      price: 1.29,
      unitValue: 750,
      unitType: "g",
      description:
        "Junge Erbsen, kurz nach der Ernte tiefgekühlt.",
      stock: 80,
      categorySlugs: ["tiefkuehl-fertiggerichte"],
    },
    {
      slug: "ritter-sport-voll-nuss",
      name: "Ritter Sport Dunkle Voll-Nuss",
      imageUrl: `${IMG}/400/041/770/2005/front_en.262.400.jpg`,
      price: 1.49,
      unitValue: 100,
      unitType: "g",
      description:
        "Zartbitterschokolade mit ganzen Haselnüssen.",
      stock: 110,
      categorySlugs: ["suesswaren-snacks"],
      brandSlug: "ritter-sport",
      isPopular: true,
    },
    {
      slug: "milka-weisse",
      name: "Milka Weiße Schokolade",
      imageUrl: `${IMG}/402/570/000/1962/front_en.121.400.jpg`,
      price: 1.49,
      originalPrice: 1.79,
      unitValue: 100,
      unitType: "g",
      description:
        "Zart schmelzende weiße Schokolade mit Alpenmilch.",
      stock: 120,
      categorySlugs: ["suesswaren-snacks"],
      brandSlug: "milka",
      isPopular: true,
    },
    {
      slug: "lindt-edelbitter-90",
      name: "Lindt Excellence Edelbitter 90 %",
      imageUrl: `${IMG}/304/692/002/9759/front_en.544.400.jpg`,
      price: 2.29,
      unitValue: 100,
      unitType: "g",
      description:
        "Intensive Edelbitterschokolade mit 90 % Kakao.",
      stock: 70,
      categorySlugs: ["suesswaren-snacks"],
      brandSlug: "lindt",
    },
    {
      slug: "schogetten-dark",
      name: "Schogetten Dark Chocolate",
      imageUrl: `${IMG}/400/060/785/2008/front_en.96.400.jpg`,
      price: 1.29,
      unitValue: 100,
      unitType: "g",
      description:
        "Zartbitterschokolade in 18 Einzelstücken.",
      stock: 95,
      categorySlugs: ["suesswaren-snacks"],
      brandSlug: "schogetten",
    },
    {
      slug: "storck-merci",
      name: "merci Finest Selection",
      imageUrl: `${IMG}/401/440/090/1191/front_en.320.400.jpg`,
      price: 4.49,
      originalPrice: 4.99,
      unitValue: 250,
      unitType: "g",
      description:
        "Acht Schokoladenspezialitäten in Stäbchenform — die Klassiker-Mischung.",
      stock: 65,
      categorySlugs: ["suesswaren-snacks"],
      brandSlug: "storck",
      isPopular: true,
    },
    {
      slug: "werthers-original",
      name: "Werther's Original",
      imageUrl: `${IMG}/401/440/090/8930/front_en.38.400.jpg`,
      price: 2.49,
      unitValue: 245,
      unitType: "g",
      description:
        "Sahnebonbons nach Originalrezept.",
      stock: 80,
      categorySlugs: ["suesswaren-snacks"],
      brandSlug: "storck",
    },
    {
      slug: "nimm2-lachgummi",
      name: "nimm2 Lachgummi",
      imageUrl: `${IMG}/401/440/091/4818/front_en.36.400.jpg`,
      price: 1.79,
      unitValue: 200,
      unitType: "g",
      description:
        "Fruchtgummi mit Fruchtsaft und Vitaminen.",
      stock: 90,
      categorySlugs: ["suesswaren-snacks"],
      brandSlug: "storck",
    },
    {
      slug: "knoppers",
      name: "Knoppers Nussriegel",
      imageUrl: `${IMG}/000/004/014/4382/front_en.184.400.jpg`,
      price: 0.49,
      unitValue: 25,
      unitType: "g",
      description:
        "Der Pausenriegel mit Milchcreme und Nüssen.",
      stock: 200,
      categorySlugs: ["suesswaren-snacks"],
      brandSlug: "storck",
    },
    {
      slug: "haribo-goldbaeren",
      name: "Haribo Goldbären",
      imageUrl: `${IMG}/900/297/530/1558/front_en.16.400.jpg`,
      price: 1.09,
      unitValue: 100,
      unitType: "g",
      description:
        "Die Fruchtgummi-Klassiker in sechs Sorten.",
      stock: 150,
      categorySlugs: ["suesswaren-snacks"],
      brandSlug: "haribo",
      isPopular: true,
    },
    {
      slug: "katjes-wunderland",
      name: "Katjes Wunderland",
      imageUrl: `${IMG}/000/001/121/1112/front_de.7.400.jpg`,
      price: 1.49,
      unitValue: 175,
      unitType: "g",
      description:
        "Fruchtgummi ohne Gelatine, vegetarisch.",
      stock: 85,
      categorySlugs: ["suesswaren-snacks"],
      brandSlug: "katjes",
    },
    {
      slug: "leibniz-butterkeks",
      name: "Bahlsen Leibniz Butterkeks",
      imageUrl: `${IMG}/401/710/037/0007/front_de.165.400.jpg`,
      price: 1.79,
      unitValue: 200,
      unitType: "g",
      description:
        "Der Butterkeks mit 52 Zähnen — seit 1891.",
      stock: 100,
      categorySlugs: ["suesswaren-snacks"],
      brandSlug: "bahlsen",
      isPopular: true,
    },
    {
      slug: "kinder-joy",
      name: "Kinder Joy",
      imageUrl: `${IMG}/000/008/031/0891/front_en.134.400.jpg`,
      price: 0.89,
      unitValue: 20,
      unitType: "g",
      description:
        "Zwei Kammern: Milchcreme mit Waffelkugeln und eine Überraschung.",
      stock: 130,
      categorySlugs: ["suesswaren-snacks"],
      brandSlug: "ferrero",
    },
    {
      slug: "balisto-honig-mandel",
      name: "Balisto Honig-Mandel",
      imageUrl: `${IMG}/500/015/941/9291/front_fr.53.400.jpg`,
      price: 2.29,
      unitValue: 185,
      unitType: "g",
      description:
        "Müsliriegel mit Honig und Mandeln, zehn Stück.",
      stock: 75,
      categorySlugs: ["suesswaren-snacks"],
      brandSlug: "balisto",
    },
    {
      slug: "seeberger-cashew-cranberry",
      name: "Seeberger Cashew-Cranberry-Mix",
      imageUrl: `${IMG}/400/825/815/5004/front_en.77.400.jpg`,
      price: 3.49,
      unitValue: 150,
      unitType: "g",
      description:
        "Geröstete Cashewkerne mit süßen Cranberries.",
      stock: 60,
      categorySlugs: ["suesswaren-snacks"],
      brandSlug: "seeberger",
    },
    {
      slug: "funny-frisch-linsen-chips",
      name: "funny-frisch Linsen Chips Paprika",
      imageUrl: `${IMG}/400/358/610/4120/front_de.46.400.jpg`,
      price: 1.79,
      unitValue: 90,
      unitType: "g",
      description:
        "Linsenchips mit Paprika — 40 % weniger Fett als Kartoffelchips.",
      stock: 85,
      categorySlugs: ["suesswaren-snacks"],
      brandSlug: "funny-frisch",
    },
    {
      slug: "coca-cola-330",
      name: "Coca-Cola",
      imageUrl: `${IMG}/544/900/021/4911/front_fr.335.400.jpg`,
      price: 0.99,
      unitValue: 330,
      unitType: "ml",
      description:
        "Coca-Cola in der Dose, gut gekühlt am besten.",
      stock: 200,
      categorySlugs: ["getraenke"],
      brandSlug: "coca-cola",
      sizeVariants: [
        { value: 330, price: 0.99 },
        { value: 1500, price: 2.19 },
      ],
      isPopular: true,
    },
    {
      slug: "fanta-orange",
      name: "Fanta Orange",
      imageUrl: `${IMG}/544/900/000/4840/front_en.172.400.jpg`,
      price: 2.49,
      unitValue: 2000,
      unitType: "ml",
      description:
        "Fanta Orange in der 2-Liter-Flasche.",
      stock: 120,
      categorySlugs: ["getraenke"],
      brandSlug: "coca-cola",
    },
    {
      slug: "gerolsteiner-sprudel",
      name: "Gerolsteiner Sprudel Classic",
      imageUrl: `${IMG}/400/151/300/0613/front_de.57.400.jpg`,
      price: 0.85,
      unitValue: 1000,
      unitType: "ml",
      description:
        "Natürliches Mineralwasser mit kräftiger Kohlensäure.",
      stock: 180,
      categorySlugs: ["getraenke"],
      brandSlug: "gerolsteiner",
      isPopular: true,
    },
    {
      slug: "volvic-wasser",
      name: "Volvic Naturelle",
      imageUrl: `${IMG}/305/764/018/6158/front_de.79.400.jpg`,
      price: 1.19,
      unitValue: 1500,
      unitType: "ml",
      description:
        "Stilles Mineralwasser aus vulkanischem Gestein.",
      stock: 150,
      categorySlugs: ["getraenke"],
      brandSlug: "volvic",
    },
    {
      slug: "hohes-c-orange",
      name: "hohes C Orangensaft",
      imageUrl: `${IMG}/404/851/770/1818/front_de.57.400.jpg`,
      price: 2.29,
      originalPrice: 2.69,
      unitValue: 1000,
      unitType: "ml",
      description:
        "Orangensaft mit 100 % Fruchtgehalt und natürlichem Vitamin C.",
      stock: 110,
      categorySlugs: ["getraenke"],
      brandSlug: "hohes-c",
      isPopular: true,
    },
    {
      slug: "hohes-c-plus-eisen",
      name: "hohes C Plus Eisen",
      imageUrl: `${IMG}/404/851/770/2105/front_de.34.400.jpg`,
      price: 2.49,
      unitValue: 1000,
      unitType: "ml",
      description:
        "Mehrfruchtsaft mit Eisen und Vitaminen.",
      stock: 70,
      categorySlugs: ["getraenke"],
      brandSlug: "hohes-c",
    },
    {
      slug: "pfanner-orange",
      name: "Pfanner Orangensaft",
      imageUrl: `${IMG}/900/690/001/4292/front_en.43.400.jpg`,
      price: 2.49,
      unitValue: 2000,
      unitType: "ml",
      description:
        "Orangensaft in der 2-Liter-Packung, aus Fruchtsaftkonzentrat.",
      stock: 95,
      categorySlugs: ["getraenke"],
      brandSlug: "pfanner",
    },
    {
      slug: "red-bull",
      name: "Red Bull Energy Drink",
      imageUrl: `${IMG}/900/249/010/0070/front_en.245.400.jpg`,
      price: 1.39,
      unitValue: 250,
      unitType: "ml",
      description:
        "Verleiht Flügel — mit Koffein und Taurin.",
      stock: 160,
      categorySlugs: ["getraenke"],
      brandSlug: "red-bull",
      isPopular: true,
    },
    {
      slug: "apfelsaft-naturis",
      name: "Apfelsaft naturtrüb",
      imageUrl: `${IMG}/405/648/912/6669/front_fr.54.400.jpg`,
      price: 1.99,
      unitValue: 1500,
      unitType: "ml",
      description:
        "Naturtrüber Apfelsaft aus Direktsaft.",
      stock: 100,
      categorySlugs: ["getraenke"],
    },
    {
      slug: "mandarinensaft",
      name: "Mandarinensaft",
      imageUrl: `${IMG}/406/145/806/7652/front_de.33.400.jpg`,
      price: 1.79,
      unitValue: 1000,
      unitType: "ml",
      description:
        "Mandarinensaft, fruchtig-süß und ohne Zuckerzusatz.",
      stock: 65,
      categorySlugs: ["getraenke"],
    },
    {
      slug: "dallmayr-prodomo",
      name: "Dallmayr Prodomo gemahlen",
      imageUrl: `${IMG}/400/816/710/3714/front_de.90.400.jpg`,
      price: 6.99,
      originalPrice: 7.99,
      unitValue: 500,
      unitType: "g",
      description:
        "Milder Filterkaffee aus 100 % Arabica-Hochlandbohnen.",
      stock: 75,
      categorySlugs: ["kaffee-tee"],
      brandSlug: "dallmayr",
      isPopular: true,
    },
    {
      slug: "lavazza-qualita-oro",
      name: "Lavazza Qualità Oro",
      imageUrl: `${IMG}/800/007/002/0580/front_en.17.400.jpg`,
      price: 4.99,
      unitValue: 250,
      unitType: "g",
      description:
        "Kräftig-aromatischer Espresso, ganze Bohne.",
      stock: 70,
      categorySlugs: ["kaffee-tee"],
      brandSlug: "lavazza",
      isPopular: true,
    },
    {
      slug: "jacobs-bohnen",
      name: "Jacobs Kaffeebohnen Classic",
      imageUrl: `${IMG}/800/375/390/0520/front_en.49.400.jpg`,
      price: 12.99,
      originalPrice: 14.49,
      unitValue: 1000,
      unitType: "g",
      description:
        "Ganze Bohnen für Vollautomaten, ausgewogen im Geschmack.",
      stock: 55,
      categorySlugs: ["kaffee-tee"],
      brandSlug: "jacobs",
    },
    {
      slug: "moevenpick-himmlische",
      name: "Mövenpick Der Himmlische",
      imageUrl: `${IMG}/400/658/100/1777/front_de.67.400.jpg`,
      price: 7.49,
      unitValue: 500,
      unitType: "g",
      description:
        "Gemahlener Röstkaffee, fein und ausbalanciert.",
      stock: 50,
      categorySlugs: ["kaffee-tee"],
      brandSlug: "moevenpick",
    },
    {
      slug: "segafredo-intermezzo",
      name: "Segafredo Intermezzo",
      imageUrl: `${IMG}/800/341/034/4315/front_fr.42.400.jpg`,
      price: 3.99,
      unitValue: 250,
      unitType: "g",
      description:
        "Espresso-Röstung mit vollem Körper, gemahlen.",
      stock: 60,
      categorySlugs: ["kaffee-tee"],
      brandSlug: "segafredo",
    },
    {
      slug: "nescafe-dolce-gusto-latte",
      name: "Nescafé Dolce Gusto Café au Lait",
      imageUrl: `${IMG}/761/303/317/4667/front_fr.481.400.jpg`,
      price: 4.49,
      unitValue: 160,
      unitType: "g",
      description:
        "16 Kapseln Café au Lait für Dolce Gusto Maschinen.",
      stock: 80,
      categorySlugs: ["kaffee-tee"],
      brandSlug: "nescafe",
    },
    {
      slug: "teekanne-pfirsich",
      name: "Teekanne Mediterraner Pfirsich",
      imageUrl: `${IMG}/400/930/001/4164/front_de.99.400.jpg`,
      price: 1.99,
      unitValue: 20,
      unitType: "pcs",
      description:
        "20 Teebeutel Früchtetee mit Pfirsichnote, ohne Koffein.",
      stock: 90,
      categorySlugs: ["kaffee-tee"],
      brandSlug: "teekanne",
    },
    {
      slug: "messmer-earl-grey",
      name: "Meßmer Earl Grey",
      imageUrl: `${IMG}/400/125/721/8404/front_de.53.400.jpg`,
      price: 2.29,
      unitValue: 25,
      unitType: "pcs",
      description:
        "Schwarztee mit Bergamotte, 25 Teebeutel.",
      stock: 85,
      categorySlugs: ["kaffee-tee"],
      brandSlug: "messmer",
    },
    {
      slug: "messmer-pfefferminze",
      name: "Meßmer Pfefferminze",
      imageUrl: `${IMG}/400/125/715/3002/front_de.149.400.jpg`,
      price: 1.99,
      unitValue: 25,
      unitType: "pcs",
      description:
        "Pfefferminztee aus reinen Blättern, 25 Teebeutel.",
      stock: 80,
      categorySlugs: ["kaffee-tee"],
      brandSlug: "messmer",
    },
    {
      slug: "spuelmittel-zitrone",
      name: "Spülmittel Zitrone",
      imageUrl: "",
      price: 1.29,
      unitValue: 500,
      unitType: "ml",
      description:
        "Fettlösendes Handgeschirrspülmittel mit Zitrusduft.",
      stock: 100,
      categorySlugs: ["haushalt-reinigung"],
    },
    {
      slug: "allzweckreiniger",
      name: "Allzweckreiniger",
      imageUrl: "",
      price: 1.79,
      unitValue: 1000,
      unitType: "ml",
      description:
        "Universalreiniger für alle abwaschbaren Oberflächen.",
      stock: 90,
      categorySlugs: ["haushalt-reinigung"],
    },
    {
      slug: "toilettenpapier",
      name: "Toilettenpapier 3-lagig",
      imageUrl: "",
      price: 3.99,
      originalPrice: 4.49,
      unitValue: 10,
      unitType: "pcs",
      description:
        "Zehn Rollen dreilagiges Toilettenpapier, je 150 Blatt.",
      stock: 120,
      categorySlugs: ["haushalt-reinigung"],
      isPopular: true,
    },
    {
      slug: "kuechenrolle",
      name: "Küchenrolle",
      imageUrl: "",
      price: 2.49,
      unitValue: 4,
      unitType: "pcs",
      description:
        "Vier saugstarke Küchenrollen, zweilagig.",
      stock: 110,
      categorySlugs: ["haushalt-reinigung"],
    },
    {
      slug: "muellbeutel",
      name: "Müllbeutel 60 l",
      imageUrl: "",
      price: 2.29,
      unitValue: 20,
      unitType: "pcs",
      description:
        "20 reißfeste Müllbeutel mit Zugband.",
      stock: 95,
      categorySlugs: ["haushalt-reinigung"],
    },
    {
      slug: "vollwaschmittel",
      name: "Vollwaschmittel Pulver",
      imageUrl: "",
      price: 11.99,
      originalPrice: 13.99,
      unitValue: 3600,
      unitType: "g",
      description:
        "Vollwaschmittel für 60 Waschgänge, ab 20 °C wirksam.",
      stock: 60,
      categorySlugs: ["haushalt-reinigung"],
      isPopular: true,
    },
    {
      slug: "geschirrspueltabs",
      name: "Geschirrspültabs All-in-One",
      imageUrl: "",
      price: 14.99,
      unitValue: 100,
      unitType: "pcs",
      description:
        "100 Tabs mit Klarspüler- und Salzfunktion.",
      stock: 70,
      categorySlugs: ["haushalt-reinigung"],
    },
    {
      slug: "zahnpasta",
      name: "Zahnpasta Complete",
      imageUrl: "",
      price: 1.99,
      unitValue: 75,
      unitType: "ml",
      description:
        "Zahncreme mit Fluorid für täglichen Kariesschutz.",
      stock: 105,
      categorySlugs: ["haushalt-reinigung"],
    },
  ],

  coupons: [
    {
      code: "WILLKOMMEN10",
      type: "percent",
      value: 10,
      scope: "store",
      minOrderValue: 20,
      maxDiscount: 5,
      usageLimit: 500,
      perUserLimit: 1,
    },
    {
      code: "FRISCHE5",
      type: "percent",
      value: 5,
      scope: "category",
      targetCategorySlugs: ["obst-gemuese"],
      minOrderValue: 10,
      maxDiscount: 3,
      usageLimit: 300,
      perUserLimit: 2,
    },
    {
      code: "KAFFEE15",
      type: "percent",
      value: 15,
      scope: "category",
      targetCategorySlugs: ["kaffee-tee"],
      minOrderValue: 15,
      maxDiscount: 5,
      usageLimit: 200,
      perUserLimit: 1,
    },
    {
      code: "SUESS2",
      type: "flat",
      value: 2,
      scope: "category",
      targetCategorySlugs: ["suesswaren-snacks"],
      minOrderValue: 12,
      maxDiscount: 2,
      usageLimit: 250,
      perUserLimit: 2,
    },
    {
      code: "HAUSHALT3",
      type: "flat",
      value: 3,
      scope: "category",
      targetCategorySlugs: ["haushalt-reinigung"],
      minOrderValue: 25,
      maxDiscount: 3,
      usageLimit: 150,
      perUserLimit: 1,
    },
    {
      code: "PIZZA1",
      type: "flat",
      value: 1,
      scope: "product",
      targetProductSlugs: ["oetker-pizza-vegetale", "oetker-pizza-formaggi", "oetker-pizza-tonno"],
      minOrderValue: 6,
      maxDiscount: 1,
      usageLimit: 400,
      perUserLimit: 3,
    },
    {
      code: "GRATISVERSAND",
      type: "flat",
      value: 4,
      scope: "store",
      minOrderValue: 40,
      maxDiscount: 4,
      usageLimit: 400,
      perUserLimit: 1,
    },
  ],

  banners: [
    {
      title: "Frisch aus der Region",
      subtitle: "Obst & Gemüse jeden Morgen geliefert",
      imageUrl:
        "https://images.unsplash.com/photo-1542838132-92c53300491e?w=1200&q=80",
      targetCategorySlug: "obst-gemuese",
      sortOrder: 0,
      backgroundColor: "#1F6F4A",
    },
    {
      title: "Kaffeegenuss zu Hause",
      subtitle: "Bohnen und Kapseln bis 15 % günstiger",
      imageUrl:
        "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=1200&q=80",
      targetCategorySlug: "kaffee-tee",
      sortOrder: 1,
      backgroundColor: "#4A2C1A",
    },
    {
      title: "Süße Pause",
      subtitle: "Schokolade und Gummibärchen im Angebot",
      imageUrl:
        "https://images.unsplash.com/photo-1481391319762-47dff72954d9?w=1200&q=80",
      targetCategorySlug: "suesswaren-snacks",
      sortOrder: 2,
      backgroundColor: "#7A1F3D",
    },
    {
      title: "Vorratskammer füllen",
      subtitle: "Nudeln, Reis und Konserven im Vorteilspack",
      imageUrl:
        "https://images.unsplash.com/photo-1556909212-d5b604d0c90d?w=1200&q=80",
      targetCategorySlug: "nudeln-reis-konserven",
      sortOrder: 3,
      backgroundColor: "#2A4C7A",
    },
  ],
};
