// The "Generate sample data" catalog — a realistic Indian quick-commerce
// grocery store (Zepto/Instamart-style groups, real brands, ₹ MRP pricing).
//
// Product images are real branded product photos served from Open Food Facts
// (images.openfoodfacts.org) — © Open Food Facts contributors, CC-BY-SA 4.0,
// https://world.openfoodfacts.org. The generate dialog shows this attribution.
// Every URL here was taken from a live OFF API result and is re-verified by
// scripts/verify-seed-images.mjs; re-run it whenever this file changes. A few
// products the catalog wants but OFF has no usable photo for (e.g. Vim bar)
// carry imageUrl "" — every consumer renders a placeholder.
//
// Slugs are the cross-reference keys: real Firestore ids are minted at write
// time by the seeder (seed-grocery.ts), which maps slugs → new doc ids.

import type { CouponScope, CouponType, UnitType } from "@/lib/types";

export type SeedCategory = {
  slug: string;
  name: string;
  imageUrl: string;
  groupName: string;
};

export type SeedBrand = {
  slug: string;
  name: string;
  // "" throughout v1 — OFF hosts product photos, not brand logos, and logo
  // files elsewhere are trademark-encumbered. Consumers placeholder-fall-back.
  logoUrl: string;
};

export type SeedSizeVariant = {
  value: number;
  price: number;
  // Absent = no per-size discount (originalPrice equals price).
  originalPrice?: number;
};

export type SeedProduct = {
  slug: string;
  name: string;
  imageUrl: string;
  price: number;
  // Absent = not discounted.
  originalPrice?: number;
  unitValue: number;
  unitType: UnitType;
  description: string;
  stock: number;
  prepTime?: string;
  categorySlugs: string[];
  // Absent = unbranded ("").
  brandSlug?: string;
  sizeVariants?: SeedSizeVariant[];
  isPopular?: boolean;
};

// Always seeded evergreen (validFrom/validUntil "") and active; the target
// slug list used is the one matching `scope`.
export type SeedCoupon = {
  code: string;
  type: CouponType;
  value: number;
  scope: CouponScope;
  targetCategorySlugs?: string[];
  targetProductSlugs?: string[];
  minOrderValue: number;
  maxDiscount: number;
  usageLimit: number;
  perUserLimit: number;
};

export type SeedBanner = {
  title: string;
  subtitle: string;
  imageUrl: string;
  // At most one of these; neither = a display-only banner.
  targetCategorySlug?: string;
  targetProductSlug?: string;
  sortOrder: number;
  backgroundColor: string;
};

export type GrocerySeed = {
  categories: SeedCategory[];
  brands: SeedBrand[];
  products: SeedProduct[];
  coupons: SeedCoupon[];
  banners: SeedBanner[];
};

const IMG = "https://images.openfoodfacts.org/images/products";

export const GROCERY_SEED: GrocerySeed = {
  categories: [
    {
      slug: "fruits-vegetables",
      name: "Fruits & Vegetables",
      imageUrl: `${IMG}/000/010/164/6267/front_en.12.400.jpg`,
      groupName: "Grocery & Kitchen",
    },
    {
      slug: "dairy-bread-eggs",
      name: "Dairy, Bread & Eggs",
      imageUrl: `${IMG}/890/126/226/0121/front_en.52.400.jpg`,
      groupName: "Grocery & Kitchen",
    },
    {
      slug: "atta-rice-dal",
      name: "Atta, Rice & Dal",
      imageUrl: `${IMG}/890/172/515/0105/front_en.18.400.jpg`,
      groupName: "Grocery & Kitchen",
    },
    {
      slug: "oil-ghee-masala",
      name: "Oil, Ghee & Masala",
      imageUrl: `${IMG}/890/600/728/0242/front_en.18.400.jpg`,
      groupName: "Grocery & Kitchen",
    },
    {
      slug: "instant-sauces",
      name: "Instant Food & Sauces",
      imageUrl: `${IMG}/890/105/802/3787/front_en.6.400.jpg`,
      groupName: "Grocery & Kitchen",
    },
    {
      slug: "snacks-biscuits",
      name: "Snacks & Biscuits",
      imageUrl: `${IMG}/890/149/150/3020/front_en.35.400.jpg`,
      groupName: "Snacks & Drinks",
    },
    {
      slug: "cold-drinks-juices",
      name: "Cold Drinks & Juices",
      imageUrl: `${IMG}/890/188/800/5410/front_en.23.400.jpg`,
      groupName: "Snacks & Drinks",
    },
    {
      slug: "tea-coffee",
      name: "Tea, Coffee & Health Drinks",
      imageUrl: `${IMG}/890/105/201/0615/front_en.18.400.jpg`,
      groupName: "Snacks & Drinks",
    },
    {
      slug: "chocolates-sweets",
      name: "Chocolates & Sweets",
      imageUrl: `${IMG}/762/220/227/2639/front_en.3.400.jpg`,
      groupName: "Snacks & Drinks",
    },
    {
      slug: "cleaning-household",
      name: "Cleaning & Household",
      imageUrl: `${IMG}/890/139/615/3306/front_en.5.400.jpg`,
      groupName: "Household Essentials",
    },
  ],

  brands: [
    { slug: "amul", name: "Amul", logoUrl: "" },
    { slug: "mother-dairy", name: "Mother Dairy", logoUrl: "" },
    { slug: "britannia", name: "Britannia", logoUrl: "" },
    { slug: "parle", name: "Parle", logoUrl: "" },
    { slug: "maggi", name: "Maggi", logoUrl: "" },
    { slug: "nescafe", name: "Nescafé", logoUrl: "" },
    { slug: "tata-sampann", name: "Tata Sampann", logoUrl: "" },
    { slug: "tata-tea", name: "Tata Tea", logoUrl: "" },
    { slug: "aashirvaad", name: "Aashirvaad", logoUrl: "" },
    { slug: "fortune", name: "Fortune", logoUrl: "" },
    { slug: "saffola", name: "Saffola", logoUrl: "" },
    { slug: "haldirams", name: "Haldiram's", logoUrl: "" },
    { slug: "lays", name: "Lay's", logoUrl: "" },
    { slug: "bingo", name: "Bingo!", logoUrl: "" },
    { slug: "sunfeast", name: "Sunfeast", logoUrl: "" },
    { slug: "cadbury", name: "Cadbury", logoUrl: "" },
    { slug: "coca-cola", name: "Coca-Cola", logoUrl: "" },
    { slug: "real", name: "Real", logoUrl: "" },
    { slug: "dabur", name: "Dabur", logoUrl: "" },
    { slug: "kissan", name: "Kissan", logoUrl: "" },
    { slug: "everest", name: "Everest", logoUrl: "" },
    { slug: "mdh", name: "MDH", logoUrl: "" },
    { slug: "india-gate", name: "India Gate", logoUrl: "" },
    { slug: "daawat", name: "Daawat", logoUrl: "" },
    { slug: "kelloggs", name: "Kellogg's", logoUrl: "" },
    { slug: "red-label", name: "Red Label", logoUrl: "" },
    { slug: "bru", name: "Bru", logoUrl: "" },
    { slug: "dettol", name: "Dettol", logoUrl: "" },
    { slug: "harpic", name: "Harpic", logoUrl: "" },
    { slug: "colgate", name: "Colgate", logoUrl: "" },
    { slug: "vim", name: "Vim", logoUrl: "" },
    { slug: "surf-excel", name: "Surf Excel", logoUrl: "" },
  ],

  products: [
    // ── Fruits & Vegetables ────────────────────────────────────────────
    {
      slug: "onion-500g",
      name: "Onion",
      imageUrl: `${IMG}/890/497/058/8504/front_en.3.400.jpg`,
      price: 22,
      unitValue: 500,
      unitType: "g",
      description:
        "Fresh, firm onions — the base of every Indian gravy. Handpicked and packed the same day.",
      stock: 120,
      categorySlugs: ["fruits-vegetables"],
    },
    {
      slug: "carrot-500g",
      name: "Carrot (Gajar)",
      imageUrl: `${IMG}/000/010/164/6267/front_en.12.400.jpg`,
      price: 38,
      unitValue: 500,
      unitType: "g",
      description:
        "Crunchy red carrots, great for salads, sabzi and gajar ka halwa.",
      stock: 80,
      categorySlugs: ["fruits-vegetables"],
    },
    {
      slug: "spinach-250g",
      name: "Spinach (Palak)",
      imageUrl: `${IMG}/000/010/148/1695/front_en.3.400.jpg`,
      price: 22,
      unitValue: 250,
      unitType: "g",
      description:
        "Tender green palak leaves, washed and bunched. Perfect for palak paneer and dal.",
      stock: 60,
      categorySlugs: ["fruits-vegetables"],
    },
    {
      slug: "french-beans-250g",
      name: "French Beans",
      imageUrl: `${IMG}/000/059/000/1282/front_en.3.400.jpg`,
      price: 32,
      unitValue: 250,
      unitType: "g",
      description: "Crisp, stringless French beans — stir-fry or steam.",
      stock: 45,
      categorySlugs: ["fruits-vegetables"],
    },
    {
      slug: "mushroom-200g",
      name: "Button Mushroom",
      imageUrl: `${IMG}/400/841/732/3008/front_en.6.400.jpg`,
      price: 55,
      unitValue: 200,
      unitType: "g",
      description:
        "Farm-fresh button mushrooms in a sealed punnet. Clean, white and ready to cook.",
      stock: 0,
      categorySlugs: ["fruits-vegetables"],
    },
    {
      slug: "cowpea-beans-250g",
      name: "Cowpea Beans (Lobia)",
      imageUrl: `${IMG}/890/429/370/5074/front_en.3.400.jpg`,
      price: 28,
      unitValue: 250,
      unitType: "g",
      description: "Fresh green lobia pods, tender and quick-cooking.",
      stock: 35,
      categorySlugs: ["fruits-vegetables"],
    },
    {
      slug: "mango-banganpalli-1kg",
      name: "Mango Banganpalli",
      imageUrl: `${IMG}/890/429/370/4770/front_en.3.400.jpg`,
      price: 129,
      originalPrice: 149,
      unitValue: 1000,
      unitType: "g",
      description:
        "Golden Banganpalli mangoes from Andhra — fibreless, honey-sweet flesh.",
      stock: 50,
      categorySlugs: ["fruits-vegetables"],
      isPopular: true,
    },
    {
      slug: "orange-nagpur-1kg",
      name: "Orange Nagpur",
      imageUrl: `${IMG}/890/437/765/2288/front_en.3.400.jpg`,
      price: 89,
      unitValue: 1000,
      unitType: "g",
      description:
        "Juicy Nagpur santra with that signature sweet-tangy punch.",
      stock: 70,
      categorySlugs: ["fruits-vegetables"],
    },
    {
      slug: "papaya-red-lady",
      name: "Papaya Red Lady",
      imageUrl: `${IMG}/000/059/999/0534/front_en.3.400.jpg`,
      price: 65,
      unitValue: 1,
      unitType: "pcs",
      description:
        "One whole Red Lady papaya, ripened naturally — deep orange and sweet.",
      stock: 40,
      categorySlugs: ["fruits-vegetables"],
    },
    {
      slug: "lemon-4pcs",
      name: "Lemon (Nimbu)",
      imageUrl: `${IMG}/000/010/223/9128/front_en.3.400.jpg`,
      price: 20,
      unitValue: 4,
      unitType: "pcs",
      description: "Thin-skinned, juicy lemons — 4 per pack.",
      stock: 90,
      categorySlugs: ["fruits-vegetables"],
    },

    // ── Dairy, Bread & Eggs ────────────────────────────────────────────
    {
      slug: "amul-butter-100g",
      name: "Amul Butter",
      imageUrl: `${IMG}/890/126/201/0016/front_en.53.400.jpg`,
      price: 62,
      unitValue: 100,
      unitType: "g",
      description:
        "The utterly butterly classic — pasteurised table butter that makes everything better.",
      stock: 85,
      categorySlugs: ["dairy-bread-eggs"],
      brandSlug: "amul",
      sizeVariants: [
        { value: 100, price: 62 },
        { value: 500, price: 305, originalPrice: 315 },
      ],
      isPopular: true,
    },
    {
      slug: "amul-taaza-500ml",
      name: "Amul Taaza Toned Milk",
      imageUrl: `${IMG}/890/126/226/0121/front_en.52.400.jpg`,
      price: 29,
      unitValue: 500,
      unitType: "ml",
      description:
        "Homogenised toned milk — the everyday pouch for chai, coffee and cereal.",
      stock: 200,
      categorySlugs: ["dairy-bread-eggs"],
      brandSlug: "amul",
      isPopular: true,
    },
    {
      slug: "amul-gold-500ml",
      name: "Amul Gold Full Cream Milk",
      imageUrl: `${IMG}/890/126/226/0107/front_en.3.400.jpg`,
      price: 34,
      unitValue: 500,
      unitType: "ml",
      description: "Rich full-cream milk with 6% fat — for thicker chai and creamier kheer.",
      stock: 150,
      categorySlugs: ["dairy-bread-eggs"],
      brandSlug: "amul",
    },
    {
      slug: "amul-malai-paneer-200g",
      name: "Amul Malai Paneer",
      imageUrl: `${IMG}/890/126/218/0115/front_en.6.400.jpg`,
      price: 95,
      unitValue: 200,
      unitType: "g",
      description:
        "Soft, fresh malai paneer that holds its shape in the pan — matar paneer ready.",
      stock: 55,
      categorySlugs: ["dairy-bread-eggs"],
      brandSlug: "amul",
    },
    {
      slug: "amul-fresh-cream-250ml",
      name: "Amul Fresh Cream",
      imageUrl: `${IMG}/890/126/215/1863/front_en.6.400.jpg`,
      price: 85,
      unitValue: 250,
      unitType: "ml",
      description: "25% fat fresh cream for gravies, desserts and whipping.",
      stock: 48,
      categorySlugs: ["dairy-bread-eggs"],
      brandSlug: "amul",
    },
    {
      slug: "amul-cheese-slices-200g",
      name: "Amul Cheese Slices",
      imageUrl: `${IMG}/890/126/202/0244/front_en.3.400.jpg`,
      price: 145,
      unitValue: 200,
      unitType: "g",
      description:
        "Processed cheese slices that melt evenly — sandwich and burger essential.",
      stock: 65,
      categorySlugs: ["dairy-bread-eggs"],
      brandSlug: "amul",
    },
    {
      slug: "amul-lassi-250ml",
      name: "Amul Lassi",
      imageUrl: `${IMG}/890/126/215/1696/front_en.43.400.jpg`,
      price: 25,
      unitValue: 250,
      unitType: "ml",
      description: "Sweetened cultured lassi, chilled and ready to drink.",
      stock: 75,
      categorySlugs: ["dairy-bread-eggs"],
      brandSlug: "amul",
    },
    {
      slug: "mother-dairy-dahi-1kg",
      name: "Mother Dairy Classic Dahi",
      imageUrl: `${IMG}/890/164/802/2169/front_en.15.400.jpg`,
      price: 115,
      originalPrice: 125,
      unitValue: 1000,
      unitType: "g",
      description:
        "Thick, set curd with a clean, mild tang — the family-size tub.",
      stock: 60,
      categorySlugs: ["dairy-bread-eggs"],
      brandSlug: "mother-dairy",
    },
    {
      slug: "mother-dairy-chach-270ml",
      name: "Mother Dairy Tadka Chach",
      imageUrl: `${IMG}/890/164/800/2444/front_en.3.400.jpg`,
      price: 15,
      unitValue: 270,
      unitType: "ml",
      description:
        "Probiotic spiced buttermilk with a jeera-hing tadka — summer in a cup.",
      stock: 90,
      categorySlugs: ["dairy-bread-eggs"],
      brandSlug: "mother-dairy",
    },
    {
      slug: "mother-dairy-cow-milk-500ml",
      name: "Mother Dairy Cow Milk",
      imageUrl: `${IMG}/890/164/892/0120/front_en.3.400.jpg`,
      price: 29,
      unitValue: 500,
      unitType: "ml",
      description: "Pure cow milk pouch, pasteurised and chilled.",
      stock: 140,
      categorySlugs: ["dairy-bread-eggs"],
      brandSlug: "mother-dairy",
    },
    {
      slug: "britannia-brown-bread",
      name: "Britannia 100% Whole Wheat Bread",
      imageUrl: `${IMG}/890/106/333/8593/front_en.3.400.jpg`,
      price: 55,
      unitValue: 1,
      unitType: "pcs",
      description:
        "Soft whole-wheat brown bread with zero maida — toast it, stuff it, roll it.",
      stock: 40,
      categorySlugs: ["dairy-bread-eggs"],
      brandSlug: "britannia",
    },

    // ── Atta, Rice & Dal ───────────────────────────────────────────────
    {
      slug: "aashirvaad-atta-5kg",
      name: "Aashirvaad Shudh Chakki Atta",
      imageUrl: `${IMG}/890/172/515/0105/front_en.18.400.jpg`,
      price: 289,
      originalPrice: 315,
      unitValue: 5000,
      unitType: "g",
      description:
        "100% whole wheat atta, chakki-ground from four-step-selected grain for soft rotis.",
      stock: 75,
      categorySlugs: ["atta-rice-dal"],
      brandSlug: "aashirvaad",
      sizeVariants: [
        { value: 1000, price: 72 },
        { value: 5000, price: 289, originalPrice: 315 },
      ],
      isPopular: true,
    },
    {
      slug: "aashirvaad-select-atta-5kg",
      name: "Aashirvaad Select Sharbati Atta",
      imageUrl: `${IMG}/890/172/512/1228/front_en.17.400.jpg`,
      price: 395,
      unitValue: 5000,
      unitType: "g",
      description:
        "Premium Sharbati wheat from MP — noticeably softer, sweeter rotis.",
      stock: 40,
      categorySlugs: ["atta-rice-dal"],
      brandSlug: "aashirvaad",
    },
    {
      slug: "tata-sampann-toor-dal-1kg",
      name: "Tata Sampann Unpolished Toor Dal",
      imageUrl: `${IMG}/890/404/392/6216/front_en.5.400.jpg`,
      price: 189,
      originalPrice: 210,
      unitValue: 1000,
      unitType: "g",
      description:
        "Unpolished arhar dal with no artificial shine — protein-rich and quick to cook.",
      stock: 95,
      categorySlugs: ["atta-rice-dal"],
      brandSlug: "tata-sampann",
      sizeVariants: [
        { value: 500, price: 98 },
        { value: 1000, price: 189, originalPrice: 210 },
      ],
      isPopular: true,
    },
    {
      slug: "tata-sampann-moong-dal-1kg",
      name: "Tata Sampann Unpolished Moong Dal",
      imageUrl: `${IMG}/890/404/392/6315/front_en.23.400.jpg`,
      price: 165,
      unitValue: 1000,
      unitType: "g",
      description: "Light, easily digested yellow moong dal — khichdi's best friend.",
      stock: 80,
      categorySlugs: ["atta-rice-dal"],
      brandSlug: "tata-sampann",
    },
    {
      slug: "tata-sampann-chana-dal-500g",
      name: "Tata Sampann Unpolished Chana Dal",
      imageUrl: `${IMG}/890/404/392/6629/front_en.5.400.jpg`,
      price: 75,
      unitValue: 500,
      unitType: "g",
      description: "Nutty, unpolished chana dal for dal fry, sundal and besan at home.",
      stock: 70,
      categorySlugs: ["atta-rice-dal"],
      brandSlug: "tata-sampann",
    },
    {
      slug: "tata-sampann-besan-500g",
      name: "Tata Sampann Fine Besan",
      imageUrl: `${IMG}/890/404/392/6728/front_en.3.400.jpg`,
      price: 68,
      unitValue: 500,
      unitType: "g",
      description:
        "Fine gram flour milled from 100% chana dal — pakoras, kadhi, cheela.",
      stock: 60,
      categorySlugs: ["atta-rice-dal"],
      brandSlug: "tata-sampann",
    },
    {
      slug: "tata-sampann-poha-1kg",
      name: "Tata Sampann Poha",
      imageUrl: `${IMG}/890/404/390/2326/front_en.3.400.jpg`,
      price: 80,
      unitValue: 1000,
      unitType: "g",
      description: "Thick flaked rice that stays fluffy — breakfast poha in minutes.",
      stock: 55,
      categorySlugs: ["atta-rice-dal"],
      brandSlug: "tata-sampann",
    },
    {
      slug: "tata-sampann-kala-chana-500g",
      name: "Tata Sampann Kala Chana",
      imageUrl: `${IMG}/890/404/392/6308/front_en.3.400.jpg`,
      price: 58,
      unitValue: 500,
      unitType: "g",
      description: "Whole black chana, protein-packed for chole and sprouts.",
      stock: 65,
      categorySlugs: ["atta-rice-dal"],
      brandSlug: "tata-sampann",
    },
    {
      slug: "india-gate-basmati-1kg",
      name: "India Gate Aged Basmati Rice",
      imageUrl: `${IMG}/069/022/530/1244/front_en.9.400.jpg`,
      price: 195,
      unitValue: 1000,
      unitType: "g",
      description:
        "Aged long-grain basmati that cooks up separate and fragrant — biryani grade.",
      stock: 85,
      categorySlugs: ["atta-rice-dal"],
      brandSlug: "india-gate",
    },
    {
      slug: "daawat-rozana-basmati-1kg",
      name: "Daawat Rozana Super Basmati Rice",
      imageUrl: `${IMG}/890/153/700/7123/front_en.11.400.jpg`,
      price: 128,
      originalPrice: 140,
      unitValue: 1000,
      unitType: "g",
      description: "Everyday basmati at an everyday price — pulao to plain rice.",
      stock: 100,
      categorySlugs: ["atta-rice-dal"],
      brandSlug: "daawat",
    },
    {
      slug: "fortune-rawa-500g",
      name: "Fortune Rawa (Semolina)",
      imageUrl: `${IMG}/890/600/881/1223/front_en.3.400.jpg`,
      price: 42,
      unitValue: 500,
      unitType: "g",
      description: "Fine sooji for upma, rava dosa and sheera.",
      stock: 50,
      categorySlugs: ["atta-rice-dal"],
      brandSlug: "fortune",
    },

    // ── Oil, Ghee & Masala ─────────────────────────────────────────────
    {
      slug: "fortune-sunflower-oil-1l",
      name: "Fortune Sunlite Refined Sunflower Oil",
      imageUrl: `${IMG}/890/600/728/0242/front_en.18.400.jpg`,
      price: 145,
      originalPrice: 165,
      unitValue: 1000,
      unitType: "ml",
      description:
        "Light, refined sunflower oil for everyday frying and tadka.",
      stock: 110,
      categorySlugs: ["oil-ghee-masala"],
      brandSlug: "fortune",
      sizeVariants: [
        { value: 1000, price: 145, originalPrice: 165 },
        { value: 5000, price: 699, originalPrice: 750 },
      ],
      isPopular: true,
    },
    {
      slug: "fortune-mustard-oil-500ml",
      name: "Fortune Kachi Ghani Mustard Oil",
      imageUrl: `${IMG}/890/600/728/0945/front_en.12.400.jpg`,
      price: 75,
      unitValue: 500,
      unitType: "ml",
      description:
        "Cold-pressed kachi ghani mustard oil with that pungent kick — pickles and Bengali cooking.",
      stock: 70,
      categorySlugs: ["oil-ghee-masala"],
      brandSlug: "fortune",
    },
    {
      slug: "saffola-gold-1l",
      name: "Saffola Gold Blended Oil",
      imageUrl: `${IMG}/890/108/801/7381/front_en.8.400.jpg`,
      price: 185,
      originalPrice: 205,
      unitValue: 1000,
      unitType: "ml",
      description:
        "Heart-friendly rice bran + sunflower oil blend with balanced fatty acids.",
      stock: 90,
      categorySlugs: ["oil-ghee-masala"],
      brandSlug: "saffola",
      sizeVariants: [
        { value: 1000, price: 185, originalPrice: 205 },
        { value: 5000, price: 899 },
      ],
    },
    {
      slug: "amul-ghee-1l",
      name: "Amul Pure Ghee",
      imageUrl: `${IMG}/890/126/203/0151/front_fr.9.400.jpg`,
      price: 615,
      unitValue: 1000,
      unitType: "ml",
      description:
        "Granular, aromatic cow's-milk ghee made the traditional way.",
      stock: 45,
      categorySlugs: ["oil-ghee-masala"],
      brandSlug: "amul",
      sizeVariants: [
        { value: 500, price: 330 },
        { value: 1000, price: 615 },
      ],
    },
    {
      slug: "mother-dairy-ghee-1l",
      name: "Mother Dairy Pure Ghee",
      imageUrl: `${IMG}/890/164/809/4746/front_en.4.400.jpg`,
      price: 599,
      unitValue: 1000,
      unitType: "ml",
      description: "Rich, danedar cow ghee for rotis, dal and sweets.",
      stock: 0,
      categorySlugs: ["oil-ghee-masala"],
      brandSlug: "mother-dairy",
    },
    {
      slug: "aashirvaad-svasti-ghee-200ml",
      name: "Aashirvaad Svasti Pure Cow Ghee",
      imageUrl: `${IMG}/890/172/510/0339/front_en.9.400.jpg`,
      price: 145,
      unitValue: 200,
      unitType: "ml",
      description: "Slow-cooked pure cow ghee in a handy try-me pack.",
      stock: 55,
      categorySlugs: ["oil-ghee-masala"],
      brandSlug: "aashirvaad",
    },
    {
      slug: "everest-garam-masala-50g",
      name: "Everest Garam Masala",
      imageUrl: `${IMG}/890/178/610/0507/front_en.4.400.jpg`,
      price: 45,
      unitValue: 50,
      unitType: "g",
      description:
        "The finishing blend — a pinch lifts any curry with warm, roasted spice.",
      stock: 95,
      categorySlugs: ["oil-ghee-masala"],
      brandSlug: "everest",
    },
    {
      slug: "everest-chaat-masala-50g",
      name: "Everest Chaat Masala",
      imageUrl: `${IMG}/890/178/606/0504/front_en.15.400.jpg`,
      price: 38,
      unitValue: 50,
      unitType: "g",
      description:
        "Tangy amchur-black salt magic — sprinkle on fruit, salads and everything fried.",
      stock: 85,
      categorySlugs: ["oil-ghee-masala"],
      brandSlug: "everest",
    },
    {
      slug: "everest-kitchen-king-50g",
      name: "Everest Kitchen King Masala",
      imageUrl: `${IMG}/890/178/612/0505/front_en.12.400.jpg`,
      price: 42,
      unitValue: 50,
      unitType: "g",
      description: "The all-rounder blend for restaurant-style sabzi gravies.",
      stock: 75,
      categorySlugs: ["oil-ghee-masala"],
      brandSlug: "everest",
    },
    {
      slug: "everest-kashmiri-mirch-100g",
      name: "Everest Kashmirilal Red Chilli Powder",
      imageUrl: `${IMG}/890/178/641/1009/front_en.15.400.jpg`,
      price: 85,
      unitValue: 100,
      unitType: "g",
      description:
        "Brilliant red Kashmiri chilli — deep colour, gentle heat.",
      stock: 65,
      categorySlugs: ["oil-ghee-masala"],
      brandSlug: "everest",
    },
    {
      slug: "mdh-kasoori-methi-100g",
      name: "MDH Kasoori Methi",
      imageUrl: `${IMG}/890/216/700/0188/front_en.13.400.jpg`,
      price: 52,
      unitValue: 100,
      unitType: "g",
      description:
        "Sun-dried fenugreek leaves — crush over butter chicken and dal makhani.",
      stock: 60,
      categorySlugs: ["oil-ghee-masala"],
      brandSlug: "mdh",
    },
    {
      slug: "aashirvaad-salt-1kg",
      name: "Aashirvaad Iodised Salt",
      imageUrl: `${IMG}/890/172/512/3123/front_en.13.400.jpg`,
      price: 28,
      unitValue: 1000,
      unitType: "g",
      description: "Free-flowing iodised crystal salt, vacuum evaporated.",
      stock: 150,
      categorySlugs: ["oil-ghee-masala"],
      brandSlug: "aashirvaad",
    },

    // ── Instant Food & Sauces ──────────────────────────────────────────
    {
      slug: "maggi-masala-140g",
      name: "Maggi 2-Minute Masala Noodles",
      imageUrl: `${IMG}/890/105/802/3787/front_en.6.400.jpg`,
      price: 28,
      unitValue: 140,
      unitType: "g",
      description:
        "The double pack of India's favourite 2-minute noodles with the classic masala tastemaker.",
      stock: 180,
      categorySlugs: ["instant-sauces"],
      brandSlug: "maggi",
      isPopular: true,
    },
    {
      slug: "maggi-masala-70g",
      name: "Maggi 2-Minute Masala Noodles (Single)",
      imageUrl: `${IMG}/890/105/801/7687/front_en.13.400.jpg`,
      price: 14,
      unitValue: 70,
      unitType: "g",
      description: "The single-serve classic — midnight snack, sorted.",
      stock: 250,
      categorySlugs: ["instant-sauces"],
      brandSlug: "maggi",
    },
    {
      slug: "yippee-noodles-72g",
      name: "Sunfeast Yippee! Magic Masala Noodles",
      imageUrl: `${IMG}/890/908/100/5251/front_en.16.400.jpg`,
      price: 15,
      unitValue: 72,
      unitType: "g",
      description:
        "Long, non-sticky noodle strands with a veggie-flecked masala mix.",
      stock: 140,
      categorySlugs: ["instant-sauces"],
      brandSlug: "sunfeast",
    },
    {
      slug: "saffola-oats-classic-38g",
      name: "Saffola Masala Oats — Classic Masala",
      imageUrl: `${IMG}/890/108/806/8734/front_en.19.400.jpg`,
      price: 15,
      unitValue: 38,
      unitType: "g",
      description: "Savoury single-serve oats ready in 3 minutes.",
      stock: 100,
      categorySlugs: ["instant-sauces"],
      brandSlug: "saffola",
      prepTime: "3 min",
    },
    {
      slug: "saffola-oats-tomato-38g",
      name: "Saffola Masala Oats — Peppy Tomato",
      imageUrl: `${IMG}/890/108/806/8741/front_en.24.400.jpg`,
      price: 15,
      unitValue: 38,
      unitType: "g",
      description: "Tangy tomato masala oats — a lighter chatpata fix.",
      stock: 95,
      categorySlugs: ["instant-sauces"],
      brandSlug: "saffola",
      prepTime: "3 min",
    },
    {
      slug: "saffola-oats-1kg",
      name: "Saffola Oats",
      imageUrl: `${IMG}/890/108/821/3608/front_en.3.400.jpg`,
      price: 199,
      originalPrice: 220,
      unitValue: 1000,
      unitType: "g",
      description:
        "100% natural wholegrain oats — creamy in minutes, great for masala oats too.",
      stock: 60,
      categorySlugs: ["instant-sauces"],
      brandSlug: "saffola",
    },
    {
      slug: "kelloggs-corn-flakes-250g",
      name: "Kellogg's Corn Flakes Original",
      imageUrl: `${IMG}/890/149/900/8183/front_en.14.400.jpg`,
      price: 99,
      unitValue: 250,
      unitType: "g",
      description: "The golden breakfast classic — crisp flakes of sun-ripened corn.",
      stock: 70,
      categorySlugs: ["instant-sauces"],
      brandSlug: "kelloggs",
    },
    {
      slug: "kelloggs-chocos-385g",
      name: "Kellogg's Chocos",
      imageUrl: `${IMG}/890/149/901/0728/front_en.14.400.jpg`,
      price: 185,
      unitValue: 385,
      unitType: "g",
      description:
        "Wheat shells coated in real chocolate — the kids' breakfast negotiation-ender.",
      stock: 55,
      categorySlugs: ["instant-sauces"],
      brandSlug: "kelloggs",
    },
    {
      slug: "kissan-ketchup-850g",
      name: "Kissan Fresh Tomato Ketchup",
      imageUrl: `${IMG}/890/103/090/2932/front_en.5.400.jpg`,
      price: 145,
      originalPrice: 160,
      unitValue: 850,
      unitType: "g",
      description:
        "Made from 100% real tomatoes — the samosa's constant companion.",
      stock: 80,
      categorySlugs: ["instant-sauces"],
      brandSlug: "kissan",
    },
    {
      slug: "kissan-mixed-fruit-jam-200g",
      name: "Kissan Mixed Fruit Jam",
      imageUrl: `${IMG}/890/103/083/1690/front_en.32.400.jpg`,
      price: 85,
      unitValue: 200,
      unitType: "g",
      description: "Thick mixed-fruit jam bursting with real fruit pulp.",
      stock: 65,
      categorySlugs: ["instant-sauces"],
      brandSlug: "kissan",
    },
    {
      slug: "dabur-honey-500g",
      name: "Dabur Honey",
      imageUrl: `${IMG}/890/120/702/5372/front_en.21.400.jpg`,
      price: 199,
      originalPrice: 225,
      unitValue: 500,
      unitType: "g",
      description:
        "100% pure honey with no added sugar — NMR tested.",
      stock: 70,
      categorySlugs: ["instant-sauces"],
      brandSlug: "dabur",
    },

    // ── Snacks & Biscuits ──────────────────────────────────────────────
    {
      slug: "parle-g-250g",
      name: "Parle-G Glucose Biscuits",
      imageUrl: `${IMG}/890/171/912/3870/front_en.27.400.jpg`,
      price: 25,
      unitValue: 250,
      unitType: "g",
      description:
        "The world's largest-selling biscuit — genius with a cup of chai.",
      stock: 200,
      categorySlugs: ["snacks-biscuits"],
      brandSlug: "parle",
      isPopular: true,
    },
    {
      slug: "parle-hide-seek-120g",
      name: "Parle Hide & Seek Chocolate Chip",
      imageUrl: `${IMG}/890/171/910/5913/front_en.22.400.jpg`,
      price: 30,
      unitValue: 120,
      unitType: "g",
      description: "Buttery cookies loaded with choco chips.",
      stock: 90,
      categorySlugs: ["snacks-biscuits"],
      brandSlug: "parle",
    },
    {
      slug: "parle-krackjack-57g",
      name: "Parle KrackJack",
      imageUrl: `${IMG}/890/171/913/5248/front_en.25.400.jpg`,
      price: 10,
      unitValue: 57,
      unitType: "g",
      description: "The original sweet-and-salty crackle.",
      stock: 150,
      categorySlugs: ["snacks-biscuits"],
      brandSlug: "parle",
    },
    {
      slug: "parle-monaco-63g",
      name: "Parle Monaco Classic",
      imageUrl: `${IMG}/890/171/913/5118/front_en.24.400.jpg`,
      price: 10,
      unitValue: 63,
      unitType: "g",
      description: "Light, flaky salted crackers — top them or dunk them.",
      stock: 130,
      categorySlugs: ["snacks-biscuits"],
      brandSlug: "parle",
    },
    {
      slug: "britannia-bourbon-100g",
      name: "Britannia Bourbon",
      imageUrl: `${IMG}/890/106/313/9336/front_en.3.400.jpg`,
      price: 30,
      unitValue: 100,
      unitType: "g",
      description:
        "Chocolate cream sandwiched in chocolate biscuits, topped with sugar crystals.",
      stock: 110,
      categorySlugs: ["snacks-biscuits"],
      brandSlug: "britannia",
    },
    {
      slug: "britannia-good-day-cashew-200g",
      name: "Britannia Good Day Cashew Cookies",
      imageUrl: `${IMG}/890/106/309/3287/front_en.18.400.jpg`,
      price: 58,
      unitValue: 200,
      unitType: "g",
      description: "Buttery cookies studded with real cashew bits.",
      stock: 85,
      categorySlugs: ["snacks-biscuits"],
      brandSlug: "britannia",
    },
    {
      slug: "britannia-marie-gold-250g",
      name: "Britannia Marie Gold",
      imageUrl: `${IMG}/890/106/302/3901/front_en.6.400.jpg`,
      price: 35,
      unitValue: 250,
      unitType: "g",
      description: "The light, crisp tea-time staple since forever.",
      stock: 120,
      categorySlugs: ["snacks-biscuits"],
      brandSlug: "britannia",
    },
    {
      slug: "britannia-milk-bikis-100g",
      name: "Britannia Milk Bikis",
      imageUrl: `${IMG}/890/106/301/2868/front_en.5.400.jpg`,
      price: 25,
      unitValue: 100,
      unitType: "g",
      description: "Milk-rich biscuits kids grow up on.",
      stock: 100,
      categorySlugs: ["snacks-biscuits"],
      brandSlug: "britannia",
    },
    {
      slug: "lays-classic-salted-50g",
      name: "Lay's Classic Salted Potato Chips",
      imageUrl: `${IMG}/890/149/110/1844/front_en.32.400.jpg`,
      price: 20,
      unitValue: 50,
      unitType: "g",
      description: "Thin-cut potato chips with just the right salt.",
      stock: 160,
      categorySlugs: ["snacks-biscuits"],
      brandSlug: "lays",
    },
    {
      slug: "lays-magic-masala-48g",
      name: "Lay's India's Magic Masala",
      imageUrl: `${IMG}/890/149/150/3020/front_en.35.400.jpg`,
      price: 20,
      unitValue: 48,
      unitType: "g",
      description:
        "The spicy, tangy masala that made blue packs famous.",
      stock: 170,
      categorySlugs: ["snacks-biscuits"],
      brandSlug: "lays",
      isPopular: true,
    },
    {
      slug: "lays-cream-onion-55g",
      name: "Lay's American Style Cream & Onion",
      imageUrl: `${IMG}/890/149/110/1813/front_en.40.400.jpg`,
      price: 20,
      unitValue: 55,
      unitType: "g",
      description: "Cool cream and zesty onion on a crisp chip.",
      stock: 150,
      categorySlugs: ["snacks-biscuits"],
      brandSlug: "lays",
    },
    {
      slug: "bingo-mad-angles-66g",
      name: "Bingo! Mad Angles Tomato Madness",
      imageUrl: `${IMG}/890/172/501/3769/front_en.4.400.jpg`,
      price: 20,
      unitValue: 66,
      unitType: "g",
      description: "Triangle chips with a tangy tomato hit — dangerously moreish.",
      stock: 120,
      categorySlugs: ["snacks-biscuits"],
      brandSlug: "bingo",
    },
    {
      slug: "bingo-tedhe-medhe-75g",
      name: "Bingo! Tedhe Medhe",
      imageUrl: `${IMG}/890/172/511/8921/front_en.7.400.jpg`,
      price: 20,
      unitValue: 75,
      unitType: "g",
      description: "Twisted, masala-dusted sticks that don't know when to stop.",
      stock: 130,
      categorySlugs: ["snacks-biscuits"],
      brandSlug: "bingo",
    },
    {
      slug: "haldirams-aloo-bhujia-200g",
      name: "Haldiram's Aloo Bhujia",
      imageUrl: `${IMG}/890/400/440/0731/front_en.4.400.jpg`,
      price: 52,
      unitValue: 200,
      unitType: "g",
      description:
        "The legendary crisp potato sev from Bikaner — chai's crunchiest partner.",
      stock: 95,
      categorySlugs: ["snacks-biscuits"],
      brandSlug: "haldirams",
      isPopular: true,
    },
    {
      slug: "haldirams-moong-dal-400g",
      name: "Haldiram's Moong Dal",
      imageUrl: `${IMG}/890/400/440/3800/front_en.17.400.jpg`,
      price: 98,
      unitValue: 400,
      unitType: "g",
      description: "Crunchy salted fried moong dal — the classic namkeen.",
      stock: 0,
      categorySlugs: ["snacks-biscuits"],
      brandSlug: "haldirams",
    },

    // ── Cold Drinks & Juices ───────────────────────────────────────────
    {
      slug: "sprite-750ml",
      name: "Sprite Lime Flavoured Soft Drink",
      imageUrl: `${IMG}/890/176/403/2271/front_en.50.400.jpg`,
      price: 40,
      unitValue: 750,
      unitType: "ml",
      description: "Clear lemon-lime fizz — thand rakh, clarity for the win.",
      stock: 140,
      categorySlugs: ["cold-drinks-juices"],
      brandSlug: "coca-cola",
      isPopular: true,
    },
    {
      slug: "sprite-250ml",
      name: "Sprite (Mini)",
      imageUrl: `${IMG}/890/176/403/2912/front_en.26.400.jpg`,
      price: 20,
      unitValue: 250,
      unitType: "ml",
      description: "The grab-and-go mini bottle.",
      stock: 180,
      categorySlugs: ["cold-drinks-juices"],
      brandSlug: "coca-cola",
    },
    {
      slug: "thums-up-1l",
      name: "Thums Up",
      imageUrl: `${IMG}/890/176/404/2904/front_en.6.400.jpg`,
      price: 65,
      unitValue: 1000,
      unitType: "ml",
      description: "Strong, fizzy cola with the taste of thunder.",
      stock: 110,
      categorySlugs: ["cold-drinks-juices"],
      brandSlug: "coca-cola",
    },
    {
      slug: "frooti-300ml",
      name: "Frooti Mango Drink",
      imageUrl: `${IMG}/890/257/910/3057/front_en.34.400.jpg`,
      price: 20,
      unitValue: 300,
      unitType: "ml",
      description: "Fresh 'n' juicy mango — the OG green pack.",
      stock: 160,
      categorySlugs: ["cold-drinks-juices"],
      brandSlug: "parle",
    },
    {
      slug: "appy-fizz-250ml",
      name: "Appy Fizz Sparkling Apple Drink",
      imageUrl: `${IMG}/890/257/900/2442/front_en.3.400.jpg`,
      price: 25,
      unitValue: 250,
      unitType: "ml",
      description: "Crisp sparkling apple drink in the iconic champagne-style bottle.",
      stock: 120,
      categorySlugs: ["cold-drinks-juices"],
      brandSlug: "parle",
    },
    {
      slug: "real-mixed-fruit-1l",
      name: "Real Fruit Power Mixed Fruit Juice",
      imageUrl: `${IMG}/890/188/800/5410/front_en.23.400.jpg`,
      price: 130,
      originalPrice: 140,
      unitValue: 1000,
      unitType: "ml",
      description: "Nine-fruit blend with no added preservatives.",
      stock: 85,
      categorySlugs: ["cold-drinks-juices"],
      brandSlug: "real",
      isPopular: true,
    },
    {
      slug: "real-orange-1l",
      name: "Real Activ 100% Orange Juice",
      imageUrl: `${IMG}/890/188/800/5397/front_en.31.400.jpg`,
      price: 135,
      unitValue: 1000,
      unitType: "ml",
      description: "100% orange juice with no added sugar.",
      stock: 75,
      categorySlugs: ["cold-drinks-juices"],
      brandSlug: "real",
    },
    {
      slug: "real-activ-coconut-water-1l",
      name: "Real Activ 100% Tender Coconut Water",
      imageUrl: `${IMG}/890/120/703/7795/front_en.3.400.jpg`,
      price: 185,
      unitValue: 1000,
      unitType: "ml",
      description:
        "Naturally isotonic tender coconut water — nothing added, nothing removed.",
      stock: 60,
      categorySlugs: ["cold-drinks-juices"],
      brandSlug: "real",
    },
    {
      slug: "amul-kool-kesar-180ml",
      name: "Amul Kool Kesar Milk",
      imageUrl: `${IMG}/890/126/215/2211/front_en.43.400.jpg`,
      price: 25,
      unitValue: 180,
      unitType: "ml",
      description: "Chilled kesar-flavoured milk in a handy bottle.",
      stock: 90,
      categorySlugs: ["cold-drinks-juices"],
      brandSlug: "amul",
    },

    // ── Tea, Coffee & Health Drinks ────────────────────────────────────
    {
      slug: "tata-tea-premium-1kg",
      name: "Tata Tea Premium",
      imageUrl: `${IMG}/890/105/201/0615/front_en.18.400.jpg`,
      price: 560,
      originalPrice: 590,
      unitValue: 1000,
      unitType: "g",
      description:
        "The classic strong Assam blend crores of homes wake up to.",
      stock: 70,
      categorySlugs: ["tea-coffee"],
      brandSlug: "tata-tea",
      sizeVariants: [
        { value: 250, price: 145 },
        { value: 1000, price: 560, originalPrice: 590 },
      ],
      isPopular: true,
    },
    {
      slug: "tata-tea-gold-care-500g",
      name: "Tata Tea Gold Care",
      imageUrl: `${IMG}/890/105/200/5161/front_en.5.400.jpg`,
      price: 310,
      unitValue: 500,
      unitType: "g",
      description:
        "Gold blend with 5 natural ingredients — tulsi, ginger, cardamom warmth.",
      stock: 55,
      categorySlugs: ["tea-coffee"],
      brandSlug: "tata-tea",
    },
    {
      slug: "red-label-tea-100g",
      name: "Brooke Bond Red Label Tea",
      imageUrl: `${IMG}/890/103/087/7179/front_en.3.400.jpg`,
      price: 60,
      unitValue: 100,
      unitType: "g",
      description: "Strong, refreshing CTC chai that brings people together.",
      stock: 100,
      categorySlugs: ["tea-coffee"],
      brandSlug: "red-label",
    },
    {
      slug: "nescafe-classic-45g",
      name: "Nescafé Classic Instant Coffee",
      imageUrl: `${IMG}/000/008/900/9949/front_en.4.400.jpg`,
      price: 185,
      unitValue: 45,
      unitType: "g",
      description:
        "100% pure instant coffee with that signature Nescafé aroma.",
      stock: 80,
      categorySlugs: ["tea-coffee"],
      brandSlug: "nescafe",
      isPopular: true,
    },
    {
      slug: "bru-instant-50g",
      name: "Bru Instant Coffee",
      imageUrl: `${IMG}/890/103/053/5895/front_en.3.400.jpg`,
      price: 140,
      unitValue: 50,
      unitType: "g",
      description:
        "Coffee-chicory blend for that strong South-style filter kick, instantly.",
      stock: 75,
      categorySlugs: ["tea-coffee"],
      brandSlug: "bru",
    },
    {
      slug: "bru-gold-100g",
      name: "Bru Gold Freeze-Dried Coffee",
      imageUrl: `${IMG}/890/103/037/3930/front_en.3.400.jpg`,
      price: 325,
      unitValue: 100,
      unitType: "g",
      description: "100% pure freeze-dried granules for a smoother black cup.",
      stock: 0,
      categorySlugs: ["tea-coffee"],
      brandSlug: "bru",
    },
    {
      slug: "bournvita-500g",
      name: "Cadbury Bournvita",
      imageUrl: `${IMG}/000/000/914/1209/front_en.18.400.jpg`,
      price: 235,
      originalPrice: 250,
      unitValue: 500,
      unitType: "g",
      description:
        "Chocolate malt drink with vitamins and minerals — tayyari jeet ki.",
      stock: 65,
      categorySlugs: ["tea-coffee"],
      brandSlug: "cadbury",
    },

    // ── Chocolates & Sweets ────────────────────────────────────────────
    {
      slug: "dairy-milk-21g",
      name: "Cadbury Dairy Milk",
      imageUrl: `${IMG}/762/220/227/2639/front_en.3.400.jpg`,
      price: 20,
      unitValue: 21,
      unitType: "g",
      description: "The classic creamy milk chocolate — kuch meetha ho jaaye.",
      stock: 200,
      categorySlugs: ["chocolates-sweets"],
      brandSlug: "cadbury",
      isPopular: true,
    },
    {
      slug: "dairy-milk-11g",
      name: "Cadbury Dairy Milk (Mini)",
      imageUrl: `${IMG}/762/220/233/4009/front_en.9.400.jpg`,
      price: 10,
      unitValue: 11,
      unitType: "g",
      description: "The ₹10 pocket-money classic.",
      stock: 250,
      categorySlugs: ["chocolates-sweets"],
      brandSlug: "cadbury",
    },
    {
      slug: "five-star-18g",
      name: "Cadbury 5 Star",
      imageUrl: `${IMG}/762/220/231/8078/front_en.14.400.jpg`,
      price: 10,
      unitValue: 18,
      unitType: "g",
      description: "Chewy caramel and nougat dipped in chocolate — lose yourself.",
      stock: 220,
      categorySlugs: ["chocolates-sweets"],
      brandSlug: "cadbury",
    },
    {
      slug: "gems-18g",
      name: "Cadbury Gems",
      imageUrl: `${IMG}/762/220/221/6695/front_en.3.400.jpg`,
      price: 10,
      unitValue: 18,
      unitType: "g",
      description: "Rainbow-shelled chocolate buttons.",
      stock: 180,
      categorySlugs: ["chocolates-sweets"],
      brandSlug: "cadbury",
    },
    {
      slug: "bournville-75g",
      name: "Cadbury Bournville Intense 70% Dark",
      imageUrl: `${IMG}/762/220/232/5960/front_en.11.400.jpg`,
      price: 120,
      unitValue: 75,
      unitType: "g",
      description: "Intense 70% cocoa dark chocolate — you have to earn it.",
      stock: 60,
      categorySlugs: ["chocolates-sweets"],
      brandSlug: "cadbury",
    },
    {
      slug: "oreo-original-120g",
      name: "Cadbury Oreo Original",
      imageUrl: `${IMG}/762/220/222/5512/front_en.16.400.jpg`,
      price: 30,
      unitValue: 120,
      unitType: "g",
      description: "Twist, lick, dunk — the chocolatey sandwich cookie.",
      stock: 110,
      categorySlugs: ["chocolates-sweets", "snacks-biscuits"],
      brandSlug: "cadbury",
    },
    {
      slug: "amul-dark-chocolate-150g",
      name: "Amul Dark Chocolate",
      imageUrl: `${IMG}/890/126/207/0676/front_en.44.400.jpg`,
      price: 110,
      unitValue: 150,
      unitType: "g",
      description: "55% rich cocoa dark chocolate at an honest price.",
      stock: 70,
      categorySlugs: ["chocolates-sweets"],
      brandSlug: "amul",
    },
    {
      slug: "amul-fruit-n-nut-150g",
      name: "Amul Fruit 'N' Nut Dark Chocolate",
      imageUrl: `${IMG}/890/126/207/0539/front_en.21.400.jpg`,
      price: 135,
      unitValue: 150,
      unitType: "g",
      description: "Dark chocolate loaded with raisins and roasted almonds.",
      stock: 55,
      categorySlugs: ["chocolates-sweets"],
      brandSlug: "amul",
    },
    {
      slug: "amul-chocominis-250g",
      name: "Amul Chocominis",
      imageUrl: `${IMG}/890/126/207/0546/front_en.24.400.jpg`,
      price: 199,
      unitValue: 250,
      unitType: "g",
      description: "A pouch of bite-size chocolates to keep the jar full.",
      stock: 45,
      categorySlugs: ["chocolates-sweets"],
      brandSlug: "amul",
    },

    // ── Cleaning & Household ───────────────────────────────────────────
    {
      slug: "dettol-soap-75g",
      name: "Dettol Original Bathing Soap",
      imageUrl: `${IMG}/000/005/015/8980/front_en.3.400.jpg`,
      price: 40,
      unitValue: 75,
      unitType: "g",
      description: "Trusted germ protection in the classic pine fragrance.",
      stock: 130,
      categorySlugs: ["cleaning-household"],
      brandSlug: "dettol",
    },
    {
      slug: "dettol-handwash-200ml",
      name: "Dettol Original Liquid Handwash",
      imageUrl: `${IMG}/890/139/632/4508/front_en.5.400.jpg`,
      price: 99,
      unitValue: 200,
      unitType: "ml",
      description: "pH-balanced germ-protection handwash pump.",
      stock: 90,
      categorySlugs: ["cleaning-household"],
      brandSlug: "dettol",
    },
    {
      slug: "harpic-lemon-500ml",
      name: "Harpic Power Plus Lemon Toilet Cleaner",
      imageUrl: `${IMG}/890/139/615/3306/front_en.5.400.jpg`,
      price: 98,
      originalPrice: 108,
      unitValue: 500,
      unitType: "ml",
      description: "10× better stain removal with a fresh lemon burst.",
      stock: 85,
      categorySlugs: ["cleaning-household"],
      brandSlug: "harpic",
    },
    {
      slug: "harpic-gel-750ml",
      name: "Harpic Active Cleaning Gel",
      imageUrl: `${IMG}/600/110/622/4936/front_en.5.400.jpg`,
      price: 185,
      unitValue: 750,
      unitType: "ml",
      description: "Thick clinging gel for an all-round sparkling clean.",
      stock: 60,
      categorySlugs: ["cleaning-household"],
      brandSlug: "harpic",
    },
    {
      slug: "colgate-maxfresh-450g",
      name: "Colgate MaxFresh Spicy Fresh",
      imageUrl: `${IMG}/890/131/454/3653/front_en.6.400.jpg`,
      price: 240,
      originalPrice: 260,
      unitValue: 450,
      unitType: "g",
      description: "Cooling crystals for a blast of freshness — family value pack.",
      stock: 75,
      categorySlugs: ["cleaning-household"],
      brandSlug: "colgate",
    },
    {
      slug: "colgate-visible-white-200g",
      name: "Colgate Visible White",
      imageUrl: `${IMG}/890/131/407/8216/front_en.3.400.jpg`,
      price: 135,
      unitValue: 200,
      unitType: "g",
      description: "Whitening toothpaste — visibly whiter teeth in one week.",
      stock: 65,
      categorySlugs: ["cleaning-household"],
      brandSlug: "colgate",
    },
    {
      // No usable OFF photo — exercises the placeholder path deliberately.
      slug: "vim-bar-200g",
      name: "Vim Dishwash Bar",
      imageUrl: "",
      price: 20,
      unitValue: 200,
      unitType: "g",
      description: "Lemon-power grease cutter for sparkling utensils.",
      stock: 140,
      categorySlugs: ["cleaning-household"],
      brandSlug: "vim",
    },
    {
      // No usable OFF photo — exercises the placeholder path deliberately.
      slug: "surf-excel-easy-wash-1kg",
      name: "Surf Excel Easy Wash Detergent Powder",
      imageUrl: "",
      price: 120,
      originalPrice: 135,
      unitValue: 1000,
      unitType: "g",
      description:
        "Superfine powder that dissolves fast and lifts tough stains — daag achhe hain.",
      stock: 95,
      categorySlugs: ["cleaning-household"],
      brandSlug: "surf-excel",
    },
  ],

  coupons: [
    {
      code: "WELCOME10",
      type: "percent",
      value: 10,
      scope: "store",
      minOrderValue: 199,
      maxDiscount: 80,
      usageLimit: 0,
      perUserLimit: 1,
    },
    {
      code: "FLAT50",
      type: "flat",
      value: 50,
      scope: "store",
      minOrderValue: 499,
      maxDiscount: 0,
      usageLimit: 0,
      perUserLimit: 3,
    },
    {
      code: "FRESH15",
      type: "percent",
      value: 15,
      scope: "category",
      targetCategorySlugs: ["fruits-vegetables"],
      minOrderValue: 149,
      maxDiscount: 60,
      usageLimit: 0,
      perUserLimit: 2,
    },
    {
      code: "SNACKS20",
      type: "percent",
      value: 20,
      scope: "category",
      targetCategorySlugs: ["snacks-biscuits"],
      minOrderValue: 249,
      maxDiscount: 100,
      usageLimit: 0,
      perUserLimit: 2,
    },
    {
      code: "AMULLOVE",
      type: "percent",
      value: 12,
      scope: "product",
      targetProductSlugs: [
        "amul-butter-100g",
        "amul-taaza-500ml",
        "amul-cheese-slices-200g",
      ],
      minOrderValue: 0,
      maxDiscount: 50,
      usageLimit: 0,
      perUserLimit: 1,
    },
    {
      code: "CHAI10",
      type: "percent",
      value: 10,
      scope: "category",
      targetCategorySlugs: ["tea-coffee"],
      minOrderValue: 199,
      maxDiscount: 40,
      usageLimit: 0,
      perUserLimit: 3,
    },
  ],

  banners: [
    {
      title: "Fresh picks, daily",
      subtitle: "Farm-fresh fruit & veg, delivered in minutes",
      imageUrl: `${IMG}/890/429/370/4770/front_en.3.400.jpg`,
      targetCategorySlug: "fruits-vegetables",
      sortOrder: 0,
      backgroundColor: "#E7F2EC",
    },
    {
      title: "Snack o'clock",
      subtitle: "Chips, biscuits & bhujia for every craving",
      imageUrl: `${IMG}/890/400/440/0731/front_en.4.400.jpg`,
      targetCategorySlug: "snacks-biscuits",
      sortOrder: 1,
      backgroundColor: "#FDF1E3",
    },
    {
      title: "Chai time essentials",
      subtitle: "Teas, coffees & the biscuits to dunk in them",
      imageUrl: `${IMG}/890/105/201/0615/front_en.18.400.jpg`,
      targetCategorySlug: "tea-coffee",
      sortOrder: 2,
      backgroundColor: "#F3EAE3",
    },
    {
      title: "Pantry staples, stocked",
      subtitle: "Atta, dal, oil & masala — the weekly list, sorted",
      imageUrl: `${IMG}/890/172/515/0105/front_en.18.400.jpg`,
      sortOrder: 3,
      backgroundColor: "#EAF0F7",
    },
  ],
};
