// The **Italy** sample catalog — a realistic Italian supermarket
// (Esselunga/Coop-style aisles, real Italian brands, € retail pricing),
// seeded in Italian because catalog content is single-valued (see
// docs/explanation/content-i18n-plan.md).
//
// Prices are Spanish shelf prices, NOT converted from another market. The
// storefront's price filter uses per-currency bands (2/5/10 for euros — see
// cordelia's ProductPriceFilter), and a catalog that leaves a band empty makes
// that chip unmatchable; npm run verify:seed-bands enforces the spread.
//
// Image sources (every URL is verified live by scripts/verify-seed-images.mjs
// — re-run it whenever this file changes):
// - Products: real Italian product photos from Open Food Facts
//   (images.openfoodfacts.org) — © Open Food Facts contributors, CC-BY-SA
//   4.0. Barcodes were harvested from OFF's Italian catalogue and every path
//   re-resolved through its product endpoint, because the search index returns
//   unpadded paths and stale revisions for short codes. Loose produce and the
//   whole Casa aisle carry imageUrl "" — OFF is a packaged-*food* database —
//   and every consumer renders a placeholder.
// - Banners: landscape photography from Unsplash.
// - Brand logos: Google's favicon endpoint / DiceBear monograms.

import {
  OFF_IMAGE_BASE,
  type GrocerySeed,
} from "./seed-types";

const IMG = OFF_IMAGE_BASE;

export const ITALY_SEED: GrocerySeed = {
  categories: [
    {
      slug: "frutta-verdura",
      name: "Frutta e Verdura",
      imageUrl: "",
      groupName: "Alimentari",
    },
    {
      slug: "latticini-uova",
      name: "Latticini e Uova",
      imageUrl: `${IMG}/800/043/013/8719/front_en.91.400.jpg`,
      groupName: "Alimentari",
    },
    {
      slug: "pane-colazione",
      name: "Pane e Colazione",
      imageUrl: `${IMG}/807/680/950/4751/front_it.172.400.jpg`,
      groupName: "Alimentari",
    },
    {
      slug: "pasta-riso-scatolame",
      name: "Pasta, Riso e Scatolame",
      imageUrl: `${IMG}/807/680/019/5057/front_en.3809.400.jpg`,
      groupName: "Alimentari",
    },
    {
      slug: "olio-condimenti",
      name: "Olio e Condimenti",
      imageUrl: `${IMG}/000/008/005/3835/front_de.84.400.jpg`,
      groupName: "Alimentari",
    },
    {
      slug: "surgelati-salumi",
      name: "Surgelati e Salumi",
      imageUrl: `${IMG}/805/701/822/1035/front_it.4.400.jpg`,
      groupName: "Alimentari",
    },
    {
      slug: "dolci-snack",
      name: "Dolci e Snack",
      imageUrl: `${IMG}/800/030/032/4655/front_it.36.400.jpg`,
      groupName: "Snack e Bevande",
    },
    {
      slug: "bevande",
      name: "Bevande e Acque",
      imageUrl: `${IMG}/800/227/001/4901/front_en.304.400.jpg`,
      groupName: "Snack e Bevande",
    },
    {
      slug: "caffe-te",
      name: "Caffè e Tè",
      imageUrl: `${IMG}/800/375/390/0438/front_en.11.400.jpg`,
      groupName: "Snack e Bevande",
    },
    {
      slug: "casa-pulizia",
      name: "Casa e Pulizia",
      imageUrl: "",
      groupName: "Casa",
    },
  ],

  brands: [
    { slug: "arborea", name: "Arborea", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Arborea&size=128&fontWeight=600" },
    { slug: "granarolo", name: "Granarolo", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://granarolo.it&size=128" },
    { slug: "parmalat", name: "Parmalat", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://parmalat.it&size=128" },
    { slug: "galbani", name: "Galbani", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://galbani.it&size=128" },
    { slug: "latteria-soresina", name: "Latteria Soresina", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Latteria%20Soresina&size=128&fontWeight=600" },
    { slug: "parmareggio", name: "Parmareggio", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Parmareggio&size=128&fontWeight=600" },
    { slug: "philadelphia", name: "Philadelphia", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Philadelphia&size=128&fontWeight=600" },
    { slug: "danone", name: "Danone", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://danone.it&size=128" },
    { slug: "vitasnella", name: "Vitasnella", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Vitasnella&size=128&fontWeight=600" },
    { slug: "via-verde-bio", name: "Via Verde Bio", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Via%20Verde%20Bio&size=128&fontWeight=600" },
    { slug: "mulino-bianco", name: "Mulino Bianco", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://mulinobianco.it&size=128" },
    { slug: "pavesi", name: "Pavesi", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Pavesi&size=128&fontWeight=600" },
    { slug: "misura", name: "Misura", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Misura&size=128&fontWeight=600" },
    { slug: "gentilini", name: "Gentilini", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Gentilini&size=128&fontWeight=600" },
    { slug: "balocco", name: "Balocco", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://balocco.it&size=128" },
    { slug: "colussi", name: "Colussi", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Colussi&size=128&fontWeight=600" },
    { slug: "divella", name: "Divella", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://divella.it&size=128" },
    { slug: "motta", name: "Motta", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Motta&size=128&fontWeight=600" },
    { slug: "zuegg", name: "Zuegg", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://zuegg.it&size=128" },
    { slug: "nutella", name: "Nutella", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://nutella.com&size=128" },
    { slug: "barilla", name: "Barilla", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://barilla.com&size=128" },
    { slug: "de-cecco", name: "De Cecco", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://dececco.com&size=128" },
    { slug: "rummo", name: "Rummo", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Rummo&size=128&fontWeight=600" },
    { slug: "riso-gallo", name: "Riso Gallo", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Riso%20Gallo&size=128&fontWeight=600" },
    { slug: "riso-scotti", name: "Riso Scotti", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Riso%20Scotti&size=128&fontWeight=600" },
    { slug: "rio-mare", name: "Rio Mare", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Rio%20Mare&size=128&fontWeight=600" },
    { slug: "mutti", name: "Mutti", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://mutti-parma.com&size=128" },
    { slug: "valfrutta", name: "Valfrutta", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Valfrutta&size=128&fontWeight=600" },
    { slug: "sacla", name: "Saclà", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Sacla&size=128&fontWeight=600" },
    { slug: "monini", name: "Monini", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://monini.com&size=128" },
    { slug: "bertolli", name: "Bertolli", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Bertolli&size=128&fontWeight=600" },
    { slug: "cirio", name: "Cirio", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Cirio&size=128&fontWeight=600" },
    { slug: "ponti", name: "Ponti", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Ponti&size=128&fontWeight=600" },
    { slug: "calve", name: "Calvé", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Calve&size=128&fontWeight=600" },
    { slug: "star", name: "Star", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Star&size=128&fontWeight=600" },
    { slug: "findus", name: "Findus", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://findus.it&size=128" },
    { slug: "buitoni", name: "Buitoni", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Buitoni&size=128&fontWeight=600" },
    { slug: "cameo", name: "Cameo", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Cameo&size=128&fontWeight=600" },
    { slug: "fratelli-beretta", name: "Fratelli Beretta", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Fratelli%20Beretta&size=128&fontWeight=600" },
    { slug: "rovagnati", name: "Rovagnati", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://rovagnati.it&size=128" },
    { slug: "algida", name: "Algida", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Algida&size=128&fontWeight=600" },
    { slug: "perugina", name: "Perugina", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://perugina.com&size=128" },
    { slug: "novi", name: "Novi", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Novi&size=128&fontWeight=600" },
    { slug: "lindt", name: "Lindt", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://lindt.it&size=128" },
    { slug: "milka", name: "Milka", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Milka&size=128&fontWeight=600" },
    { slug: "loacker", name: "Loacker", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://loacker.com&size=128" },
    { slug: "kinder", name: "Kinder", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://kinder.com&size=128" },
    { slug: "oreo", name: "Oreo", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Oreo&size=128&fontWeight=600" },
    { slug: "tuc", name: "Tuc", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Tuc&size=128&fontWeight=600" },
    { slug: "haribo", name: "Haribo", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://haribo.com&size=128" },
    { slug: "san-carlo", name: "San Carlo", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=San%20Carlo&size=128&fontWeight=600" },
    { slug: "wasa", name: "Wasa", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://wasa.com&size=128" },
    { slug: "gran-cereale", name: "Gran Cereale", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Gran%20Cereale&size=128&fontWeight=600" },
    { slug: "levissima", name: "Levissima", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Levissima&size=128&fontWeight=600" },
    { slug: "san-benedetto", name: "San Benedetto", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=San%20Benedetto&size=128&fontWeight=600" },
    { slug: "san-pellegrino", name: "San Pellegrino", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=San%20Pellegrino&size=128&fontWeight=600" },
    { slug: "ferrarelle", name: "Ferrarelle", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Ferrarelle&size=128&fontWeight=600" },
    { slug: "uliveto", name: "Uliveto", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Uliveto&size=128&fontWeight=600" },
    { slug: "coca-cola", name: "Coca-Cola", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://coca-cola.it&size=128" },
    { slug: "fanta", name: "Fanta", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Fanta&size=128&fontWeight=600" },
    { slug: "santal", name: "Santàl", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Santal&size=128&fontWeight=600" },
    { slug: "estathe", name: "Estathé", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Estathe&size=128&fontWeight=600" },
    { slug: "lavazza", name: "Lavazza", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://lavazza.it&size=128" },
    { slug: "illy", name: "illy", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://illy.com&size=128" },
    { slug: "kimbo", name: "Kimbo", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Kimbo&size=128&fontWeight=600" },
    { slug: "segafredo", name: "Segafredo", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Segafredo&size=128&fontWeight=600" },
    { slug: "nescafe", name: "Nescafé", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://nescafe.com&size=128" },
    { slug: "bonomelli", name: "Bonomelli", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Bonomelli&size=128&fontWeight=600" },
    { slug: "twinings", name: "Twinings", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Twinings&size=128&fontWeight=600" },
  ],

  products: [
    {
      slug: "banane",
      name: "Banane",
      imageUrl: "",
      price: 1.69,
      unitValue: 1000,
      unitType: "g",
      description:
        "Banane dolci e mature al punto giusto, del commercio equo.",
      stock: 130,
      categorySlugs: ["frutta-verdura"],
      isPopular: true,
    },
    {
      slug: "mele-golden",
      name: "Mele Golden",
      imageUrl: "",
      price: 2.19,
      unitValue: 1000,
      unitType: "g",
      description:
        "Mele Golden croccanti, di produzione italiana.",
      stock: 115,
      categorySlugs: ["frutta-verdura"],
      isPopular: true,
    },
    {
      slug: "pomodori-ciliegino",
      name: "Pomodori ciliegino",
      imageUrl: "",
      price: 2.79,
      originalPrice: 3.19,
      unitValue: 500,
      unitType: "g",
      description:
        "Pomodorini ciliegino maturati al sole, dolci in insalata.",
      stock: 95,
      categorySlugs: ["frutta-verdura"],
      isPopular: true,
    },
    {
      slug: "zucchine",
      name: "Zucchine",
      imageUrl: "",
      price: 2.09,
      unitValue: 1000,
      unitType: "g",
      description:
        "Zucchine sode, perfette grigliate o in padella.",
      stock: 85,
      categorySlugs: ["frutta-verdura"],
    },
    {
      slug: "carote",
      name: "Carote",
      imageUrl: "",
      price: 1.19,
      unitValue: 1000,
      unitType: "g",
      description:
        "Carote di pieno campo, lavate e pronte all'uso.",
      stock: 105,
      categorySlugs: ["frutta-verdura"],
    },
    {
      slug: "patate",
      name: "Patate a pasta gialla",
      imageUrl: "",
      price: 1.89,
      unitValue: 2000,
      unitType: "g",
      description:
        "Patate a pasta gialla, ottime al forno o lessate.",
      stock: 100,
      categorySlugs: ["frutta-verdura"],
    },
    {
      slug: "cipolle",
      name: "Cipolle dorate",
      imageUrl: "",
      price: 1.09,
      unitValue: 1000,
      unitType: "g",
      description:
        "Cipolle dorate dal gusto delicato, la base di ogni soffritto.",
      stock: 110,
      categorySlugs: ["frutta-verdura"],
    },
    {
      slug: "insalata-lattuga",
      name: "Lattuga romana",
      imageUrl: "",
      price: 0.99,
      unitValue: 1,
      unitType: "pcs",
      description:
        "Lattuga romana croccante, lavata e pronta.",
      stock: 90,
      categorySlugs: ["frutta-verdura"],
    },
    {
      slug: "mutti-polpa",
      name: "Mutti Polpa di pomodoro",
      imageUrl: `${IMG}/000/008/004/2556/front_en.449.400.jpg`,
      price: 1.29,
      unitValue: 400,
      unitType: "g",
      description:
        "Polpa di pomodoro a pezzi, da pomodori 100% italiani.",
      stock: 130,
      categorySlugs: ["frutta-verdura"],
      brandSlug: "mutti",
      isPopular: true,
    },
    {
      slug: "valfrutta-borlotti",
      name: "Valfrutta Borlotti",
      imageUrl: `${IMG}/800/144/000/1383/front_it.18.400.jpg`,
      price: 1.19,
      unitValue: 360,
      unitType: "g",
      description:
        "Fagioli borlotti italiani lavorati freschi.",
      stock: 115,
      categorySlugs: ["frutta-verdura"],
      brandSlug: "valfrutta",
    },
    {
      slug: "sacla-olive",
      name: "Saclà Olivolì snocciolate",
      imageUrl: `${IMG}/800/106/000/1466/front_it.44.400.jpg`,
      price: 2.19,
      unitValue: 290,
      unitType: "g",
      description:
        "Olive verdi snocciolate in salamoia, per l'aperitivo.",
      stock: 90,
      categorySlugs: ["frutta-verdura"],
      brandSlug: "sacla",
    },
    {
      slug: "arborea-latte",
      name: "Arborea Latte parzialmente scremato",
      imageUrl: `${IMG}/800/272/400/2966/front_it.104.400.jpg`,
      price: 1.29,
      unitValue: 1000,
      unitType: "ml",
      description:
        "Latte parzialmente scremato di alta qualità.",
      stock: 145,
      categorySlugs: ["latticini-uova"],
      brandSlug: "arborea",
      sizeVariants: [
        { value: 1000, price: 1.29 },
        { value: 500, price: 0.85 },
      ],
      isPopular: true,
    },
    {
      slug: "granarolo-latte",
      name: "Granarolo Latte parzialmente scremato UHT",
      imageUrl: `${IMG}/800/267/016/8631/front_it.81.400.jpg`,
      price: 1.35,
      unitValue: 1000,
      unitType: "ml",
      description:
        "Latte UHT parzialmente scremato, a lunga conservazione.",
      stock: 135,
      categorySlugs: ["latticini-uova"],
      brandSlug: "granarolo",
    },
    {
      slug: "parmalat-latte",
      name: "Parmalat Latte parzialmente scremato",
      imageUrl: `${IMG}/800/258/002/7004/front_it.68.400.jpg`,
      price: 1.39,
      unitValue: 1000,
      unitType: "ml",
      description:
        "Latte parzialmente scremato Parmalat, dal gusto leggero.",
      stock: 125,
      categorySlugs: ["latticini-uova"],
      brandSlug: "parmalat",
    },
    {
      slug: "galbani-mozzarella",
      name: "Galbani Mozzarella",
      imageUrl: `${IMG}/800/043/013/8719/front_en.91.400.jpg`,
      price: 0.99,
      originalPrice: 1.29,
      unitValue: 125,
      unitType: "g",
      description:
        "Mozzarella fresca in acqua di conservazione.",
      stock: 140,
      categorySlugs: ["latticini-uova"],
      brandSlug: "galbani",
      isPopular: true,
    },
    {
      slug: "soresina-grana-padano",
      name: "Latteria Soresina Grana Padano DOP",
      imageUrl: `${IMG}/800/467/311/0112/front_fr.29.400.jpg`,
      price: 2.49,
      unitValue: 100,
      unitType: "g",
      description:
        "Grana Padano DOP in scaglie, stagionato oltre 12 mesi.",
      stock: 95,
      categorySlugs: ["latticini-uova"],
      brandSlug: "latteria-soresina",
      isPopular: true,
    },
    {
      slug: "parmareggio-parmigiano",
      name: "Parmareggio Parmigiano Reggiano DOP",
      imageUrl: `${IMG}/801/072/199/8120/front_it.38.400.jpg`,
      price: 2.29,
      unitValue: 60,
      unitType: "g",
      description:
        "Parmigiano Reggiano DOP grattugiato fresco.",
      stock: 100,
      categorySlugs: ["latticini-uova"],
      brandSlug: "parmareggio",
      isPopular: true,
    },
    {
      slug: "philadelphia",
      name: "Philadelphia Original",
      imageUrl: `${IMG}/400/033/903/5229/front_en.106.400.jpg`,
      price: 2.79,
      unitValue: 200,
      unitType: "g",
      description:
        "Formaggio fresco spalmabile, delicato e cremoso.",
      stock: 90,
      categorySlugs: ["latticini-uova"],
      brandSlug: "philadelphia",
    },
    {
      slug: "danone-skyr",
      name: "Danone Skyr",
      imageUrl: `${IMG}/303/349/000/4743/front_fr.148.400.jpg`,
      price: 1.19,
      unitValue: 140,
      unitType: "g",
      description:
        "Skyr denso alla maniera islandese, ricco di proteine.",
      stock: 85,
      categorySlugs: ["latticini-uova"],
      brandSlug: "danone",
    },
    {
      slug: "vitasnella-cerealyo",
      name: "Vitasnella Cereal Yo frutti rossi",
      imageUrl: `${IMG}/762/221/008/9885/front_it.13.400.jpg`,
      price: 1.99,
      unitValue: 253,
      unitType: "g",
      description:
        "Yogurt magro con cereali e frutti rossi.",
      stock: 80,
      categorySlugs: ["latticini-uova"],
      brandSlug: "vitasnella",
    },
    {
      slug: "via-verde-uova-bio",
      name: "Via Verde Uova biologiche",
      imageUrl: `${IMG}/803/058/270/0120/front_en.27.400.jpg`,
      price: 2.19,
      unitValue: 4,
      unitType: "pcs",
      description:
        "Quattro uova biologiche da galline allevate a terra.",
      stock: 95,
      categorySlugs: ["latticini-uova"],
      brandSlug: "via-verde-bio",
      isPopular: true,
    },
    {
      slug: "burro",
      name: "Burro",
      imageUrl: "",
      price: 2.59,
      unitValue: 250,
      unitType: "g",
      description:
        "Burro di panna centrifugata, ideale in cucina e in pasticceria.",
      stock: 90,
      categorySlugs: ["latticini-uova"],
    },
    {
      slug: "ricotta",
      name: "Ricotta fresca",
      imageUrl: "",
      price: 1.79,
      unitValue: 250,
      unitType: "g",
      description:
        "Ricotta fresca di latte vaccino, dolce e leggera.",
      stock: 85,
      categorySlugs: ["latticini-uova"],
    },
    {
      slug: "pane-casereccio",
      name: "Pane casereccio",
      imageUrl: "",
      price: 2.49,
      unitValue: 500,
      unitType: "g",
      description:
        "Pane casereccio a lievitazione naturale, crosta croccante.",
      stock: 120,
      categorySlugs: ["pane-colazione"],
      isPopular: true,
    },
    {
      slug: "mulino-bianco-pan-bauletto",
      name: "Mulino Bianco Pan Bauletto Integrale",
      imageUrl: `${IMG}/807/680/950/4751/front_it.172.400.jpg`,
      price: 2.19,
      unitValue: 400,
      unitType: "g",
      description:
        "Pan bauletto integrale morbido, a fette.",
      stock: 110,
      categorySlugs: ["pane-colazione"],
      brandSlug: "mulino-bianco",
      isPopular: true,
    },
    {
      slug: "mulino-bianco-biscotti-integrali",
      name: "Mulino Bianco Biscotti con farina integrale",
      imageUrl: `${IMG}/807/680/957/6987/front_en.17.400.jpg`,
      price: 2.35,
      unitValue: 270,
      unitType: "g",
      description:
        "Biscotti con farina integrale di cereali, per la colazione.",
      stock: 95,
      categorySlugs: ["pane-colazione"],
      brandSlug: "mulino-bianco",
    },
    {
      slug: "pavesi-gocciole",
      name: "Pavesi Gocciole",
      imageUrl: `${IMG}/801/335/599/9143/front_en.116.400.jpg`,
      price: 2.49,
      originalPrice: 2.89,
      unitValue: 500,
      unitType: "g",
      description:
        "Frollini con gocce di cioccolato, formato famiglia.",
      stock: 100,
      categorySlugs: ["pane-colazione"],
      brandSlug: "pavesi",
      isPopular: true,
    },
    {
      slug: "pavesi-ringo-vaniglia",
      name: "Pavesi Ringo Vaniglia",
      imageUrl: `${IMG}/801/335/599/9501/front_en.61.400.jpg`,
      price: 1.89,
      unitValue: 165,
      unitType: "g",
      description:
        "I biscotti Ringo con crema alla vaniglia.",
      stock: 105,
      categorySlugs: ["pane-colazione"],
      brandSlug: "pavesi",
    },
    {
      slug: "misura-fette-biscottate",
      name: "Misura Fette biscottate",
      imageUrl: `${IMG}/800/259/004/3148/front_en.25.400.jpg`,
      price: 2.29,
      unitValue: 320,
      unitType: "g",
      description:
        "Fette biscottate leggere, da spalmare a colazione.",
      stock: 95,
      categorySlugs: ["pane-colazione"],
      brandSlug: "misura",
    },
    {
      slug: "gentilini-fette-integrali",
      name: "Gentilini Fette biscottate integrali",
      imageUrl: `${IMG}/800/746/514/1110/front_it.54.400.jpg`,
      price: 1.99,
      unitValue: 175,
      unitType: "g",
      description:
        "Fette biscottate integrali, croccanti e fragranti.",
      stock: 85,
      categorySlugs: ["pane-colazione"],
      brandSlug: "gentilini",
    },
    {
      slug: "balocco-cruschelle",
      name: "Balocco Cruschelle",
      imageUrl: `${IMG}/800/110/006/7025/front_it.77.400.jpg`,
      price: 2.15,
      unitValue: 700,
      unitType: "g",
      description:
        "Biscotti integrali con crusca di frumento.",
      stock: 90,
      categorySlugs: ["pane-colazione"],
      brandSlug: "balocco",
    },
    {
      slug: "colussi-crackers",
      name: "Colussi Crackers salati",
      imageUrl: `${IMG}/800/259/001/2915/front_en.29.400.jpg`,
      price: 1.75,
      unitValue: 250,
      unitType: "g",
      description:
        "Crackers salati in superficie, in monoporzioni.",
      stock: 100,
      categorySlugs: ["pane-colazione"],
      brandSlug: "colussi",
    },
    {
      slug: "divella-ottimini",
      name: "Divella Ottimini Integrali",
      imageUrl: `${IMG}/800/512/121/4253/front_en.34.400.jpg`,
      price: 2.05,
      unitValue: 400,
      unitType: "g",
      description:
        "Frollini integrali Ottimini, senza olio di palma.",
      stock: 85,
      categorySlugs: ["pane-colazione"],
      brandSlug: "divella",
    },
    {
      slug: "motta-buondi",
      name: "Motta Buondì",
      imageUrl: `${IMG}/801/403/700/8009/front_en.55.400.jpg`,
      price: 2.45,
      unitValue: 198,
      unitType: "g",
      description:
        "Il Buondì Motta glassato, la merenda di sempre.",
      stock: 90,
      categorySlugs: ["pane-colazione"],
      brandSlug: "motta",
    },
    {
      slug: "zuegg-confettura-fragole",
      name: "Zuegg Confettura extra di fragole",
      imageUrl: `${IMG}/000/008/029/8342/front_it.40.400.jpg`,
      price: 2.39,
      unitValue: 320,
      unitType: "g",
      description:
        "Confettura extra di fragole, con il 50% di frutta.",
      stock: 95,
      categorySlugs: ["pane-colazione"],
      brandSlug: "zuegg",
      isPopular: true,
    },
    {
      slug: "nutella-biscuits",
      name: "Nutella Biscuits",
      imageUrl: `${IMG}/800/050/031/0427/front_fr.550.400.jpg`,
      price: 2.99,
      unitValue: 304,
      unitType: "g",
      description:
        "Biscotti croccanti con cuore cremoso di Nutella.",
      stock: 105,
      categorySlugs: ["pane-colazione"],
      brandSlug: "nutella",
      isPopular: true,
    },
    {
      slug: "barilla-spaghetti",
      name: "Barilla Spaghetti n. 5",
      imageUrl: `${IMG}/807/680/019/5057/front_en.3809.400.jpg`,
      price: 1.29,
      originalPrice: 1.55,
      unitValue: 500,
      unitType: "g",
      description:
        "Spaghetti n. 5 di semola di grano duro, cottura 9 minuti.",
      stock: 150,
      categorySlugs: ["pasta-riso-scatolame"],
      brandSlug: "barilla",
      sizeVariants: [
        { value: 500, price: 1.29, originalPrice: 1.55 },
        { value: 1000, price: 2.35 },
      ],
      isPopular: true,
    },
    {
      slug: "de-cecco-linguine",
      name: "De Cecco Linguine n. 7",
      imageUrl: `${IMG}/800/125/012/0076/front_bg.126.400.jpg`,
      price: 1.75,
      unitValue: 500,
      unitType: "g",
      description:
        "Linguine n. 7 trafilate al bronzo, essiccate lentamente.",
      stock: 120,
      categorySlugs: ["pasta-riso-scatolame"],
      brandSlug: "de-cecco",
      isPopular: true,
    },
    {
      slug: "rummo-gnocchi",
      name: "Rummo Gnocchi di patate",
      imageUrl: `${IMG}/800/834/320/1179/front_en.74.400.jpg`,
      price: 1.99,
      unitValue: 500,
      unitType: "g",
      description:
        "Gnocchi di patate pronti in tre minuti.",
      stock: 95,
      categorySlugs: ["pasta-riso-scatolame"],
      brandSlug: "rummo",
    },
    {
      slug: "barilla-farina",
      name: "Barilla Farina",
      imageUrl: `${IMG}/807/680/279/5019/front_en.26.400.jpg`,
      price: 0.95,
      unitValue: 1000,
      unitType: "g",
      description:
        "Farina di grano tenero tipo 00, per pasta fresca e dolci.",
      stock: 130,
      categorySlugs: ["pasta-riso-scatolame"],
      brandSlug: "barilla",
    },
    {
      slug: "riso-gallo-risotto",
      name: "Riso Gallo Risotto Tradition",
      imageUrl: `${IMG}/800/142/000/3406/front_fr.47.400.jpg`,
      price: 2.79,
      unitValue: 500,
      unitType: "g",
      description:
        "Riso Carnaroli per risotti, tenuta di cottura perfetta.",
      stock: 90,
      categorySlugs: ["pasta-riso-scatolame"],
      brandSlug: "riso-gallo",
    },
    {
      slug: "riso-scotti-integrale",
      name: "Riso Scotti Riso integrale",
      imageUrl: `${IMG}/800/186/019/0513/front_it.111.400.jpg`,
      price: 2.19,
      unitValue: 1000,
      unitType: "g",
      description:
        "Riso integrale ricco di fibre, cottura 15 minuti.",
      stock: 95,
      categorySlugs: ["pasta-riso-scatolame"],
      brandSlug: "riso-scotti",
    },
    {
      slug: "rio-mare-tonno-olio",
      name: "Rio Mare Tonno all'olio di oliva",
      imageUrl: `${IMG}/800/403/034/4938/front_en.107.400.jpg`,
      price: 1.29,
      unitValue: 52,
      unitType: "g",
      description:
        "Tonno all'olio di oliva in monoporzione.",
      stock: 140,
      categorySlugs: ["pasta-riso-scatolame"],
      brandSlug: "rio-mare",
      isPopular: true,
    },
    {
      slug: "rio-mare-insalatissime",
      name: "Rio Mare Insalatissime",
      imageUrl: `${IMG}/800/403/002/6018/front_en.167.400.jpg`,
      price: 2.59,
      unitValue: 160,
      unitType: "g",
      description:
        "Insalata di tonno pronta, completa di forchetta.",
      stock: 100,
      categorySlugs: ["pasta-riso-scatolame"],
      brandSlug: "rio-mare",
    },
    {
      slug: "zucchero",
      name: "Zucchero semolato",
      imageUrl: "",
      price: 1.15,
      unitValue: 1000,
      unitType: "g",
      description:
        "Zucchero semolato di barbabietola, grana fine.",
      stock: 125,
      categorySlugs: ["pasta-riso-scatolame"],
    },
    {
      slug: "sale-fino",
      name: "Sale fino da cucina",
      imageUrl: "",
      price: 0.65,
      unitValue: 1000,
      unitType: "g",
      description:
        "Sale fino marino, per la cucina di ogni giorno.",
      stock: 130,
      categorySlugs: ["pasta-riso-scatolame"],
    },
    {
      slug: "passata-di-pomodoro",
      name: "Passata di pomodoro",
      imageUrl: "",
      price: 1.09,
      unitValue: 700,
      unitType: "g",
      description:
        "Passata di pomodoro densa, da pomodori maturi.",
      stock: 135,
      categorySlugs: ["pasta-riso-scatolame"],
    },
    {
      slug: "monini-classico",
      name: "Monini Classico Olio extra vergine",
      imageUrl: `${IMG}/000/008/005/3835/front_de.84.400.jpg`,
      price: 7.95,
      originalPrice: 8.95,
      unitValue: 1000,
      unitType: "ml",
      description:
        "Olio extra vergine di oliva Classico, fruttato ed equilibrato.",
      stock: 75,
      categorySlugs: ["olio-condimenti"],
      brandSlug: "monini",
      isPopular: true,
    },
    {
      slug: "bertolli-originale",
      name: "Bertolli Originale Olio extra vergine",
      imageUrl: `${IMG}/800/247/001/7290/front_it.16.400.jpg`,
      price: 8.45,
      unitValue: 1000,
      unitType: "ml",
      description:
        "Olio extra vergine di oliva dal gusto rotondo.",
      stock: 65,
      categorySlugs: ["olio-condimenti"],
      brandSlug: "bertolli",
    },
    {
      slug: "cirio-olio-italiano",
      name: "Cirio Olio extra vergine 100% italiano",
      imageUrl: `${IMG}/800/427/508/2282/front_it.3.400.jpg`,
      price: 9.25,
      unitValue: 1000,
      unitType: "ml",
      description:
        "Olio extra vergine di oliva da olive 100% italiane.",
      stock: 60,
      categorySlugs: ["olio-condimenti"],
      brandSlug: "cirio",
    },
    {
      slug: "ponti-glassa-balsamico",
      name: "Ponti Glassa all'Aceto Balsamico di Modena",
      imageUrl: `${IMG}/800/101/007/6568/front_en.89.400.jpg`,
      price: 2.65,
      unitValue: 250,
      unitType: "ml",
      description:
        "Glassa densa all'aceto balsamico di Modena IGP.",
      stock: 85,
      categorySlugs: ["olio-condimenti"],
      brandSlug: "ponti",
    },
    {
      slug: "calve-maionese",
      name: "Calvé Maionese",
      imageUrl: `${IMG}/872/018/239/4439/front_it.65.400.jpg`,
      price: 2.45,
      unitValue: 428,
      unitType: "g",
      description:
        "Maionese Calvé, cremosa e delicata.",
      stock: 95,
      categorySlugs: ["olio-condimenti"],
      brandSlug: "calve",
      isPopular: true,
    },
    {
      slug: "star-maionese",
      name: "Star Maionese",
      imageUrl: `${IMG}/611/118/400/4129/front_en.55.400.jpg`,
      price: 2.19,
      unitValue: 280,
      unitType: "ml",
      description:
        "Maionese Star su ricetta originale.",
      stock: 90,
      categorySlugs: ["olio-condimenti"],
      brandSlug: "star",
    },
    {
      slug: "aceto-balsamico",
      name: "Aceto balsamico di Modena",
      imageUrl: "",
      price: 2.35,
      unitValue: 500,
      unitType: "ml",
      description:
        "Aceto balsamico di Modena IGP, per insalate e secondi.",
      stock: 90,
      categorySlugs: ["olio-condimenti"],
    },
    {
      slug: "pepe-nero",
      name: "Pepe nero macinato",
      imageUrl: "",
      price: 1.45,
      unitValue: 100,
      unitType: "g",
      description:
        "Pepe nero macinato, intenso e profumato.",
      stock: 100,
      categorySlugs: ["olio-condimenti"],
    },
    {
      slug: "origano",
      name: "Origano secco",
      imageUrl: "",
      price: 1.15,
      unitValue: 20,
      unitType: "g",
      description:
        "Origano secco in foglie, per pizza e pomodori.",
      stock: 110,
      categorySlugs: ["olio-condimenti"],
    },
    {
      slug: "findus-bastoncini",
      name: "Findus Bastoncini di merluzzo",
      imageUrl: `${IMG}/805/701/822/1035/front_it.4.400.jpg`,
      price: 3.49,
      originalPrice: 3.99,
      unitValue: 300,
      unitType: "g",
      description:
        "Bastoncini di merluzzo impanati, croccanti al forno.",
      stock: 85,
      categorySlugs: ["surgelati-salumi"],
      brandSlug: "findus",
      isPopular: true,
    },
    {
      slug: "findus-capitan",
      name: "Findus 18 Bastoncini Capitan Findus",
      imageUrl: `${IMG}/805/701/822/2988/front_it.8.400.jpg`,
      price: 4.79,
      unitValue: 450,
      unitType: "g",
      description:
        "Diciotto bastoncini Capitan Findus, formato famiglia.",
      stock: 70,
      categorySlugs: ["surgelati-salumi"],
      brandSlug: "findus",
    },
    {
      slug: "buitoni-mini-pizze",
      name: "Buitoni Mini pizze Tomate e Mozzarella",
      imageUrl: `${IMG}/761/303/437/7104/front_fr.98.400.jpg`,
      price: 3.25,
      unitValue: 270,
      unitType: "g",
      description:
        "Nove mini pizze surgelate pomodoro e mozzarella.",
      stock: 80,
      categorySlugs: ["surgelati-salumi"],
      brandSlug: "buitoni",
    },
    {
      slug: "cameo-speedy-pizza",
      name: "Cameo Speedy Pizza",
      imageUrl: `${IMG}/800/300/055/0010/front_it.4.400.jpg`,
      price: 2.95,
      unitValue: 300,
      unitType: "g",
      description:
        "Quattro pizzette pronte in pochi minuti.",
      stock: 85,
      categorySlugs: ["surgelati-salumi"],
      brandSlug: "cameo",
    },
    {
      slug: "beretta-prosciutto-cotto",
      name: "Fratelli Beretta Prosciutto cotto",
      imageUrl: `${IMG}/800/766/018/9306/front_en.52.400.jpg`,
      price: 2.69,
      unitValue: 120,
      unitType: "g",
      description:
        "Prosciutto cotto di alta qualità, in vaschetta.",
      stock: 100,
      categorySlugs: ["surgelati-salumi"],
      brandSlug: "fratelli-beretta",
      isPopular: true,
    },
    {
      slug: "rovagnati-fesa-tacchino",
      name: "Rovagnati Fesa di tacchino al forno",
      imageUrl: `${IMG}/800/714/151/6812/front_it.19.400.jpg`,
      price: 2.49,
      unitValue: 100,
      unitType: "g",
      description:
        "Fesa di tacchino al forno, affettata sottile.",
      stock: 95,
      categorySlugs: ["surgelati-salumi"],
      brandSlug: "rovagnati",
    },
    {
      slug: "rovagnati-grancotto",
      name: "Rovagnati Gran Cotto",
      imageUrl: `${IMG}/800/714/151/6836/front_it.3.400.jpg`,
      price: 2.99,
      unitValue: 100,
      unitType: "g",
      description:
        "Prosciutto Gran Cotto Rovagnati, senza glutine.",
      stock: 90,
      categorySlugs: ["surgelati-salumi"],
      brandSlug: "rovagnati",
    },
    {
      slug: "algida-fior-di-fragola",
      name: "Algida Fior di Fragola",
      imageUrl: `${IMG}/000/008/011/2655/front_it.3.400.jpg`,
      price: 3.45,
      unitValue: 500,
      unitType: "ml",
      description:
        "Gelato Fior di Fragola, in vaschetta da condividere.",
      stock: 65,
      categorySlugs: ["surgelati-salumi"],
      brandSlug: "algida",
      isPopular: true,
    },
    {
      slug: "piselli-surgelati",
      name: "Piselli surgelati",
      imageUrl: "",
      price: 1.29,
      unitValue: 750,
      unitType: "g",
      description:
        "Piselli fini surgelati poco dopo la raccolta.",
      stock: 95,
      categorySlugs: ["surgelati-salumi"],
    },
    {
      slug: "spinaci-surgelati",
      name: "Spinaci surgelati",
      imageUrl: "",
      price: 1.39,
      unitValue: 450,
      unitType: "g",
      description:
        "Spinaci in foglia surgelati, in porzioni pratiche.",
      stock: 90,
      categorySlugs: ["surgelati-salumi"],
    },
    {
      slug: "perugina-baci",
      name: "Perugina Baci",
      imageUrl: `${IMG}/800/030/032/4655/front_it.36.400.jpg`,
      price: 4.29,
      originalPrice: 4.99,
      unitValue: 200,
      unitType: "g",
      description:
        "I Baci Perugina con nocciola intera e il loro cartiglio.",
      stock: 75,
      categorySlugs: ["dolci-snack"],
      brandSlug: "perugina",
      isPopular: true,
    },
    {
      slug: "novi-nero-99",
      name: "Novi Nero Nero 99%",
      imageUrl: `${IMG}/800/638/021/5807/front_it.34.400.jpg`,
      price: 2.19,
      unitValue: 75,
      unitType: "g",
      description:
        "Cioccolato fondente extra al 99% di cacao.",
      stock: 80,
      categorySlugs: ["dolci-snack"],
      brandSlug: "novi",
    },
    {
      slug: "lindt-noir-70",
      name: "Lindt Excellence Fondente 70%",
      imageUrl: `${IMG}/304/692/002/2651/front_en.159.400.jpg`,
      price: 2.35,
      unitValue: 100,
      unitType: "g",
      description:
        "Cioccolato fondente intenso con il 70% di cacao.",
      stock: 85,
      categorySlugs: ["dolci-snack"],
      brandSlug: "lindt",
    },
    {
      slug: "milka-cake-choc",
      name: "Milka Cake & Choc",
      imageUrl: `${IMG}/762/230/078/4751/front_de.111.400.jpg`,
      price: 2.29,
      unitValue: 175,
      unitType: "g",
      description:
        "Tortine soffici con cuore di cioccolato Milka.",
      stock: 90,
      categorySlugs: ["dolci-snack"],
      brandSlug: "milka",
    },
    {
      slug: "loacker-napolitaner",
      name: "Loacker Napolitaner",
      imageUrl: `${IMG}/800/038/000/7219/front_en.43.400.jpg`,
      price: 2.55,
      unitValue: 175,
      unitType: "g",
      description:
        "Wafer Napolitaner con crema di nocciole.",
      stock: 100,
      categorySlugs: ["dolci-snack"],
      brandSlug: "loacker",
      isPopular: true,
    },
    {
      slug: "loacker-wafers-fondenti",
      name: "Loacker Wafers Fondenti",
      imageUrl: `${IMG}/800/038/014/1548/front_hr.45.400.jpg`,
      price: 2.45,
      unitValue: 150,
      unitType: "g",
      description:
        "Wafer ricoperti di cioccolato fondente.",
      stock: 90,
      categorySlugs: ["dolci-snack"],
      brandSlug: "loacker",
    },
    {
      slug: "kinder-bueno",
      name: "Kinder Bueno",
      imageUrl: `${IMG}/000/008/005/2760/front_en.503.400.jpg`,
      price: 1.19,
      unitValue: 43,
      unitType: "g",
      description:
        "Due barrette di wafer con latte e nocciole.",
      stock: 140,
      categorySlugs: ["dolci-snack"],
      brandSlug: "kinder",
    },
    {
      slug: "oreo-original",
      name: "Oreo Original",
      imageUrl: `${IMG}/762/230/074/4663/front_it.241.400.jpg`,
      price: 2.19,
      unitValue: 220,
      unitType: "g",
      description:
        "I biscotti Oreo con crema al centro.",
      stock: 105,
      categorySlugs: ["dolci-snack"],
      brandSlug: "oreo",
    },
    {
      slug: "tuc-cheese",
      name: "Tuc Gusto Cheese",
      imageUrl: `${IMG}/762/230/057/1351/front_en.156.400.jpg`,
      price: 1.65,
      unitValue: 100,
      unitType: "g",
      description:
        "Crackers Tuc al gusto formaggio.",
      stock: 100,
      categorySlugs: ["dolci-snack"],
      brandSlug: "tuc",
    },
    {
      slug: "haribo-orsetti",
      name: "Haribo Orsetti d'oro",
      imageUrl: `${IMG}/900/297/530/1558/front_en.16.400.jpg`,
      price: 1.09,
      unitValue: 100,
      unitType: "g",
      description:
        "Gli Orsetti d'oro Haribo in sei gusti di frutta.",
      stock: 150,
      categorySlugs: ["dolci-snack"],
      brandSlug: "haribo",
      isPopular: true,
    },
    {
      slug: "san-carlo-paprika",
      name: "San Carlo Più Gusto Paprika",
      imageUrl: `${IMG}/800/313/012/7922/front_it.92.400.jpg`,
      price: 2.35,
      unitValue: 150,
      unitType: "g",
      description:
        "Patatine Più Gusto al gusto paprika.",
      stock: 110,
      categorySlugs: ["dolci-snack"],
      brandSlug: "san-carlo",
      isPopular: true,
    },
    {
      slug: "wasa-tartine",
      name: "Wasa Croccanti Authentique",
      imageUrl: `${IMG}/730/040/048/1595/front_fr.265.400.jpg`,
      price: 2.25,
      unitValue: 275,
      unitType: "g",
      description:
        "Croccanti di segale, da farcire.",
      stock: 80,
      categorySlugs: ["dolci-snack"],
      brandSlug: "wasa",
    },
    {
      slug: "gran-cereale-riso",
      name: "Gran Cereale Croccante con riso",
      imageUrl: `${IMG}/807/680/951/7300/front_en.34.400.jpg`,
      price: 2.65,
      unitValue: 230,
      unitType: "g",
      description:
        "Biscotti croccanti con riso soffiato e cereali.",
      stock: 85,
      categorySlugs: ["dolci-snack"],
      brandSlug: "gran-cereale",
    },
    {
      slug: "levissima",
      name: "Levissima Acqua minerale",
      imageUrl: `${IMG}/000/008/000/0532/front_en.50.400.jpg`,
      price: 0.65,
      unitValue: 1500,
      unitType: "ml",
      description:
        "Acqua minerale naturale delle Alpi, leggerissima.",
      stock: 220,
      categorySlugs: ["bevande"],
      brandSlug: "levissima",
      sizeVariants: [
        { value: 1500, price: 0.65 },
        { value: 500, price: 0.45 },
      ],
      isPopular: true,
    },
    {
      slug: "san-benedetto",
      name: "San Benedetto Acqua minerale",
      imageUrl: `${IMG}/800/162/001/2734/front_it.40.400.jpg`,
      price: 0.45,
      unitValue: 500,
      unitType: "ml",
      description:
        "Acqua minerale naturale in formato da mezzo litro.",
      stock: 200,
      categorySlugs: ["bevande"],
      brandSlug: "san-benedetto",
    },
    {
      slug: "san-pellegrino",
      name: "San Pellegrino Acqua frizzante",
      imageUrl: `${IMG}/800/227/001/4901/front_en.304.400.jpg`,
      price: 0.95,
      unitValue: 1000,
      unitType: "ml",
      description:
        "Acqua minerale frizzante, la bollicina italiana per eccellenza.",
      stock: 180,
      categorySlugs: ["bevande"],
      brandSlug: "san-pellegrino",
      isPopular: true,
    },
    {
      slug: "ferrarelle",
      name: "Ferrarelle Acqua effervescente naturale",
      imageUrl: `${IMG}/000/008/013/4091/front_it.54.400.jpg`,
      price: 0.85,
      unitValue: 1500,
      unitType: "ml",
      description:
        "Acqua effervescente naturale, dalle bollicine leggere.",
      stock: 170,
      categorySlugs: ["bevande"],
      brandSlug: "ferrarelle",
    },
    {
      slug: "uliveto",
      name: "Uliveto Acqua minerale",
      imageUrl: `${IMG}/800/849/000/0021/front_en.3.400.jpg`,
      price: 0.89,
      unitValue: 1500,
      unitType: "ml",
      description:
        "Acqua minerale naturale, favorisce la digestione.",
      stock: 165,
      categorySlugs: ["bevande"],
      brandSlug: "uliveto",
    },
    {
      slug: "coca-cola",
      name: "Coca-Cola",
      imageUrl: `${IMG}/544/900/021/4911/front_fr.335.400.jpg`,
      price: 0.95,
      unitValue: 330,
      unitType: "ml",
      description:
        "Coca-Cola in lattina, da servire ben fredda.",
      stock: 200,
      categorySlugs: ["bevande"],
      brandSlug: "coca-cola",
      isPopular: true,
    },
    {
      slug: "fanta-arancia",
      name: "Fanta Arancia",
      imageUrl: `${IMG}/000/004/082/2938/front_en.164.400.jpg`,
      price: 1.05,
      unitValue: 500,
      unitType: "ml",
      description:
        "Fanta Arancia con succo d'arancia.",
      stock: 175,
      categorySlugs: ["bevande"],
      brandSlug: "fanta",
    },
    {
      slug: "santal-ace",
      name: "Santàl ACE",
      imageUrl: `${IMG}/800/258/002/6267/front_it.23.400.jpg`,
      price: 1.75,
      unitValue: 1000,
      unitType: "ml",
      description:
        "Succo ACE arancia, limone e carota, con vitamine.",
      stock: 130,
      categorySlugs: ["bevande"],
      brandSlug: "santal",
      isPopular: true,
    },
    {
      slug: "estathe-limone",
      name: "Estathé Limone",
      imageUrl: `${IMG}/000/008/017/7685/front_it.3.400.jpg`,
      price: 0.95,
      unitValue: 330,
      unitType: "ml",
      description:
        "Il tè freddo al limone in brick, da portare con sé.",
      stock: 190,
      categorySlugs: ["bevande"],
      brandSlug: "estathe",
      isPopular: true,
    },
    {
      slug: "riso-scotti-oat",
      name: "Riso Scotti Oat Original",
      imageUrl: `${IMG}/800/186/025/2846/front_it.83.400.jpg`,
      price: 2.29,
      unitValue: 1000,
      unitType: "ml",
      description:
        "Bevanda d'avena senza zuccheri aggiunti.",
      stock: 95,
      categorySlugs: ["bevande"],
      brandSlug: "riso-scotti",
    },
    {
      slug: "riso-scotti-rice",
      name: "Riso Scotti Rice Original",
      imageUrl: `${IMG}/800/186/081/0008/front_en.125.400.jpg`,
      price: 2.19,
      unitValue: 1000,
      unitType: "ml",
      description:
        "Bevanda di riso naturalmente dolce, senza lattosio.",
      stock: 90,
      categorySlugs: ["bevande"],
      brandSlug: "riso-scotti",
    },
    {
      slug: "lavazza-il-mattino",
      name: "Lavazza Il Mattino",
      imageUrl: `${IMG}/800/007/003/2866/front_en.10.400.jpg`,
      price: 10.95,
      originalPrice: 12.49,
      unitValue: 1000,
      unitType: "g",
      description:
        "Caffè macinato Il Mattino, quattro confezioni da 250 g.",
      stock: 70,
      categorySlugs: ["caffe-te"],
      brandSlug: "lavazza",
      isPopular: true,
    },
    {
      slug: "illy-classico",
      name: "illy Caffè tostato classico",
      imageUrl: `${IMG}/800/375/390/0438/front_en.11.400.jpg`,
      price: 5.95,
      unitValue: 250,
      unitType: "g",
      description:
        "Caffè macinato tostatura classica, miscela 100% arabica.",
      stock: 85,
      categorySlugs: ["caffe-te"],
      brandSlug: "illy",
      isPopular: true,
    },
    {
      slug: "kimbo-macinato",
      name: "Kimbo Caffè macinato fresco",
      imageUrl: `${IMG}/800/220/015/5100/front_fr.11.400.jpg`,
      price: 3.45,
      unitValue: 250,
      unitType: "g",
      description:
        "Caffè macinato napoletano, corposo e cremoso.",
      stock: 100,
      categorySlugs: ["caffe-te"],
      brandSlug: "kimbo",
      isPopular: true,
    },
    {
      slug: "segafredo-brasile",
      name: "Segafredo Le Origini Brasile",
      imageUrl: `${IMG}/800/341/024/0549/front_it.3.400.jpg`,
      price: 3.95,
      unitValue: 250,
      unitType: "g",
      description:
        "Caffè macinato monorigine Brasile, dolce e rotondo.",
      stock: 85,
      categorySlugs: ["caffe-te"],
      brandSlug: "segafredo",
    },
    {
      slug: "nescafe-dolce-gusto",
      name: "Nescafé Dolce Gusto Cortado",
      imageUrl: `${IMG}/761/303/282/7014/front_en.38.400.jpg`,
      price: 4.65,
      unitValue: 100,
      unitType: "g",
      description:
        "Capsule Dolce Gusto espresso macchiato.",
      stock: 90,
      categorySlugs: ["caffe-te"],
      brandSlug: "nescafe",
    },
    {
      slug: "bonomelli-camomilla",
      name: "Bonomelli Camomilla setacciata",
      imageUrl: `${IMG}/800/184/001/1166/front_en.9.400.jpg`,
      price: 2.35,
      unitValue: 20,
      unitType: "pcs",
      description:
        "Venti filtri di camomilla setacciata, per notti calme.",
      stock: 110,
      categorySlugs: ["caffe-te"],
      brandSlug: "bonomelli",
    },
    {
      slug: "twinings-verde",
      name: "Twinings Tè verde Gunpowder",
      imageUrl: `${IMG}/007/017/702/9784/front_en.38.400.jpg`,
      price: 3.15,
      unitValue: 100,
      unitType: "g",
      description:
        "Tè verde Gunpowder in foglia, fresco e agrumato.",
      stock: 75,
      categorySlugs: ["caffe-te"],
      brandSlug: "twinings",
    },
    {
      slug: "caffe-macinato",
      name: "Caffè macinato per moka",
      imageUrl: "",
      price: 3.75,
      unitValue: 250,
      unitType: "g",
      description:
        "Caffè macinato per moka, tostatura media.",
      stock: 105,
      categorySlugs: ["caffe-te"],
    },
    {
      slug: "cialde-espresso",
      name: "Cialde espresso",
      imageUrl: "",
      price: 4.85,
      unitValue: 50,
      unitType: "pcs",
      description:
        "Cinquanta cialde compatibili, tostatura espresso.",
      stock: 85,
      categorySlugs: ["caffe-te"],
    },
    {
      slug: "detersivo-piatti",
      name: "Detersivo per piatti Limone",
      imageUrl: "",
      price: 1.29,
      unitValue: 750,
      unitType: "ml",
      description:
        "Detersivo per piatti sgrassante al limone, schiuma persistente.",
      stock: 110,
      categorySlugs: ["casa-pulizia"],
    },
    {
      slug: "sgrassatore",
      name: "Sgrassatore universale",
      imageUrl: "",
      price: 1.79,
      unitValue: 750,
      unitType: "ml",
      description:
        "Sgrassatore universale per tutte le superfici lavabili.",
      stock: 100,
      categorySlugs: ["casa-pulizia"],
    },
    {
      slug: "carta-igienica",
      name: "Carta igienica 3 veli",
      imageUrl: "",
      price: 4.19,
      originalPrice: 4.79,
      unitValue: 12,
      unitType: "pcs",
      description:
        "Dodici rotoli a tre veli, morbidi e resistenti.",
      stock: 130,
      categorySlugs: ["casa-pulizia"],
      isPopular: true,
    },
    {
      slug: "carta-casa",
      name: "Carta casa",
      imageUrl: "",
      price: 2.59,
      unitValue: 4,
      unitType: "pcs",
      description:
        "Quattro rotoli di carta casa ad alto assorbimento.",
      stock: 115,
      categorySlugs: ["casa-pulizia"],
    },
    {
      slug: "sacchi-immondizia",
      name: "Sacchi immondizia 50 l",
      imageUrl: "",
      price: 2.29,
      unitValue: 20,
      unitType: "pcs",
      description:
        "Venti sacchi resistenti con maniglie richiudibili.",
      stock: 100,
      categorySlugs: ["casa-pulizia"],
    },
    {
      slug: "detersivo-lavatrice",
      name: "Detersivo liquido per lavatrice",
      imageUrl: "",
      price: 12.75,
      originalPrice: 14.25,
      unitValue: 3000,
      unitType: "ml",
      description:
        "Detersivo liquido per 60 lavaggi, efficace già a 20 °C.",
      stock: 65,
      categorySlugs: ["casa-pulizia"],
      isPopular: true,
    },
    {
      slug: "pastiglie-lavastoviglie",
      name: "Pastiglie lavastoviglie tutto in uno",
      imageUrl: "",
      price: 13.45,
      unitValue: 60,
      unitType: "pcs",
      description:
        "Sessanta pastiglie tutto in uno con sale e brillantante.",
      stock: 70,
      categorySlugs: ["casa-pulizia"],
    },
    {
      slug: "dentifricio",
      name: "Dentifricio protezione totale",
      imageUrl: "",
      price: 2.09,
      unitValue: 75,
      unitType: "ml",
      description:
        "Dentifricio al fluoro per la protezione quotidiana dalle carie.",
      stock: 110,
      categorySlugs: ["casa-pulizia"],
    },
  ],

  coupons: [
    {
      code: "BENVENUTO10",
      type: "percent",
      value: 10,
      scope: "store",
      minOrderValue: 20,
      maxDiscount: 5,
      usageLimit: 500,
      perUserLimit: 1,
    },
    {
      code: "FRESCHI5",
      type: "percent",
      value: 5,
      scope: "category",
      targetCategorySlugs: ["frutta-verdura"],
      minOrderValue: 10,
      maxDiscount: 3,
      usageLimit: 300,
      perUserLimit: 2,
    },
    {
      code: "CAFFE15",
      type: "percent",
      value: 15,
      scope: "category",
      targetCategorySlugs: ["caffe-te"],
      minOrderValue: 15,
      maxDiscount: 5,
      usageLimit: 200,
      perUserLimit: 1,
    },
    {
      code: "DOLCE2",
      type: "flat",
      value: 2,
      scope: "category",
      targetCategorySlugs: ["dolci-snack"],
      minOrderValue: 12,
      maxDiscount: 2,
      usageLimit: 250,
      perUserLimit: 2,
    },
    {
      code: "CASA3",
      type: "flat",
      value: 3,
      scope: "category",
      targetCategorySlugs: ["casa-pulizia"],
      minOrderValue: 25,
      maxDiscount: 3,
      usageLimit: 150,
      perUserLimit: 1,
    },
    {
      code: "PIZZA1",
      type: "flat",
      value: 1,
      scope: "product",
      targetProductSlugs: ["buitoni-mini-pizze", "cameo-speedy-pizza", "findus-bastoncini"],
      minOrderValue: 6,
      maxDiscount: 1,
      usageLimit: 400,
      perUserLimit: 3,
    },
    {
      code: "SPEDIZIONE",
      type: "flat",
      value: 4,
      scope: "store",
      minOrderValue: 40,
      maxDiscount: 4,
      usageLimit: 400,
      perUserLimit: 1,
    },
  ],

  banners: [
    {
      title: "Dal mercato ogni mattina",
      subtitle: "Frutta e verdura appena arrivate",
      imageUrl:
        "https://images.unsplash.com/photo-1542838132-92c53300491e?w=1200&q=80",
      targetCategorySlug: "frutta-verdura",
      sortOrder: 0,
      backgroundColor: "#1F6F4A",
    },
    {
      title: "L'ora del caffè",
      subtitle: "Fino al 15% su macinato e capsule",
      imageUrl:
        "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=1200&q=80",
      targetCategorySlug: "caffe-te",
      sortOrder: 1,
      backgroundColor: "#4A2C1A",
    },
    {
      title: "Voglia di dolce",
      subtitle: "Cioccolato e biscotti in offerta",
      imageUrl:
        "https://images.unsplash.com/photo-1481391319762-47dff72954d9?w=1200&q=80",
      targetCategorySlug: "dolci-snack",
      sortOrder: 2,
      backgroundColor: "#7A1F3D",
    },
    {
      title: "Riempi la dispensa",
      subtitle: "Pasta, riso e scatolame in formato famiglia",
      imageUrl:
        "https://images.unsplash.com/photo-1556909212-d5b604d0c90d?w=1200&q=80",
      targetCategorySlug: "pasta-riso-scatolame",
      sortOrder: 3,
      backgroundColor: "#2A4C7A",
    },
  ],
};
