// The **Spain** sample catalog — a realistic Spanish supermarket
// (Mercadona/Carrefour-ES style aisles, real Spanish brands, € retail pricing),
// seeded in Spanish because catalog content is single-valued (see
// docs/explanation/content-i18n-plan.md).
//
// Prices are Spanish shelf prices, NOT converted from another market. The
// storefront's price filter uses per-currency bands (2/5/10 for euros — see
// cordelia's ProductPriceFilter), and a catalog that leaves a band empty makes
// that chip unmatchable; npm run verify:seed-bands enforces the spread.
//
// Image sources (every URL is verified live by scripts/verify-seed-images.mjs
// — re-run it whenever this file changes):
// - Products: real Spanish product photos from Open Food Facts
//   (images.openfoodfacts.org) — © Open Food Facts contributors, CC-BY-SA
//   4.0. Barcodes were harvested from OFF's Spanish catalogue and every path
//   re-resolved through its product endpoint, because the search index returns
//   unpadded paths and stale revisions for short codes. Loose produce and the
//   whole Hogar aisle carry imageUrl "" — OFF is a packaged-*food* database —
//   and every consumer renders a placeholder.
// - Banners: landscape photography from Unsplash.
// - Brand logos: Google's favicon endpoint / DiceBear monograms.

import {
  OFF_IMAGE_BASE,
  type GrocerySeed,
} from "./seed-types";

const IMG = OFF_IMAGE_BASE;

export const SPAIN_SEED: GrocerySeed = {
  categories: [
    {
      slug: "frutas-verduras",
      name: "Frutas y Verduras",
      imageUrl: "",
      groupName: "Alimentación",
    },
    {
      slug: "lacteos-huevos",
      name: "Lácteos y Huevos",
      imageUrl: `${IMG}/841/029/711/2041/front_en.95.400.jpg`,
      groupName: "Alimentación",
    },
    {
      slug: "panaderia-desayuno",
      name: "Panadería y Desayuno",
      imageUrl: `${IMG}/841/260/002/9343/front_en.115.400.jpg`,
      groupName: "Alimentación",
    },
    {
      slug: "despensa",
      name: "Despensa",
      imageUrl: `${IMG}/841/083/000/1016/front_en.48.400.jpg`,
      groupName: "Alimentación",
    },
    {
      slug: "aceites-conservas",
      name: "Aceites y Conservas",
      imageUrl: `${IMG}/841/001/026/0042/front_es.88.400.jpg`,
      groupName: "Alimentación",
    },
    {
      slug: "congelados-platos",
      name: "Congelados y Platos Preparados",
      imageUrl: `${IMG}/841/076/222/0059/front_en.35.400.jpg`,
      groupName: "Alimentación",
    },
    {
      slug: "dulces-snacks",
      name: "Dulces y Snacks",
      imageUrl: `${IMG}/841/010/900/3222/front_es.36.400.jpg`,
      groupName: "Snacks y Bebidas",
    },
    {
      slug: "bebidas",
      name: "Bebidas y Aguas",
      imageUrl: `${IMG}/841/005/515/0018/front_de.76.400.jpg`,
      groupName: "Snacks y Bebidas",
    },
    {
      slug: "cafe-infusiones",
      name: "Café e Infusiones",
      imageUrl: `${IMG}/841/009/117/0049/front_es.19.400.jpg`,
      groupName: "Snacks y Bebidas",
    },
    {
      slug: "hogar-limpieza",
      name: "Hogar y Limpieza",
      imageUrl: "",
      groupName: "Hogar",
    },
  ],

  brands: [
    { slug: "central-lechera-asturiana", name: "Central Lechera Asturiana", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://centrallecheraasturiana.es&size=128" },
    { slug: "pascual", name: "Pascual", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Pascual&size=128&fontWeight=600" },
    { slug: "puleva", name: "Puleva", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Puleva&size=128&fontWeight=600" },
    { slug: "garcia-baquero", name: "García Baquero", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Garcia%20Baquero&size=128&fontWeight=600" },
    { slug: "el-caserio", name: "El Caserío", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=El%20Caserio&size=128&fontWeight=600" },
    { slug: "philadelphia", name: "Philadelphia", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Philadelphia&size=128&fontWeight=600" },
    { slug: "danone", name: "Danone", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://danone.es&size=128" },
    { slug: "tulipan", name: "Tulipán", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Tulipan&size=128&fontWeight=600" },
    { slug: "huevos-guillen", name: "Huevos Guillén", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Huevos%20Guillen&size=128&fontWeight=600" },
    { slug: "bimbo", name: "Bimbo", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://bimbo.es&size=128" },
    { slug: "panrico", name: "Panrico", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Panrico&size=128&fontWeight=600" },
    { slug: "donuts", name: "Donuts", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Donuts&size=128&fontWeight=600" },
    { slug: "bollycao", name: "Bollycao", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Bollycao&size=128&fontWeight=600" },
    { slug: "fontaneda", name: "Fontaneda", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Fontaneda&size=128&fontWeight=600" },
    { slug: "gullon", name: "Gullón", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://gullon.es&size=128" },
    { slug: "artiach", name: "Artiach", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Artiach&size=128&fontWeight=600" },
    { slug: "cuetara", name: "Cuétara", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://cuetara.es&size=128" },
    { slug: "nestle", name: "Nestlé", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://nestle.es&size=128" },
    { slug: "nocilla", name: "Nocilla", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Nocilla&size=128&fontWeight=600" },
    { slug: "colacao", name: "ColaCao", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://colacao.es&size=128" },
    { slug: "hero", name: "Hero", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://hero.es&size=128" },
    { slug: "gallo", name: "Gallo", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://pastasgallo.es&size=128" },
    { slug: "sos", name: "SOS", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=SOS&size=128&fontWeight=600" },
    { slug: "brillante", name: "Brillante", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Brillante&size=128&fontWeight=600" },
    { slug: "gallina-blanca", name: "Gallina Blanca", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Gallina%20Blanca&size=128&fontWeight=600" },
    { slug: "litoral", name: "Litoral", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Litoral&size=128&fontWeight=600" },
    { slug: "solis", name: "Solís", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Solis&size=128&fontWeight=600" },
    { slug: "orlando", name: "Orlando", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Orlando&size=128&fontWeight=600" },
    { slug: "carbonell", name: "Carbonell", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Carbonell&size=128&fontWeight=600" },
    { slug: "coosur", name: "Coosur", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://coosur.com&size=128" },
    { slug: "la-espanola", name: "La Española", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=La%20Espanola&size=128&fontWeight=600" },
    { slug: "borges", name: "Borges", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://borges.es&size=128" },
    { slug: "hojiblanca", name: "Hojiblanca", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Hojiblanca&size=128&fontWeight=600" },
    { slug: "ligeresa", name: "Ligeresa", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Ligeresa&size=128&fontWeight=600" },
    { slug: "calvo", name: "Calvo", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://calvo.es&size=128" },
    { slug: "isabel", name: "Isabel", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Isabel&size=128&fontWeight=600" },
    { slug: "jolca", name: "Jolca", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Jolca&size=128&fontWeight=600" },
    { slug: "cidacos", name: "Cidacos", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Cidacos&size=128&fontWeight=600" },
    { slug: "el-navarrico", name: "El Navarrico", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=El%20Navarrico&size=128&fontWeight=600" },
    { slug: "campofrio", name: "Campofrío", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://campofrio.es&size=128" },
    { slug: "casa-tarradellas", name: "Casa Tarradellas", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Casa%20Tarradellas&size=128&fontWeight=600" },
    { slug: "palacios", name: "Palacios", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Palacios&size=128&fontWeight=600" },
    { slug: "revilla", name: "Revilla", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Revilla&size=128&fontWeight=600" },
    { slug: "valor", name: "Valor", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://valor.es&size=128" },
    { slug: "milka", name: "Milka", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Milka&size=128&fontWeight=600" },
    { slug: "lindt", name: "Lindt", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://lindt.es&size=128" },
    { slug: "oreo", name: "Oreo", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Oreo&size=128&fontWeight=600" },
    { slug: "nutella", name: "Nutella", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://nutella.com&size=128" },
    { slug: "chupa-chups", name: "Chupa Chups", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Chupa%20Chups&size=128&fontWeight=600" },
    { slug: "haribo", name: "Haribo", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://haribo.com&size=128" },
    { slug: "damel", name: "Damel", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Damel&size=128&fontWeight=600" },
    { slug: "ruffles", name: "Ruffles", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Ruffles&size=128&fontWeight=600" },
    { slug: "grefusa", name: "Grefusa", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://grefusa.com&size=128" },
    { slug: "el-almendro", name: "El Almendro", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=El%20Almendro&size=128&fontWeight=600" },
    { slug: "bicentury", name: "Bicentury", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Bicentury&size=128&fontWeight=600" },
    { slug: "font-vella", name: "Font Vella", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Font%20Vella&size=128&fontWeight=600" },
    { slug: "bezoya", name: "Bezoya", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Bezoya&size=128&fontWeight=600" },
    { slug: "lanjaron", name: "Lanjarón", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Lanjaron&size=128&fontWeight=600" },
    { slug: "solan-de-cabras", name: "Solán de Cabras", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Solan%20de%20Cabras&size=128&fontWeight=600" },
    { slug: "vichy-catalan", name: "Vichy Catalán", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Vichy%20Catalan&size=128&fontWeight=600" },
    { slug: "aquarius", name: "Aquarius", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Aquarius&size=128&fontWeight=600" },
    { slug: "coca-cola", name: "Coca-Cola", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://coca-cola.es&size=128" },
    { slug: "fanta", name: "Fanta", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Fanta&size=128&fontWeight=600" },
    { slug: "don-simon", name: "Don Simón", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Don%20Simon&size=128&fontWeight=600" },
    { slug: "marcilla", name: "Marcilla", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Marcilla&size=128&fontWeight=600" },
    { slug: "saimaza", name: "Saimaza", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Saimaza&size=128&fontWeight=600" },
    { slug: "bonka", name: "Bonka", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Bonka&size=128&fontWeight=600" },
    { slug: "nescafe", name: "Nescafé", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://nescafe.com&size=128" },
    { slug: "hornimans", name: "Hornimans", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Hornimans&size=128&fontWeight=600" },
    { slug: "pompadour", name: "Pompadour", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Pompadour&size=128&fontWeight=600" },
  ],

  products: [
    {
      slug: "platanos",
      name: "Plátanos",
      imageUrl: "",
      price: 1.75,
      unitValue: 1000,
      unitType: "g",
      description:
        "Plátanos de Canarias, dulces y en su punto.",
      stock: 130,
      categorySlugs: ["frutas-verduras"],
      isPopular: true,
    },
    {
      slug: "naranjas",
      name: "Naranjas de zumo",
      imageUrl: "",
      price: 1.95,
      unitValue: 2000,
      unitType: "g",
      description:
        "Naranjas de zumo valencianas, jugosas y de temporada.",
      stock: 120,
      categorySlugs: ["frutas-verduras"],
      isPopular: true,
    },
    {
      slug: "tomates",
      name: "Tomates de rama",
      imageUrl: "",
      price: 2.45,
      originalPrice: 2.85,
      unitValue: 1000,
      unitType: "g",
      description:
        "Tomates de rama madurados al sol, ideales para ensalada.",
      stock: 95,
      categorySlugs: ["frutas-verduras"],
      isPopular: true,
    },
    {
      slug: "pimientos",
      name: "Pimientos tricolor",
      imageUrl: "",
      price: 2.65,
      unitValue: 500,
      unitType: "g",
      description:
        "Pimientos rojo, verde y amarillo, carnosos y dulces.",
      stock: 80,
      categorySlugs: ["frutas-verduras"],
    },
    {
      slug: "cebollas",
      name: "Cebollas",
      imageUrl: "",
      price: 1.15,
      unitValue: 1000,
      unitType: "g",
      description:
        "Cebollas de grano suave, la base de todo sofrito.",
      stock: 110,
      categorySlugs: ["frutas-verduras"],
    },
    {
      slug: "patatas",
      name: "Patatas",
      imageUrl: "",
      price: 1.95,
      unitValue: 2000,
      unitType: "g",
      description:
        "Patatas para cocer o freír, calibre mediano.",
      stock: 105,
      categorySlugs: ["frutas-verduras"],
    },
    {
      slug: "calabacin",
      name: "Calabacín",
      imageUrl: "",
      price: 1.85,
      unitValue: 1000,
      unitType: "g",
      description:
        "Calabacines firmes, perfectos a la plancha o en crema.",
      stock: 85,
      categorySlugs: ["frutas-verduras"],
    },
    {
      slug: "lechuga",
      name: "Lechuga romana",
      imageUrl: "",
      price: 0.95,
      unitValue: 1,
      unitType: "pcs",
      description:
        "Lechuga romana crujiente, lavada y lista para usar.",
      stock: 90,
      categorySlugs: ["frutas-verduras"],
    },
    {
      slug: "manzanas",
      name: "Manzanas Fuji",
      imageUrl: "",
      price: 2.35,
      unitValue: 1000,
      unitType: "g",
      description:
        "Manzanas Fuji dulces y muy crujientes.",
      stock: 100,
      categorySlugs: ["frutas-verduras"],
    },
    {
      slug: "asturiana-leche-entera",
      name: "Central Lechera Asturiana Leche entera",
      imageUrl: `${IMG}/841/029/711/2041/front_en.95.400.jpg`,
      price: 1.15,
      unitValue: 1000,
      unitType: "ml",
      description:
        "Leche entera de vaca, de origen asturiano.",
      stock: 150,
      categorySlugs: ["lacteos-huevos"],
      brandSlug: "central-lechera-asturiana",
      sizeVariants: [
        { value: 1000, price: 1.15 },
        { value: 1500, price: 1.65 },
      ],
      isPopular: true,
    },
    {
      slug: "asturiana-semidesnatada",
      name: "Asturiana Leche semidesnatada",
      imageUrl: `${IMG}/841/029/701/2150/front_en.78.400.jpg`,
      price: 1.09,
      unitValue: 1000,
      unitType: "ml",
      description:
        "Leche semidesnatada, con la mitad de grasa y todo el sabor.",
      stock: 140,
      categorySlugs: ["lacteos-huevos"],
      brandSlug: "central-lechera-asturiana",
    },
    {
      slug: "pascual-leche-entera",
      name: "Pascual Leche entera",
      imageUrl: `${IMG}/841/012/801/0096/front_en.68.400.jpg`,
      price: 1.19,
      unitValue: 1000,
      unitType: "ml",
      description:
        "Leche entera Pascual, de granjas seleccionadas.",
      stock: 130,
      categorySlugs: ["lacteos-huevos"],
      brandSlug: "pascual",
    },
    {
      slug: "puleva-omega3",
      name: "Puleva Omega 3",
      imageUrl: `${IMG}/841/170/001/1111/front_es.88.400.jpg`,
      price: 1.65,
      unitValue: 1000,
      unitType: "ml",
      description:
        "Leche enriquecida con Omega 3, para el cuidado del corazón.",
      stock: 90,
      categorySlugs: ["lacteos-huevos"],
      brandSlug: "puleva",
    },
    {
      slug: "asturiana-mantequilla",
      name: "Asturiana Mantequilla",
      imageUrl: `${IMG}/841/029/713/2209/front_en.79.400.jpg`,
      price: 2.45,
      originalPrice: 2.85,
      unitValue: 250,
      unitType: "g",
      description:
        "Mantequilla tradicional elaborada con nata de leche asturiana.",
      stock: 85,
      categorySlugs: ["lacteos-huevos"],
      brandSlug: "central-lechera-asturiana",
      isPopular: true,
    },
    {
      slug: "tulipan-mantequilla",
      name: "Tulipán Mantequilla",
      imageUrl: `${IMG}/871/920/026/5806/front_es.39.400.jpg`,
      price: 2.85,
      unitValue: 400,
      unitType: "g",
      description:
        "Mantequilla untable, blanda recién salida de la nevera.",
      stock: 75,
      categorySlugs: ["lacteos-huevos"],
      brandSlug: "tulipan",
    },
    {
      slug: "garcia-baquero-semicurado",
      name: "García Baquero Queso semicurado en lonchas",
      imageUrl: `${IMG}/841/228/900/0879/front_en.33.400.jpg`,
      price: 3.25,
      unitValue: 200,
      unitType: "g",
      description:
        "Queso semicurado en lonchas, de mezcla de leches.",
      stock: 80,
      categorySlugs: ["lacteos-huevos"],
      brandSlug: "garcia-baquero",
      isPopular: true,
    },
    {
      slug: "garcia-baquero-cabra",
      name: "García Baquero Queso de cabra",
      imageUrl: `${IMG}/841/228/900/0930/front_en.32.400.jpg`,
      price: 2.75,
      unitValue: 125,
      unitType: "g",
      description:
        "Rulo de queso de cabra, suave y cremoso.",
      stock: 65,
      categorySlugs: ["lacteos-huevos"],
      brandSlug: "garcia-baquero",
    },
    {
      slug: "el-caserio-fundido",
      name: "El Caserío Queso fundido",
      imageUrl: `${IMG}/841/162/000/1155/front_es.25.400.jpg`,
      price: 2.35,
      unitValue: 16,
      unitType: "pcs",
      description:
        "Dieciséis porciones de queso fundido, el de toda la vida.",
      stock: 95,
      categorySlugs: ["lacteos-huevos"],
      brandSlug: "el-caserio",
    },
    {
      slug: "philadelphia-light",
      name: "Philadelphia Light",
      imageUrl: `${IMG}/762/221/010/3338/front_en.76.400.jpg`,
      price: 2.65,
      unitValue: 200,
      unitType: "g",
      description:
        "Crema de queso natural light para untar.",
      stock: 85,
      categorySlugs: ["lacteos-huevos"],
      brandSlug: "philadelphia",
    },
    {
      slug: "danone-yogur-natural",
      name: "Danone Yogur natural",
      imageUrl: `${IMG}/841/050/000/6082/front_en.74.400.jpg`,
      price: 2.45,
      unitValue: 500,
      unitType: "g",
      description:
        "Doce yogures naturales, elaborados con leche fresca.",
      stock: 110,
      categorySlugs: ["lacteos-huevos"],
      brandSlug: "danone",
      isPopular: true,
    },
    {
      slug: "danone-proteinas",
      name: "Danone Yogur +Proteínas",
      imageUrl: `${IMG}/841/050/002/9098/front_en.3.400.jpg`,
      price: 2.29,
      unitValue: 400,
      unitType: "g",
      description:
        "Yogur natural con proteínas añadidas, sin azúcares.",
      stock: 80,
      categorySlugs: ["lacteos-huevos"],
      brandSlug: "danone",
    },
    {
      slug: "huevos-camperos",
      name: "Huevos Guillén camperos",
      imageUrl: `${IMG}/841/138/400/3990/front_es.24.400.jpg`,
      price: 3.45,
      unitValue: 12,
      unitType: "pcs",
      description:
        "Docena de huevos de gallinas camperas, categoría M.",
      stock: 100,
      categorySlugs: ["lacteos-huevos"],
      brandSlug: "huevos-guillen",
      isPopular: true,
    },
    {
      slug: "barra-de-pan",
      name: "Barra de pan",
      imageUrl: "",
      price: 0.95,
      unitValue: 1,
      unitType: "pcs",
      description:
        "Barra de pan recién horneada, con corteza crujiente.",
      stock: 140,
      categorySlugs: ["panaderia-desayuno"],
      isPopular: true,
    },
    {
      slug: "bimbo-pan-integral",
      name: "Bimbo Pan integral 100 % natural",
      imageUrl: `${IMG}/841/260/002/9343/front_en.115.400.jpg`,
      price: 1.95,
      unitValue: 450,
      unitType: "g",
      description:
        "Pan de molde integral, sin azúcares añadidos.",
      stock: 105,
      categorySlugs: ["panaderia-desayuno"],
      brandSlug: "bimbo",
      isPopular: true,
    },
    {
      slug: "panrico-integral",
      name: "Panrico Integral 0 % azúcares",
      imageUrl: `${IMG}/843/453/250/6624/front_es.26.400.jpg`,
      price: 2.15,
      unitValue: 385,
      unitType: "g",
      description:
        "Pan de molde integral sin azúcares añadidos.",
      stock: 85,
      categorySlugs: ["panaderia-desayuno"],
      brandSlug: "panrico",
    },
    {
      slug: "donuts-glace",
      name: "Donuts Glacé",
      imageUrl: `${IMG}/841/002/200/0278/front_es.144.400.jpg`,
      price: 1.85,
      unitValue: 104,
      unitType: "g",
      description:
        "Los Donuts glaseados de siempre, en pack de cuatro.",
      stock: 90,
      categorySlugs: ["panaderia-desayuno"],
      brandSlug: "donuts",
    },
    {
      slug: "bollycao",
      name: "Bollycao",
      imageUrl: `${IMG}/841/002/204/0229/front_es.17.400.jpg`,
      price: 1.95,
      unitValue: 4,
      unitType: "pcs",
      description:
        "Cuatro bollos rellenos de crema de cacao.",
      stock: 85,
      categorySlugs: ["panaderia-desayuno"],
      brandSlug: "bollycao",
    },
    {
      slug: "fontaneda-maria",
      name: "Fontaneda La Buena María",
      imageUrl: `${IMG}/841/000/082/6937/front_es.34.400.jpg`,
      price: 2.15,
      unitValue: 800,
      unitType: "g",
      description:
        "Galletas María originales, para mojar en la leche.",
      stock: 100,
      categorySlugs: ["panaderia-desayuno"],
      brandSlug: "fontaneda",
      isPopular: true,
    },
    {
      slug: "gullon-digestive-avena",
      name: "Gullón Digestive Avena y Chocolate",
      imageUrl: `${IMG}/841/037/602/6962/front_en.138.400.jpg`,
      price: 2.35,
      unitValue: 425,
      unitType: "g",
      description:
        "Galletas digestive de avena bañadas en chocolate.",
      stock: 90,
      categorySlugs: ["panaderia-desayuno"],
      brandSlug: "gullon",
    },
    {
      slug: "artiach-dinosaurus",
      name: "Artiach Dinosaurus",
      imageUrl: `${IMG}/841/018/022/5087/front_fr.37.400.jpg`,
      price: 2.45,
      unitValue: 411,
      unitType: "g",
      description:
        "Las galletas Dinosaurus con chocolate con leche.",
      stock: 95,
      categorySlugs: ["panaderia-desayuno"],
      brandSlug: "artiach",
    },
    {
      slug: "cuetara-tostarica",
      name: "Cuétara TostaRica",
      imageUrl: `${IMG}/843/416/548/3965/front_en.36.400.jpg`,
      price: 2.25,
      unitValue: 570,
      unitType: "g",
      description:
        "Galletas TostaRica, el desayuno de toda la familia.",
      stock: 100,
      categorySlugs: ["panaderia-desayuno"],
      brandSlug: "cuetara",
    },
    {
      slug: "nestle-chocapic",
      name: "Nestlé Chocapic",
      imageUrl: `${IMG}/761/303/494/7611/front_fr.231.400.jpg`,
      price: 4.15,
      originalPrice: 4.79,
      unitValue: 750,
      unitType: "g",
      description:
        "Cereales de trigo y arroz con cacao, con fibra.",
      stock: 75,
      categorySlugs: ["panaderia-desayuno"],
      brandSlug: "nestle",
    },
    {
      slug: "nesquik-cereales",
      name: "Nesquik Cereales",
      imageUrl: `${IMG}/761/303/514/4699/front_fr.189.400.jpg`,
      price: 3.45,
      unitValue: 450,
      unitType: "g",
      description:
        "Cereales rellenos con sabor a cacao Nesquik.",
      stock: 80,
      categorySlugs: ["panaderia-desayuno"],
      brandSlug: "nestle",
    },
    {
      slug: "nocilla-original",
      name: "Nocilla Original",
      imageUrl: `${IMG}/841/001/447/7743/front_en.51.400.jpg`,
      price: 3.25,
      unitValue: 360,
      unitType: "g",
      description:
        "Crema de cacao con avellanas, para untar.",
      stock: 95,
      categorySlugs: ["panaderia-desayuno"],
      brandSlug: "nocilla",
      isPopular: true,
    },
    {
      slug: "colacao-original",
      name: "ColaCao Original",
      imageUrl: `${IMG}/841/001/447/8764/front_en.24.400.jpg`,
      price: 5.95,
      originalPrice: 6.49,
      unitValue: 760,
      unitType: "g",
      description:
        "El cacao soluble de siempre, con grumitos.",
      stock: 85,
      categorySlugs: ["panaderia-desayuno"],
      brandSlug: "colacao",
      isPopular: true,
    },
    {
      slug: "hero-mermelada-fresa",
      name: "Hero Mermelada de fresa",
      imageUrl: `${IMG}/841/017/506/9399/front_es.165.400.jpg`,
      price: 2.15,
      unitValue: 330,
      unitType: "g",
      description:
        "Mermelada de fresa Hero, con fruta seleccionada.",
      stock: 90,
      categorySlugs: ["panaderia-desayuno"],
      brandSlug: "hero",
    },
    {
      slug: "sos-arroz",
      name: "SOS Arroz redondo",
      imageUrl: `${IMG}/841/083/000/1016/front_en.48.400.jpg`,
      price: 1.85,
      unitValue: 1000,
      unitType: "g",
      description:
        "Arroz redondo para paellas y arroces caldosos.",
      stock: 130,
      categorySlugs: ["despensa"],
      brandSlug: "sos",
      isPopular: true,
    },
    {
      slug: "brillante-basmati",
      name: "Brillante Arroz Basmati",
      imageUrl: `${IMG}/841/018/480/0068/front_es.72.400.jpg`,
      price: 2.15,
      unitValue: 250,
      unitType: "g",
      description:
        "Arroz basmati en vasitos, listo en dos minutos.",
      stock: 90,
      categorySlugs: ["despensa"],
      brandSlug: "brillante",
    },
    {
      slug: "gallo-pasta-lenteja",
      name: "Gallo Pasta de lenteja",
      imageUrl: `${IMG}/841/006/901/9028/front_es.71.400.jpg`,
      price: 2.85,
      unitValue: 1000,
      unitType: "g",
      description:
        "Pasta elaborada con harina de lenteja, rica en proteína.",
      stock: 70,
      categorySlugs: ["despensa"],
      brandSlug: "gallo",
    },
    {
      slug: "gallina-blanca-yatekomo",
      name: "Gallina Blanca Yatekomo Pollo",
      imageUrl: `${IMG}/841/030/034/9952/front_en.78.400.jpg`,
      price: 1.35,
      unitValue: 60,
      unitType: "g",
      description:
        "Fideos orientales sabor pollo, listos en tres minutos.",
      stock: 120,
      categorySlugs: ["despensa"],
      brandSlug: "gallina-blanca",
    },
    {
      slug: "avecrem-pollo",
      name: "Avecrem Caldo de pollo",
      imageUrl: `${IMG}/841/030/010/0010/front_es.44.400.jpg`,
      price: 2.25,
      unitValue: 24,
      unitType: "pcs",
      description:
        "Veinticuatro pastillas de caldo de pollo de corral.",
      stock: 110,
      categorySlugs: ["despensa"],
      brandSlug: "gallina-blanca",
      isPopular: true,
    },
    {
      slug: "solis-tomate-frito",
      name: "Solís Tomate frito",
      imageUrl: `${IMG}/841/300/006/4651/front_es.24.400.jpg`,
      price: 1.55,
      unitValue: 725,
      unitType: "g",
      description:
        "Tomate frito estilo casero, con aceite de oliva.",
      stock: 125,
      categorySlugs: ["despensa"],
      brandSlug: "solis",
      isPopular: true,
    },
    {
      slug: "orlando-tomate-frito",
      name: "Orlando Tomate frito",
      imageUrl: `${IMG}/841/006/600/0074/front_es.55.400.jpg`,
      price: 1.15,
      unitValue: 350,
      unitType: "g",
      description:
        "Tomate frito Orlando, para pastas y guisos.",
      stock: 115,
      categorySlugs: ["despensa"],
      brandSlug: "orlando",
    },
    {
      slug: "litoral-fabada",
      name: "Litoral Fabada Asturiana",
      imageUrl: `${IMG}/761/328/781/6825/front_en.32.400.jpg`,
      price: 3.25,
      unitValue: 420,
      unitType: "g",
      description:
        "Fabada asturiana con compango, lista en el microondas.",
      stock: 75,
      categorySlugs: ["despensa"],
      brandSlug: "litoral",
    },
    {
      slug: "litoral-lentejas",
      name: "Litoral Lentejas a la Riojana",
      imageUrl: `${IMG}/841/300/006/5764/front_en.33.400.jpg`,
      price: 2.25,
      unitValue: 425,
      unitType: "g",
      description:
        "Lentejas a la riojana con chorizo, plato único.",
      stock: 80,
      categorySlugs: ["despensa"],
      brandSlug: "litoral",
    },
    {
      slug: "azucar-blanco",
      name: "Azúcar blanco",
      imageUrl: "",
      price: 1.25,
      unitValue: 1000,
      unitType: "g",
      description:
        "Azúcar blanco de remolacha, grano fino.",
      stock: 120,
      categorySlugs: ["despensa"],
    },
    {
      slug: "harina-de-trigo",
      name: "Harina de trigo",
      imageUrl: "",
      price: 0.85,
      unitValue: 1000,
      unitType: "g",
      description:
        "Harina de trigo de todo uso, para repostería y rebozados.",
      stock: 115,
      categorySlugs: ["despensa"],
    },
    {
      slug: "carbonell-aove",
      name: "Carbonell Aceite de oliva virgen extra",
      imageUrl: `${IMG}/841/001/026/0042/front_es.88.400.jpg`,
      price: 8.95,
      originalPrice: 9.95,
      unitValue: 1000,
      unitType: "ml",
      description:
        "Aceite de oliva virgen extra, sabor intenso y afrutado.",
      stock: 70,
      categorySlugs: ["aceites-conservas"],
      brandSlug: "carbonell",
      isPopular: true,
    },
    {
      slug: "coosur-aove",
      name: "Coosur Aceite de oliva virgen extra",
      imageUrl: `${IMG}/841/119/010/1392/front_es.35.400.jpg`,
      price: 8.45,
      unitValue: 1000,
      unitType: "ml",
      description:
        "Virgen extra de aceituna picual, para crudo y cocina.",
      stock: 65,
      categorySlugs: ["aceites-conservas"],
      brandSlug: "coosur",
    },
    {
      slug: "la-espanola-aove",
      name: "La Española Aceite de oliva virgen extra",
      imageUrl: `${IMG}/841/066/004/9769/front_en.20.400.jpg`,
      price: 8.75,
      unitValue: 1000,
      unitType: "ml",
      description:
        "Virgen extra de recolección temprana.",
      stock: 60,
      categorySlugs: ["aceites-conservas"],
      brandSlug: "la-espanola",
    },
    {
      slug: "borges-arbequina",
      name: "Borges Aceite Arbequina",
      imageUrl: `${IMG}/841/017/910/0340/front_es.25.400.jpg`,
      price: 9.45,
      unitValue: 500,
      unitType: "ml",
      description:
        "Virgen extra de aceituna arbequina, suave y delicado.",
      stock: 55,
      categorySlugs: ["aceites-conservas"],
      brandSlug: "borges",
    },
    {
      slug: "hojiblanca-aove",
      name: "Hojiblanca Aceite de oliva virgen extra",
      imageUrl: `${IMG}/842/276/712/3167/front_es.37.400.jpg`,
      price: 7.95,
      unitValue: 1000,
      unitType: "ml",
      description:
        "Virgen extra de variedad hojiblanca, con notas de almendra.",
      stock: 60,
      categorySlugs: ["aceites-conservas"],
      brandSlug: "hojiblanca",
    },
    {
      slug: "ligeresa",
      name: "Ligeresa Original",
      imageUrl: `${IMG}/872/270/013/6224/front_en.100.400.jpg`,
      price: 2.35,
      unitValue: 430,
      unitType: "ml",
      description:
        "Salsa fina para ensaladas, más ligera que la mayonesa.",
      stock: 85,
      categorySlugs: ["aceites-conservas"],
      brandSlug: "ligeresa",
    },
    {
      slug: "calvo-atun-oliva",
      name: "Calvo Atún claro en aceite de oliva",
      imageUrl: `${IMG}/841/009/005/1219/front_es.38.400.jpg`,
      price: 2.95,
      unitValue: 195,
      unitType: "g",
      description:
        "Atún claro en aceite de oliva, pesca responsable.",
      stock: 105,
      categorySlugs: ["aceites-conservas"],
      brandSlug: "calvo",
      isPopular: true,
    },
    {
      slug: "calvo-sardinas",
      name: "Calvo Sardinas en aceite de oliva",
      imageUrl: `${IMG}/841/009/044/1270/front_es.20.400.jpg`,
      price: 2.45,
      unitValue: 120,
      unitType: "g",
      description:
        "Sardinas en aceite de oliva, listas para la tostada.",
      stock: 90,
      categorySlugs: ["aceites-conservas"],
      brandSlug: "calvo",
    },
    {
      slug: "isabel-atun",
      name: "Isabel Atún claro",
      imageUrl: `${IMG}/841/011/121/1202/front_es.46.400.jpg`,
      price: 3.45,
      unitValue: 240,
      unitType: "g",
      description:
        "Atún claro Isabel en pack de tres latas.",
      stock: 95,
      categorySlugs: ["aceites-conservas"],
      brandSlug: "isabel",
    },
    {
      slug: "jolca-aceitunas",
      name: "Jolca Aceituna manzanilla sin hueso",
      imageUrl: `${IMG}/841/066/700/1104/front_es.27.400.jpg`,
      price: 1.35,
      unitValue: 180,
      unitType: "g",
      description:
        "Aceituna manzanilla fina sin hueso, para el aperitivo.",
      stock: 120,
      categorySlugs: ["aceites-conservas"],
      brandSlug: "jolca",
    },
    {
      slug: "cidacos-garbanzos",
      name: "Cidacos Garbanzos extra",
      imageUrl: `${IMG}/841/031/332/5813/front_en.46.400.jpg`,
      price: 1.45,
      unitValue: 570,
      unitType: "g",
      description:
        "Garbanzos cocidos extra, listos para el cocido.",
      stock: 110,
      categorySlugs: ["aceites-conservas"],
      brandSlug: "cidacos",
    },
    {
      slug: "navarrico-garbanzos",
      name: "El Navarrico Garbanzos al natural",
      imageUrl: `${IMG}/841/323/906/0035/front_es.12.400.jpg`,
      price: 2.95,
      unitValue: 700,
      unitType: "g",
      description:
        "Garbanzos al natural de calidad extra, en tarro de cristal.",
      stock: 60,
      categorySlugs: ["aceites-conservas"],
      brandSlug: "el-navarrico",
    },
    {
      slug: "sal-marina",
      name: "Sal marina fina",
      imageUrl: "",
      price: 0.85,
      unitValue: 1000,
      unitType: "g",
      description:
        "Sal marina fina obtenida por evaporación natural.",
      stock: 130,
      categorySlugs: ["aceites-conservas"],
    },
    {
      slug: "vinagre-de-jerez",
      name: "Vinagre de Jerez",
      imageUrl: "",
      price: 1.75,
      unitValue: 500,
      unitType: "ml",
      description:
        "Vinagre de Jerez con Denominación de Origen, para aliños.",
      stock: 85,
      categorySlugs: ["aceites-conservas"],
    },
    {
      slug: "tarradellas-pizza",
      name: "Casa Tarradellas Pizza jamón y queso",
      imageUrl: `${IMG}/841/076/222/0059/front_en.35.400.jpg`,
      price: 3.95,
      originalPrice: 4.49,
      unitValue: 405,
      unitType: "g",
      description:
        "Pizza fresca de jamón y queso, masa fina.",
      stock: 75,
      categorySlugs: ["congelados-platos"],
      brandSlug: "casa-tarradellas",
      isPopular: true,
    },
    {
      slug: "campofrio-pizza-5-quesos",
      name: "Campofrío Pizza 5 quesos",
      imageUrl: `${IMG}/841/032/003/3527/front_es.38.400.jpg`,
      price: 3.45,
      unitValue: 360,
      unitType: "g",
      description:
        "Pizza con salsa y cinco quesos, al horno en 12 minutos.",
      stock: 70,
      categorySlugs: ["congelados-platos"],
      brandSlug: "campofrio",
    },
    {
      slug: "campofrio-pizza-barbacoa",
      name: "Campofrío Pizza barbacoa",
      imageUrl: `${IMG}/841/032/003/4319/front_es.44.400.jpg`,
      price: 3.65,
      unitValue: 410,
      unitType: "g",
      description:
        "Pizza con salsa barbacoa y bacon.",
      stock: 65,
      categorySlugs: ["congelados-platos"],
      brandSlug: "campofrio",
    },
    {
      slug: "tarradellas-jamon-cocido",
      name: "Casa Tarradellas Jamón cocido extra",
      imageUrl: `${IMG}/841/076/221/0456/front_en.6.400.jpg`,
      price: 2.85,
      unitValue: 12,
      unitType: "pcs",
      description:
        "Lonchas de jamón cocido extra, sin gluten.",
      stock: 90,
      categorySlugs: ["congelados-platos"],
      brandSlug: "casa-tarradellas",
      isPopular: true,
    },
    {
      slug: "palacios-chorizo",
      name: "Palacios Chorizo dulce",
      imageUrl: `${IMG}/842/087/800/0025/front_es.29.400.jpg`,
      price: 3.15,
      unitValue: 1,
      unitType: "pcs",
      description:
        "Chorizo dulce de sarta, curado al natural.",
      stock: 80,
      categorySlugs: ["congelados-platos"],
      brandSlug: "palacios",
    },
    {
      slug: "revilla-chorizo",
      name: "Revilla Chorizo",
      imageUrl: `${IMG}/841/032/003/5620/front_en.28.400.jpg`,
      price: 1.45,
      unitValue: 65,
      unitType: "g",
      description:
        "Chorizo en lonchas, listo para bocadillo.",
      stock: 100,
      categorySlugs: ["congelados-platos"],
      brandSlug: "revilla",
    },
    {
      slug: "guisantes-congelados",
      name: "Guisantes congelados",
      imageUrl: "",
      price: 1.35,
      unitValue: 750,
      unitType: "g",
      description:
        "Guisantes muy finos congelados justo tras la cosecha.",
      stock: 95,
      categorySlugs: ["congelados-platos"],
    },
    {
      slug: "patatas-fritas-horno",
      name: "Patatas para horno",
      imageUrl: "",
      price: 2.25,
      unitValue: 1000,
      unitType: "g",
      description:
        "Patatas prefritas para horno, sin freidora.",
      stock: 100,
      categorySlugs: ["congelados-platos"],
    },
    {
      slug: "espinacas-congeladas",
      name: "Espinacas congeladas",
      imageUrl: "",
      price: 1.45,
      unitValue: 450,
      unitType: "g",
      description:
        "Espinacas troceadas en porciones, congeladas.",
      stock: 90,
      categorySlugs: ["congelados-platos"],
    },
    {
      slug: "valor-negro-70",
      name: "Valor Chocolate negro 70 %",
      imageUrl: `${IMG}/841/010/900/3222/front_es.36.400.jpg`,
      price: 2.15,
      unitValue: 125,
      unitType: "g",
      description:
        "Chocolate negro 70 % sin azúcares añadidos.",
      stock: 95,
      categorySlugs: ["dulces-snacks"],
      brandSlug: "valor",
      isPopular: true,
    },
    {
      slug: "milka-choco-pause",
      name: "Milka Choco Pause",
      imageUrl: `${IMG}/762/221/010/0917/front_en.114.400.jpg`,
      price: 2.45,
      unitValue: 260,
      unitType: "g",
      description:
        "Galletas con chocolate Milka, en formato familiar.",
      stock: 90,
      categorySlugs: ["dulces-snacks"],
      brandSlug: "milka",
    },
    {
      slug: "lindt-negro-70",
      name: "Lindt Excellence Negro 70 %",
      imageUrl: `${IMG}/304/692/002/2651/front_en.159.400.jpg`,
      price: 2.35,
      unitValue: 100,
      unitType: "g",
      description:
        "Chocolate negro intenso con 70 % de cacao.",
      stock: 85,
      categorySlugs: ["dulces-snacks"],
      brandSlug: "lindt",
    },
    {
      slug: "oreo-os",
      name: "Oreo O's",
      imageUrl: `${IMG}/501/002/922/7062/front_en.163.400.jpg`,
      price: 3.75,
      unitValue: 350,
      unitType: "g",
      description:
        "Cereales con sabor a galleta Oreo.",
      stock: 70,
      categorySlugs: ["dulces-snacks"],
      brandSlug: "oreo",
    },
    {
      slug: "nutella-biscuits",
      name: "Nutella Biscuits",
      imageUrl: `${IMG}/800/050/031/0427/front_fr.550.400.jpg`,
      price: 2.99,
      unitValue: 304,
      unitType: "g",
      description:
        "Galletas crujientes con corazón de Nutella.",
      stock: 90,
      categorySlugs: ["dulces-snacks"],
      brandSlug: "nutella",
      isPopular: true,
    },
    {
      slug: "chupa-chups",
      name: "Chupa Chups surtido",
      imageUrl: `${IMG}/000/004/981/4521/front_en.29.400.jpg`,
      price: 0.35,
      unitValue: 12,
      unitType: "g",
      description:
        "El caramelo con palo de siempre, sabores surtidos.",
      stock: 200,
      categorySlugs: ["dulces-snacks"],
      brandSlug: "chupa-chups",
    },
    {
      slug: "haribo-roulette",
      name: "Haribo Roulette",
      imageUrl: `${IMG}/400/168/637/2586/front_en.157.400.jpg`,
      price: 0.85,
      unitValue: 45,
      unitType: "g",
      description:
        "Rollo de gominolas surtidas Haribo.",
      stock: 160,
      categorySlugs: ["dulces-snacks"],
      brandSlug: "haribo",
    },
    {
      slug: "damel-moras",
      name: "Damel Moras",
      imageUrl: `${IMG}/848/000/065/0771/front_es.57.400.jpg`,
      price: 1.55,
      unitValue: 200,
      unitType: "g",
      description:
        "Moras de gominola azucaradas, bolsa para compartir.",
      stock: 110,
      categorySlugs: ["dulces-snacks"],
      brandSlug: "damel",
    },
    {
      slug: "ruffles-jamon",
      name: "Ruffles sabor jamón",
      imageUrl: `${IMG}/841/019/902/3148/front_es.19.400.jpg`,
      price: 2.65,
      unitValue: 150,
      unitType: "g",
      description:
        "Patatas onduladas con sabor a jamón.",
      stock: 105,
      categorySlugs: ["dulces-snacks"],
      brandSlug: "ruffles",
      isPopular: true,
    },
    {
      slug: "grefusa-pipas",
      name: "Grefusa Pipas G con sal",
      imageUrl: `${IMG}/841/316/400/3848/front_es.40.400.jpg`,
      price: 1.85,
      unitValue: 165,
      unitType: "g",
      description:
        "Pipas de girasol tostadas con sal.",
      stock: 120,
      categorySlugs: ["dulces-snacks"],
      brandSlug: "grefusa",
    },
    {
      slug: "grefusa-natuchips",
      name: "Grefusa Natuchips",
      imageUrl: `${IMG}/841/316/402/0913/front_es.19.400.jpg`,
      price: 1.75,
      unitValue: 85,
      unitType: "g",
      description:
        "Chips de maíz horneados, sin fritura.",
      stock: 95,
      categorySlugs: ["dulces-snacks"],
      brandSlug: "grefusa",
    },
    {
      slug: "el-almendro-turron",
      name: "El Almendro Turrón blando",
      imageUrl: `${IMG}/841/022/390/1992/front_fr.37.400.jpg`,
      price: 4.95,
      originalPrice: 5.95,
      unitValue: 250,
      unitType: "g",
      description:
        "Turrón blando de almendra, calidad suprema.",
      stock: 60,
      categorySlugs: ["dulces-snacks"],
      brandSlug: "el-almendro",
      isPopular: true,
    },
    {
      slug: "el-almendro-barritas",
      name: "El Almendro Barritas de almendra",
      imageUrl: `${IMG}/841/022/390/7895/front_es.42.400.jpg`,
      price: 2.85,
      unitValue: 100,
      unitType: "g",
      description:
        "Barritas de almendra con chocolate 70 %.",
      stock: 75,
      categorySlugs: ["dulces-snacks"],
      brandSlug: "el-almendro",
    },
    {
      slug: "bicentury-tortitas",
      name: "Bicentury Mini Tortitas Jamón",
      imageUrl: `${IMG}/842/320/720/6792/front_es.43.400.jpg`,
      price: 2.35,
      unitValue: 70,
      unitType: "g",
      description:
        "Mini tortitas de maíz con sabor a jamón, ligeras.",
      stock: 85,
      categorySlugs: ["dulces-snacks"],
      brandSlug: "bicentury",
    },
    {
      slug: "font-vella",
      name: "Font Vella Agua mineral",
      imageUrl: `${IMG}/841/005/515/0018/front_de.76.400.jpg`,
      price: 0.75,
      unitValue: 1500,
      unitType: "ml",
      description:
        "Agua mineral natural de mineralización débil.",
      stock: 220,
      categorySlugs: ["bebidas"],
      brandSlug: "font-vella",
      sizeVariants: [
        { value: 1500, price: 0.75 },
        { value: 500, price: 0.45 },
      ],
      isPopular: true,
    },
    {
      slug: "bezoya",
      name: "Bezoya Agua mineral",
      imageUrl: `${IMG}/841/012/800/0400/front_en.98.400.jpg`,
      price: 0.85,
      unitValue: 1500,
      unitType: "ml",
      description:
        "Agua de mineralización muy débil, ligera al paladar.",
      stock: 180,
      categorySlugs: ["bebidas"],
      brandSlug: "bezoya",
    },
    {
      slug: "lanjaron",
      name: "Lanjarón Agua mineral",
      imageUrl: `${IMG}/841/072/818/0120/front_en.64.400.jpg`,
      price: 0.79,
      unitValue: 1500,
      unitType: "ml",
      description:
        "Agua mineral natural de Sierra Nevada.",
      stock: 175,
      categorySlugs: ["bebidas"],
      brandSlug: "lanjaron",
    },
    {
      slug: "solan-de-cabras",
      name: "Solán de Cabras Agua mineral",
      imageUrl: `${IMG}/841/154/700/1085/front_es.43.400.jpg`,
      price: 0.95,
      unitValue: 1500,
      unitType: "ml",
      description:
        "Agua mineral natural en su icónica botella azul.",
      stock: 165,
      categorySlugs: ["bebidas"],
      brandSlug: "solan-de-cabras",
      isPopular: true,
    },
    {
      slug: "vichy-catalan",
      name: "Vichy Catalán Agua con gas",
      imageUrl: `${IMG}/841/074/900/1107/front_en.62.400.jpg`,
      price: 1.15,
      unitValue: 1000,
      unitType: "ml",
      description:
        "Agua mineral natural con gas, mineralización fuerte.",
      stock: 130,
      categorySlugs: ["bebidas"],
      brandSlug: "vichy-catalan",
    },
    {
      slug: "aquarius-limon",
      name: "Aquarius Limón",
      imageUrl: `${IMG}/000/005/011/2784/front_en.145.400.jpg`,
      price: 1.25,
      unitValue: 500,
      unitType: "ml",
      description:
        "Bebida isotónica sabor limón, para reponer sales.",
      stock: 145,
      categorySlugs: ["bebidas"],
      brandSlug: "aquarius",
    },
    {
      slug: "coca-cola",
      name: "Coca-Cola",
      imageUrl: `${IMG}/544/900/021/4911/front_fr.335.400.jpg`,
      price: 0.95,
      unitValue: 330,
      unitType: "ml",
      description:
        "Coca-Cola en lata, mejor bien fría.",
      stock: 200,
      categorySlugs: ["bebidas"],
      brandSlug: "coca-cola",
      isPopular: true,
    },
    {
      slug: "fanta-limon",
      name: "Fanta Limón",
      imageUrl: `${IMG}/544/900/000/6004/front_en.181.400.jpg`,
      price: 0.95,
      unitValue: 330,
      unitType: "ml",
      description:
        "Fanta Limón en lata, con zumo de limón.",
      stock: 170,
      categorySlugs: ["bebidas"],
      brandSlug: "fanta",
    },
    {
      slug: "don-simon-naranja",
      name: "Don Simón Zumo de naranja",
      imageUrl: `${IMG}/841/026/160/8105/front_es.51.400.jpg`,
      price: 1.45,
      unitValue: 1000,
      unitType: "ml",
      description:
        "Zumo de naranja exprimida, sin azúcares añadidos.",
      stock: 120,
      categorySlugs: ["bebidas"],
      brandSlug: "don-simon",
      isPopular: true,
    },
    {
      slug: "pascual-bifrutas",
      name: "Pascual Bifrutas Tropical",
      imageUrl: `${IMG}/841/012/889/1169/front_en.115.400.jpg`,
      price: 1.15,
      unitValue: 330,
      unitType: "ml",
      description:
        "Bebida de leche y zumo tropical, con vitaminas.",
      stock: 110,
      categorySlugs: ["bebidas"],
      brandSlug: "pascual",
    },
    {
      slug: "puleva-batido-chocolate",
      name: "Puleva Batido de chocolate",
      imageUrl: `${IMG}/000/008/411/7205/front_en.46.400.jpg`,
      price: 0.85,
      unitValue: 200,
      unitType: "ml",
      description:
        "Batido de chocolate listo para llevar.",
      stock: 140,
      categorySlugs: ["bebidas"],
      brandSlug: "puleva",
    },
    {
      slug: "marcilla-gran-aroma",
      name: "Marcilla Gran Aroma natural",
      imageUrl: `${IMG}/841/009/117/0049/front_es.19.400.jpg`,
      price: 3.95,
      originalPrice: 4.49,
      unitValue: 250,
      unitType: "g",
      description:
        "Café molido natural de tueste equilibrado.",
      stock: 100,
      categorySlugs: ["cafe-infusiones"],
      brandSlug: "marcilla",
      isPopular: true,
    },
    {
      slug: "saimaza-molido",
      name: "Saimaza Café molido natural",
      imageUrl: `${IMG}/871/100/052/7474/front_es.25.400.jpg`,
      price: 3.75,
      unitValue: 250,
      unitType: "g",
      description:
        "Café molido natural, aroma intenso desde 1908.",
      stock: 90,
      categorySlugs: ["cafe-infusiones"],
      brandSlug: "saimaza",
    },
    {
      slug: "bonka-natural",
      name: "Bonka Café natural",
      imageUrl: `${IMG}/841/010/002/4011/front_es.5.400.jpg`,
      price: 6.45,
      unitValue: 500,
      unitType: "g",
      description:
        "Café natural en grano, tueste medio.",
      stock: 70,
      categorySlugs: ["cafe-infusiones"],
      brandSlug: "bonka",
    },
    {
      slug: "nescafe-classic",
      name: "Nescafé Classic",
      imageUrl: `${IMG}/400/550/000/5827/front_en.45.400.jpg`,
      price: 4.75,
      unitValue: 200,
      unitType: "g",
      description:
        "Café soluble Nescafé Classic, listo en un momento.",
      stock: 95,
      categorySlugs: ["cafe-infusiones"],
      brandSlug: "nescafe",
      isPopular: true,
    },
    {
      slug: "hornimans-manzanilla",
      name: "Hornimans Manzanilla",
      imageUrl: `${IMG}/841/009/110/3320/front_es.4.400.jpg`,
      price: 1.95,
      unitValue: 25,
      unitType: "pcs",
      description:
        "Veinticinco bolsitas de manzanilla, digestiva y suave.",
      stock: 110,
      categorySlugs: ["cafe-infusiones"],
      brandSlug: "hornimans",
    },
    {
      slug: "hornimans-te-slim",
      name: "Hornimans Té Slim",
      imageUrl: `${IMG}/841/009/110/4518/front_fr.25.400.jpg`,
      price: 2.25,
      unitValue: 20,
      unitType: "pcs",
      description:
        "Infusión de té verde con hierbas, sin azúcar.",
      stock: 85,
      categorySlugs: ["cafe-infusiones"],
      brandSlug: "hornimans",
    },
    {
      slug: "pompadour-jengibre",
      name: "Pompadour Infusión jengibre y limón",
      imageUrl: `${IMG}/841/290/040/1184/front_es.24.400.jpg`,
      price: 2.45,
      unitValue: 20,
      unitType: "pcs",
      description:
        "Infusión de jengibre con limón, reconfortante.",
      stock: 80,
      categorySlugs: ["cafe-infusiones"],
      brandSlug: "pompadour",
    },
    {
      slug: "capsulas-espresso",
      name: "Cápsulas espresso",
      imageUrl: "",
      price: 4.95,
      unitValue: 40,
      unitType: "pcs",
      description:
        "Cuarenta cápsulas compatibles de tueste espresso.",
      stock: 85,
      categorySlugs: ["cafe-infusiones"],
    },
    {
      slug: "lavavajillas-mano",
      name: "Lavavajillas a mano Limón",
      imageUrl: "",
      price: 1.25,
      unitValue: 750,
      unitType: "ml",
      description:
        "Lavavajillas concentrado con aroma a limón, alto poder desengrasante.",
      stock: 110,
      categorySlugs: ["hogar-limpieza"],
    },
    {
      slug: "limpiador-multiusos",
      name: "Limpiador multiusos",
      imageUrl: "",
      price: 1.75,
      unitValue: 1000,
      unitType: "ml",
      description:
        "Limpiador multiusos para todas las superficies lavables.",
      stock: 100,
      categorySlugs: ["hogar-limpieza"],
    },
    {
      slug: "papel-higienico",
      name: "Papel higiénico 3 capas",
      imageUrl: "",
      price: 4.25,
      originalPrice: 4.89,
      unitValue: 12,
      unitType: "pcs",
      description:
        "Doce rollos de tres capas, suaves y resistentes.",
      stock: 130,
      categorySlugs: ["hogar-limpieza"],
      isPopular: true,
    },
    {
      slug: "papel-de-cocina",
      name: "Papel de cocina",
      imageUrl: "",
      price: 2.55,
      unitValue: 4,
      unitType: "pcs",
      description:
        "Cuatro rollos de papel de cocina muy absorbentes.",
      stock: 115,
      categorySlugs: ["hogar-limpieza"],
    },
    {
      slug: "bolsas-de-basura",
      name: "Bolsas de basura 50 l",
      imageUrl: "",
      price: 2.25,
      unitValue: 20,
      unitType: "pcs",
      description:
        "Veinte bolsas resistentes con cierre de autocierre.",
      stock: 100,
      categorySlugs: ["hogar-limpieza"],
    },
    {
      slug: "detergente-liquido",
      name: "Detergente líquido",
      imageUrl: "",
      price: 12.95,
      originalPrice: 14.49,
      unitValue: 3000,
      unitType: "ml",
      description:
        "Detergente líquido para 60 lavados, eficaz desde 20 °C.",
      stock: 65,
      categorySlugs: ["hogar-limpieza"],
      isPopular: true,
    },
    {
      slug: "pastillas-lavavajillas",
      name: "Pastillas lavavajillas todo en uno",
      imageUrl: "",
      price: 13.75,
      unitValue: 60,
      unitType: "pcs",
      description:
        "Sesenta pastillas todo en uno con sal y abrillantador.",
      stock: 70,
      categorySlugs: ["hogar-limpieza"],
    },
    {
      slug: "pasta-de-dientes",
      name: "Pasta de dientes protección total",
      imageUrl: "",
      price: 2.15,
      unitValue: 75,
      unitType: "ml",
      description:
        "Pasta dentífrica con flúor para la protección diaria.",
      stock: 110,
      categorySlugs: ["hogar-limpieza"],
    },
  ],

  coupons: [
    {
      code: "BIENVENIDA10",
      type: "percent",
      value: 10,
      scope: "store",
      minOrderValue: 20,
      maxDiscount: 5,
      usageLimit: 500,
      perUserLimit: 1,
    },
    {
      code: "FRESCOS5",
      type: "percent",
      value: 5,
      scope: "category",
      targetCategorySlugs: ["frutas-verduras"],
      minOrderValue: 10,
      maxDiscount: 3,
      usageLimit: 300,
      perUserLimit: 2,
    },
    {
      code: "CAFE15",
      type: "percent",
      value: 15,
      scope: "category",
      targetCategorySlugs: ["cafe-infusiones"],
      minOrderValue: 15,
      maxDiscount: 5,
      usageLimit: 200,
      perUserLimit: 1,
    },
    {
      code: "DULCE2",
      type: "flat",
      value: 2,
      scope: "category",
      targetCategorySlugs: ["dulces-snacks"],
      minOrderValue: 12,
      maxDiscount: 2,
      usageLimit: 250,
      perUserLimit: 2,
    },
    {
      code: "HOGAR3",
      type: "flat",
      value: 3,
      scope: "category",
      targetCategorySlugs: ["hogar-limpieza"],
      minOrderValue: 25,
      maxDiscount: 3,
      usageLimit: 150,
      perUserLimit: 1,
    },
    {
      code: "PIZZA1",
      type: "flat",
      value: 1,
      scope: "product",
      targetProductSlugs: ["tarradellas-pizza", "campofrio-pizza-5-quesos", "campofrio-pizza-barbacoa"],
      minOrderValue: 6,
      maxDiscount: 1,
      usageLimit: 400,
      perUserLimit: 3,
    },
    {
      code: "ENVIOGRATIS",
      type: "flat",
      value: 4,
      scope: "store",
      minOrderValue: 40,
      maxDiscount: 4,
      usageLimit: 400,
      perUserLimit: 1,
    },
  ],

  banners: [
    {
      title: "Del mercado cada mañana",
      subtitle: "Frutas y verduras recién llegadas",
      imageUrl:
        "https://images.unsplash.com/photo-1542838132-92c53300491e?w=1200&q=80",
      targetCategorySlug: "frutas-verduras",
      sortOrder: 0,
      backgroundColor: "#1F6F4A",
    },
    {
      title: "La hora del café",
      subtitle: "Hasta un 15 % en café molido y cápsulas",
      imageUrl:
        "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=1200&q=80",
      targetCategorySlug: "cafe-infusiones",
      sortOrder: 1,
      backgroundColor: "#4A2C1A",
    },
    {
      title: "Antojo dulce",
      subtitle: "Chocolates y galletas en oferta",
      imageUrl:
        "https://images.unsplash.com/photo-1481391319762-47dff72954d9?w=1200&q=80",
      targetCategorySlug: "dulces-snacks",
      sortOrder: 2,
      backgroundColor: "#7A1F3D",
    },
    {
      title: "Llena la despensa",
      subtitle: "Arroz, pasta y conservas en formato familiar",
      imageUrl:
        "https://images.unsplash.com/photo-1556909212-d5b604d0c90d?w=1200&q=80",
      targetCategorySlug: "despensa",
      sortOrder: 3,
      backgroundColor: "#2A4C7A",
    },
  ],
};
