// The **United Kingdom** sample catalog — a realistic British supermarket
// (Tesco/Sainsbury's-style aisles, real UK brands, £ retail pricing).
//
// Unlike the four European catalogs this one needs no new language pack: its
// copy is English, which the storefront already speaks. Only the catalog side
// was outstanding for the UK and US.
//
// Prices are Spanish shelf prices, NOT converted from another market. The
// storefront's price filter uses per-currency bands (2/5/10 for GBP, same
// shape as euros — see
// cordelia's ProductPriceFilter), and a catalog that leaves a band empty makes
// that chip unmatchable; npm run verify:seed-bands enforces the spread.
//
// Image sources (every URL is verified live by scripts/verify-seed-images.mjs
// — re-run it whenever this file changes):
// - Products: real British product photos from Open Food Facts
//   (images.openfoodfacts.org) — © Open Food Facts contributors, CC-BY-SA
//   4.0. Barcodes were harvested from OFF's UK catalogue and every path
//   re-resolved through its product endpoint, because the search index returns
//   unpadded paths and stale revisions for short codes. Loose produce and the
//   whole Household aisle carry imageUrl "" — OFF is a packaged-*food* database —
//   and every consumer renders a placeholder.
// - Banners: landscape photography from Unsplash.
// - Brand logos: Google's favicon endpoint / DiceBear monograms.

import {
  OFF_IMAGE_BASE,
  type GrocerySeed,
} from "./seed-types";

const IMG = OFF_IMAGE_BASE;

export const UK_SEED: GrocerySeed = {
  categories: [
    {
      slug: "fruit-veg",
      name: "Fruit & Vegetables",
      imageUrl: "",
      groupName: "Food Cupboard",
    },
    {
      slug: "dairy-eggs",
      name: "Dairy & Eggs",
      imageUrl: `${IMG}/574/090/040/4465/front_en.30.400.jpg`,
      groupName: "Food Cupboard",
    },
    {
      slug: "bakery-breakfast",
      name: "Bakery & Breakfast",
      imageUrl: `${IMG}/501/004/400/2552/front_en.67.400.jpg`,
      groupName: "Food Cupboard",
    },
    {
      slug: "food-cupboard",
      name: "Food Cupboard",
      imageUrl: `${IMG}/500/023/290/2450/front_en.29.400.jpg`,
      groupName: "Food Cupboard",
    },
    {
      slug: "cooking-condiments",
      name: "Cooking & Condiments",
      imageUrl: `${IMG}/000/008/734/3397/front_en.19.400.jpg`,
      groupName: "Food Cupboard",
    },
    {
      slug: "frozen-chilled",
      name: "Frozen & Chilled",
      imageUrl: `${IMG}/501/022/800/1838/front_en.31.400.jpg`,
      groupName: "Food Cupboard",
    },
    {
      slug: "sweets-snacks",
      name: "Sweets & Snacks",
      imageUrl: `${IMG}/500/015/953/0736/front_en.43.400.jpg`,
      groupName: "Snacks & Drinks",
    },
    {
      slug: "drinks",
      name: "Drinks & Water",
      imageUrl: `${IMG}/501/045/900/5025/front_en.30.400.jpg`,
      groupName: "Snacks & Drinks",
    },
    {
      slug: "tea-coffee",
      name: "Tea & Coffee",
      imageUrl: `${IMG}/501/035/711/2061/front_en.27.400.jpg`,
      groupName: "Snacks & Drinks",
    },
    {
      slug: "household",
      name: "Household & Cleaning",
      imageUrl: "",
      groupName: "Household",
    },
  ],

  brands: [
    { slug: "lurpak", name: "Lurpak", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Lurpak&size=128&fontWeight=600" },
    { slug: "anchor", name: "Anchor", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Anchor&size=128&fontWeight=600" },
    { slug: "muller", name: "Müller", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Müller&size=128&fontWeight=600" },
    { slug: "cathedral-city", name: "Cathedral City", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Cathedral%20City&size=128&fontWeight=600" },
    { slug: "philadelphia", name: "Philadelphia", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Philadelphia&size=128&fontWeight=600" },
    { slug: "yeo-valley", name: "Yeo Valley", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://yeovalley.co.uk&size=128" },
    { slug: "arla", name: "Arla", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://arla.co.uk&size=128" },
    { slug: "yoplait", name: "Yoplait", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Yoplait&size=128&fontWeight=600" },
    { slug: "alpro", name: "Alpro", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://alpro.com&size=128" },
    { slug: "oatly", name: "Oatly", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://oatly.com&size=128" },
    { slug: "birds", name: "Bird's", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Bird's&size=128&fontWeight=600" },
    { slug: "warburtons", name: "Warburtons", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://warburtons.co.uk&size=128" },
    { slug: "hovis", name: "Hovis", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://hovis.co.uk&size=128" },
    { slug: "kingsmill", name: "Kingsmill", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Kingsmill&size=128&fontWeight=600" },
    { slug: "weetabix", name: "Weetabix", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://weetabix.co.uk&size=128" },
    { slug: "kelloggs", name: "Kellogg's", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Kellogg's&size=128&fontWeight=600" },
    { slug: "quaker", name: "Quaker", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Quaker&size=128&fontWeight=600" },
    { slug: "mcvities", name: "McVitie's", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=McVitie's&size=128&fontWeight=600" },
    { slug: "walkers-shortbread", name: "Walkers Shortbread", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Walkers%20Shortbread&size=128&fontWeight=600" },
    { slug: "nairns", name: "Nairn's", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://nairns.com&size=128" },
    { slug: "ryvita", name: "Ryvita", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Ryvita&size=128&fontWeight=600" },
    { slug: "carrs", name: "Carr's", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Carr's&size=128&fontWeight=600" },
    { slug: "hartleys", name: "Hartley's", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Hartley's&size=128&fontWeight=600" },
    { slug: "napolina", name: "Napolina", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://napolina.com&size=128" },
    { slug: "branston", name: "Branston", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Branston&size=128&fontWeight=600" },
    { slug: "heinz", name: "Heinz", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://heinz.co.uk&size=128" },
    { slug: "tilda", name: "Tilda", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://tilda.com&size=128" },
    { slug: "dolmio", name: "Dolmio", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Dolmio&size=128&fontWeight=600" },
    { slug: "bisto", name: "Bisto", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Bisto&size=128&fontWeight=600" },
    { slug: "barilla", name: "Barilla", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://barilla.com&size=128" },
    { slug: "hellmanns", name: "Hellmann's", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Hellmann's&size=128&fontWeight=600" },
    { slug: "colmans", name: "Colman's", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Colman's&size=128&fontWeight=600" },
    { slug: "lea-perrins", name: "Lea & Perrins", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Lea%20&%20Perrins&size=128&fontWeight=600" },
    { slug: "marmite", name: "Marmite", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Marmite&size=128&fontWeight=600" },
    { slug: "birds-eye", name: "Birds Eye", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://birdseye.co.uk&size=128" },
    { slug: "mccain", name: "McCain", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=McCain&size=128&fontWeight=600" },
    { slug: "youngs", name: "Young's", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Young's&size=128&fontWeight=600" },
    { slug: "goodfellas", name: "Goodfella's", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Goodfella's&size=128&fontWeight=600" },
    { slug: "chicago-town", name: "Chicago Town", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Chicago%20Town&size=128&fontWeight=600" },
    { slug: "snickers", name: "Snickers", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://snickers.com&size=128" },
    { slug: "swedish-glace", name: "Swedish Glace", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Swedish%20Glace&size=128&fontWeight=600" },
    { slug: "galaxy", name: "Galaxy", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Galaxy&size=128&fontWeight=600" },
    { slug: "maltesers", name: "Maltesers", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Maltesers&size=128&fontWeight=600" },
    { slug: "cadbury", name: "Cadbury", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://cadbury.co.uk&size=128" },
    { slug: "pringles", name: "Pringles", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://pringles.com&size=128" },
    { slug: "bahlsen", name: "Bahlsen", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://bahlsen.de&size=128" },
    { slug: "kallo", name: "Kallø", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Kallø&size=128&fontWeight=600" },
    { slug: "haribo", name: "Haribo", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://haribo.com&size=128" },
    { slug: "doritos", name: "Doritos", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://doritos.com&size=128" },
    { slug: "oreo", name: "Oreo", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Oreo&size=128&fontWeight=600" },
    { slug: "lindt", name: "Lindt", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://lindt.co.uk&size=128" },
    { slug: "milka", name: "Milka", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Milka&size=128&fontWeight=600" },
    { slug: "tuc", name: "Tuc", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Tuc&size=128&fontWeight=600" },
    { slug: "coca-cola", name: "Coca-Cola", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://coca-cola.co.uk&size=128" },
    { slug: "fanta", name: "Fanta", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Fanta&size=128&fontWeight=600" },
    { slug: "pepsi", name: "Pepsi", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://pepsi.com&size=128" },
    { slug: "highland-spring", name: "Highland Spring", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Highland%20Spring&size=128&fontWeight=600" },
    { slug: "buxton", name: "Buxton", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Buxton&size=128&fontWeight=600" },
    { slug: "evian", name: "evian", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://evian.com&size=128" },
    { slug: "volvic", name: "Volvic", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Volvic&size=128&fontWeight=600" },
    { slug: "robinsons", name: "Robinsons", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Robinsons&size=128&fontWeight=600" },
    { slug: "ribena", name: "Ribena", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Ribena&size=128&fontWeight=600" },
    { slug: "tropicana", name: "Tropicana", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Tropicana&size=128&fontWeight=600" },
    { slug: "taylors-of-harrogate", name: "Taylors of Harrogate", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Taylors%20of%20Harrogate&size=128&fontWeight=600" },
    { slug: "tetley", name: "Tetley", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://tetley.co.uk&size=128" },
    { slug: "twinings", name: "Twinings", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://twinings.co.uk&size=128" },
    { slug: "nescafe", name: "Nescafé", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://nescafe.com&size=128" },
    { slug: "kenco", name: "Kenco", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Kenco&size=128&fontWeight=600" },
    { slug: "douwe-egberts", name: "Douwe Egberts", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Douwe%20Egberts&size=128&fontWeight=600" },
    { slug: "lavazza", name: "Lavazza", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://lavazza.com&size=128" },
  ],

  products: [
    {
      slug: "bananas",
      name: "Bananas",
      imageUrl: "",
      price: 0.95,
      unitValue: 1000,
      unitType: "g",
      description:
        "Fairtrade bananas, ripe and ready to eat.",
      stock: 140,
      categorySlugs: ["fruit-veg"],
      isPopular: true,
    },
    {
      slug: "gala-apples",
      name: "Gala Apples",
      imageUrl: "",
      price: 1.85,
      unitValue: 1000,
      unitType: "g",
      description:
        "Crisp, sweet Gala apples, six to a pack.",
      stock: 120,
      categorySlugs: ["fruit-veg"],
      isPopular: true,
    },
    {
      slug: "vine-tomatoes",
      name: "Vine Tomatoes",
      imageUrl: "",
      price: 1.75,
      originalPrice: 2.1,
      unitValue: 500,
      unitType: "g",
      description:
        "Tomatoes ripened on the vine, full of flavour.",
      stock: 100,
      categorySlugs: ["fruit-veg"],
      isPopular: true,
    },
    {
      slug: "carrots",
      name: "Carrots",
      imageUrl: "",
      price: 0.75,
      unitValue: 1000,
      unitType: "g",
      description:
        "British carrots, washed and ready to cook.",
      stock: 130,
      categorySlugs: ["fruit-veg"],
    },
    {
      slug: "potatoes",
      name: "Maris Piper Potatoes",
      imageUrl: "",
      price: 1.65,
      unitValue: 2000,
      unitType: "g",
      description:
        "Maris Piper potatoes — the all-rounder for roasting and mash.",
      stock: 115,
      categorySlugs: ["fruit-veg"],
    },
    {
      slug: "onions",
      name: "Brown Onions",
      imageUrl: "",
      price: 0.95,
      unitValue: 1000,
      unitType: "g",
      description:
        "Brown onions with a mild, sweet flavour.",
      stock: 125,
      categorySlugs: ["fruit-veg"],
    },
    {
      slug: "cucumber",
      name: "Cucumber",
      imageUrl: "",
      price: 0.75,
      unitValue: 1,
      unitType: "pcs",
      description:
        "Whole cucumber, crisp and cool.",
      stock: 110,
      categorySlugs: ["fruit-veg"],
    },
    {
      slug: "iceberg-lettuce",
      name: "Iceberg Lettuce",
      imageUrl: "",
      price: 0.85,
      unitValue: 1,
      unitType: "pcs",
      description:
        "Crunchy iceberg lettuce, washed and trimmed.",
      stock: 95,
      categorySlugs: ["fruit-veg"],
    },
    {
      slug: "napolina-chopped-tomatoes",
      name: "Napolina Chopped Tomatoes",
      imageUrl: `${IMG}/501/006/100/1613/front_en.52.400.jpg`,
      price: 0.65,
      unitValue: 400,
      unitType: "g",
      description:
        "Italian chopped tomatoes, the base of every sauce.",
      stock: 160,
      categorySlugs: ["fruit-veg"],
      brandSlug: "napolina",
      isPopular: true,
    },
    {
      slug: "semi-skimmed-milk",
      name: "Semi Skimmed Milk",
      imageUrl: "",
      price: 1.3,
      unitValue: 1136,
      unitType: "ml",
      description:
        "British semi skimmed milk, two pints.",
      stock: 160,
      categorySlugs: ["dairy-eggs"],
      sizeVariants: [
        { value: 1136, price: 1.3 },
        { value: 2272, price: 1.85 },
      ],
      isPopular: true,
    },
    {
      slug: "lurpak-spreadable",
      name: "Lurpak Spreadable Slightly Salted",
      imageUrl: `${IMG}/574/090/040/4465/front_en.30.400.jpg`,
      price: 5.25,
      originalPrice: 5.9,
      unitValue: 400,
      unitType: "g",
      description:
        "Spreadable butter straight from the fridge, slightly salted.",
      stock: 95,
      categorySlugs: ["dairy-eggs"],
      brandSlug: "lurpak",
      isPopular: true,
    },
    {
      slug: "anchor-spreadable",
      name: "Anchor Spreadable",
      imageUrl: `${IMG}/500/024/672/8749/front_en.11.400.jpg`,
      price: 3.25,
      unitValue: 400,
      unitType: "g",
      description:
        "Anchor spreadable butter, made with British milk.",
      stock: 90,
      categorySlugs: ["dairy-eggs"],
      brandSlug: "anchor",
    },
    {
      slug: "muller-unsalted-butter",
      name: "Müller Unsalted Butter",
      imageUrl: `${IMG}/501/760/051/9387/front_en.3.400.jpg`,
      price: 2.25,
      unitValue: 250,
      unitType: "g",
      description:
        "Unsalted block butter for baking and cooking.",
      stock: 85,
      categorySlugs: ["dairy-eggs"],
      brandSlug: "muller",
    },
    {
      slug: "cathedral-city-mature",
      name: "Cathedral City Mature Cheddar",
      imageUrl: `${IMG}/500/029/514/2893/front_en.45.400.jpg`,
      price: 3.5,
      originalPrice: 3.95,
      unitValue: 350,
      unitType: "g",
      description:
        "Britain's favourite mature cheddar, ready sliced or grated.",
      stock: 100,
      categorySlugs: ["dairy-eggs"],
      brandSlug: "cathedral-city",
      isPopular: true,
    },
    {
      slug: "philadelphia-original",
      name: "Philadelphia Original",
      imageUrl: `${IMG}/762/220/169/5521/front_en.3.400.jpg`,
      price: 2.4,
      unitValue: 180,
      unitType: "g",
      description:
        "Soft cheese, smooth and mild.",
      stock: 95,
      categorySlugs: ["dairy-eggs"],
      brandSlug: "philadelphia",
    },
    {
      slug: "yeo-valley-yoghurt",
      name: "Yeo Valley Organic Natural Yoghurt",
      imageUrl: `${IMG}/503/658/925/5598/front_en.3.400.jpg`,
      price: 1.75,
      unitValue: 450,
      unitType: "g",
      description:
        "Organic natural yoghurt from British farms.",
      stock: 90,
      categorySlugs: ["dairy-eggs"],
      brandSlug: "yeo-valley",
    },
    {
      slug: "arla-skyr",
      name: "Arla Skyr Natural Fat Free",
      imageUrl: `${IMG}/401/624/103/0573/front_en.47.400.jpg`,
      price: 2.0,
      unitValue: 450,
      unitType: "g",
      description:
        "Icelandic-style skyr, fat free and high in protein.",
      stock: 85,
      categorySlugs: ["dairy-eggs"],
      brandSlug: "arla",
    },
    {
      slug: "yoplait-skyr",
      name: "Yoplait Skyr Natural",
      imageUrl: `${IMG}/332/977/007/7003/front_en.164.400.jpg`,
      price: 2.5,
      unitValue: 850,
      unitType: "g",
      description:
        "Thick natural skyr in a sharing tub.",
      stock: 70,
      categorySlugs: ["dairy-eggs"],
      brandSlug: "yoplait",
    },
    {
      slug: "alpro-almond",
      name: "Alpro Almond Drink",
      imageUrl: `${IMG}/541/118/811/0835/front_en.669.400.jpg`,
      price: 1.9,
      unitValue: 1000,
      unitType: "ml",
      description:
        "Unsweetened almond drink, naturally lactose free.",
      stock: 80,
      categorySlugs: ["dairy-eggs"],
      brandSlug: "alpro",
    },
    {
      slug: "oatly-barista",
      name: "Oatly Oat Drink Barista Edition",
      imageUrl: `${IMG}/739/437/661/6228/front_en.197.400.jpg`,
      price: 2.2,
      unitValue: 1000,
      unitType: "ml",
      description:
        "Oat drink that froths properly for flat whites at home.",
      stock: 85,
      categorySlugs: ["dairy-eggs"],
      brandSlug: "oatly",
      isPopular: true,
    },
    {
      slug: "free-range-eggs",
      name: "Free Range Eggs",
      imageUrl: "",
      price: 2.65,
      unitValue: 6,
      unitType: "pcs",
      description:
        "Six large free range eggs from British hens.",
      stock: 110,
      categorySlugs: ["dairy-eggs"],
      isPopular: true,
    },
    {
      slug: "birds-custard-powder",
      name: "Bird's Custard Powder",
      imageUrl: `${IMG}/500/035/490/8248/front_en.33.400.jpg`,
      price: 2.1,
      unitValue: 350,
      unitType: "g",
      description:
        "The original custard powder — just add milk.",
      stock: 80,
      categorySlugs: ["dairy-eggs"],
      brandSlug: "birds",
    },
    {
      slug: "warburtons-seeded",
      name: "Warburtons Seeded Batch",
      imageUrl: `${IMG}/501/004/400/2552/front_en.67.400.jpg`,
      price: 1.65,
      unitValue: 800,
      unitType: "g",
      description:
        "Soft seeded batch loaf, thickly sliced.",
      stock: 120,
      categorySlugs: ["bakery-breakfast"],
      brandSlug: "warburtons",
      isPopular: true,
    },
    {
      slug: "hovis-seed-sensations",
      name: "Hovis Seed Sensations",
      imageUrl: `${IMG}/501/000/306/4744/front_en.76.400.jpg`,
      price: 1.55,
      unitValue: 800,
      unitType: "g",
      description:
        "Seeded wholemeal loaf packed with five seeds.",
      stock: 110,
      categorySlugs: ["bakery-breakfast"],
      brandSlug: "hovis",
    },
    {
      slug: "kingsmill-5050",
      name: "Kingsmill 50/50 Medium",
      imageUrl: `${IMG}/501/009/209/3441/front_en.61.400.jpg`,
      price: 1.4,
      unitValue: 800,
      unitType: "g",
      description:
        "The taste of white with the goodness of wholemeal.",
      stock: 115,
      categorySlugs: ["bakery-breakfast"],
      brandSlug: "kingsmill",
    },
    {
      slug: "weetabix",
      name: "Weetabix",
      imageUrl: `${IMG}/501/002/900/0016/front_en.44.400.jpg`,
      price: 3.2,
      originalPrice: 3.6,
      unitValue: 430,
      unitType: "g",
      description:
        "Twenty-four Weetabix biscuits, high in fibre.",
      stock: 105,
      categorySlugs: ["bakery-breakfast"],
      brandSlug: "weetabix",
      isPopular: true,
    },
    {
      slug: "kelloggs-corn-flakes",
      name: "Kellogg's Corn Flakes",
      imageUrl: `${IMG}/315/947/000/0120/front_en.147.400.jpg`,
      price: 3.0,
      unitValue: 500,
      unitType: "g",
      description:
        "The original corn flakes, toasted golden.",
      stock: 100,
      categorySlugs: ["bakery-breakfast"],
      brandSlug: "kelloggs",
      isPopular: true,
    },
    {
      slug: "quaker-oats",
      name: "Quaker Quick Cooking Oats",
      imageUrl: `${IMG}/500/010/802/2824/front_en.8.400.jpg`,
      price: 1.6,
      unitValue: 500,
      unitType: "g",
      description:
        "Quick cooking white oats for porridge in three minutes.",
      stock: 115,
      categorySlugs: ["bakery-breakfast"],
      brandSlug: "quaker",
    },
    {
      slug: "mcvities-digestives",
      name: "McVitie's Digestive Biscuits",
      imageUrl: `${IMG}/500/016/819/8491/front_en.193.400.jpg`,
      price: 1.75,
      unitValue: 400,
      unitType: "g",
      description:
        "The original digestive — made for a cup of tea.",
      stock: 130,
      categorySlugs: ["bakery-breakfast"],
      brandSlug: "mcvities",
      isPopular: true,
    },
    {
      slug: "walkers-shortbread",
      name: "Walkers Shortbread Highlanders",
      imageUrl: `${IMG}/003/904/700/1442/front_en.87.400.jpg`,
      price: 2.9,
      unitValue: 200,
      unitType: "g",
      description:
        "Pure butter shortbread, baked in Speyside.",
      stock: 75,
      categorySlugs: ["bakery-breakfast"],
      brandSlug: "walkers-shortbread",
    },
    {
      slug: "nairns-oatcakes",
      name: "Nairn's Rough Oatcakes",
      imageUrl: `${IMG}/006/123/220/3072/front_en.89.400.jpg`,
      price: 2.2,
      unitValue: 291,
      unitType: "g",
      description:
        "Rough oatcakes made with wholegrain oats.",
      stock: 85,
      categorySlugs: ["bakery-breakfast"],
      brandSlug: "nairns",
    },
    {
      slug: "ryvita-dark-rye",
      name: "Ryvita Dark Rye Crispbread",
      imageUrl: `${IMG}/501/026/500/2911/front_en.54.400.jpg`,
      price: 1.85,
      unitValue: 250,
      unitType: "g",
      description:
        "Dark rye crispbread, high in fibre.",
      stock: 80,
      categorySlugs: ["bakery-breakfast"],
      brandSlug: "ryvita",
    },
    {
      slug: "carrs-table-water",
      name: "Carr's Table Water Biscuits",
      imageUrl: `${IMG}/500/016/800/1104/front_en.95.400.jpg`,
      price: 1.65,
      unitValue: 125,
      unitType: "g",
      description:
        "Light table water biscuits for cheese.",
      stock: 85,
      categorySlugs: ["bakery-breakfast"],
      brandSlug: "carrs",
    },
    {
      slug: "hartleys-strawberry-jelly",
      name: "Hartley's Strawberry Jelly",
      imageUrl: `${IMG}/506/039/162/8745/front_en.6.400.jpg`,
      price: 1.5,
      unitValue: 690,
      unitType: "g",
      description:
        "Ready to eat strawberry jelly pots, six in a pack.",
      stock: 90,
      categorySlugs: ["bakery-breakfast"],
      brandSlug: "hartleys",
    },
    {
      slug: "branston-baked-beans",
      name: "Branston Baked Beans",
      imageUrl: `${IMG}/500/023/290/2450/front_en.29.400.jpg`,
      price: 1.1,
      unitValue: 410,
      unitType: "g",
      description:
        "Baked beans in a rich tomato sauce.",
      stock: 170,
      categorySlugs: ["food-cupboard"],
      brandSlug: "branston",
      isPopular: true,
    },
    {
      slug: "heinz-tomato-ketchup",
      name: "Heinz Tomato Ketchup",
      imageUrl: `${IMG}/000/008/715/7215/front_en.208.400.jpg`,
      price: 2.5,
      unitValue: 460,
      unitType: "g",
      description:
        "The classic tomato ketchup, thick and tangy.",
      stock: 150,
      categorySlugs: ["food-cupboard"],
      brandSlug: "heinz",
      isPopular: true,
    },
    {
      slug: "napolina-chickpeas",
      name: "Napolina Chickpeas in Water",
      imageUrl: `${IMG}/500/023/284/4217/front_en.24.400.jpg`,
      price: 0.75,
      unitValue: 400,
      unitType: "g",
      description:
        "Chickpeas in water, ready for curries and salads.",
      stock: 140,
      categorySlugs: ["food-cupboard"],
      brandSlug: "napolina",
    },
    {
      slug: "tilda-basmati",
      name: "Tilda Pure Basmati Rice",
      imageUrl: `${IMG}/501/115/788/8101/front_en.3.400.jpg`,
      price: 2.4,
      unitValue: 250,
      unitType: "g",
      description:
        "Pure basmati rice, steamed and ready in two minutes.",
      stock: 110,
      categorySlugs: ["food-cupboard"],
      brandSlug: "tilda",
    },
    {
      slug: "tilda-brown-basmati",
      name: "Tilda Brown Basmati & Wild Rice",
      imageUrl: `${IMG}/501/115/799/2662/front_en.25.400.jpg`,
      price: 2.6,
      unitValue: 250,
      unitType: "g",
      description:
        "Brown basmati with wild rice, nutty and wholegrain.",
      stock: 90,
      categorySlugs: ["food-cupboard"],
      brandSlug: "tilda",
    },
    {
      slug: "dolmio-bolognese",
      name: "Dolmio Original Bolognese",
      imageUrl: `${IMG}/400/235/963/4420/front_en.36.400.jpg`,
      price: 2.0,
      unitValue: 500,
      unitType: "g",
      description:
        "Original bolognese sauce made with Italian tomatoes.",
      stock: 120,
      categorySlugs: ["food-cupboard"],
      brandSlug: "dolmio",
      isPopular: true,
    },
    {
      slug: "bisto-gravy-granules",
      name: "Bisto Gravy Granules",
      imageUrl: `${IMG}/500/035/491/9527/front_en.31.400.jpg`,
      price: 2.2,
      unitValue: 190,
      unitType: "g",
      description:
        "Gravy granules for meat dishes — ready in a minute.",
      stock: 115,
      categorySlugs: ["food-cupboard"],
      brandSlug: "bisto",
    },
    {
      slug: "barilla-spaghetti",
      name: "Barilla Spaghetti",
      imageUrl: `${IMG}/807/680/019/5057/front_en.3809.400.jpg`,
      price: 1.4,
      unitValue: 500,
      unitType: "g",
      description:
        "Durum wheat spaghetti, al dente in nine minutes.",
      stock: 135,
      categorySlugs: ["food-cupboard"],
      brandSlug: "barilla",
      isPopular: true,
    },
    {
      slug: "caster-sugar",
      name: "Caster Sugar",
      imageUrl: "",
      price: 1.15,
      unitValue: 1000,
      unitType: "g",
      description:
        "Fine caster sugar for baking and desserts.",
      stock: 120,
      categorySlugs: ["food-cupboard"],
    },
    {
      slug: "plain-flour",
      name: "Plain Flour",
      imageUrl: "",
      price: 0.85,
      unitValue: 1500,
      unitType: "g",
      description:
        "Plain white flour for everyday baking.",
      stock: 125,
      categorySlugs: ["food-cupboard"],
    },
    {
      slug: "long-grain-rice",
      name: "Long Grain Rice",
      imageUrl: "",
      price: 1.6,
      unitValue: 1000,
      unitType: "g",
      description:
        "Easy cook long grain rice, fluffy every time.",
      stock: 115,
      categorySlugs: ["food-cupboard"],
    },
    {
      slug: "napolina-passata",
      name: "Napolina Passata",
      imageUrl: "",
      price: 1.05,
      unitValue: 690,
      unitType: "g",
      description:
        "Smooth sieved tomato passata for sauces and soups.",
      stock: 125,
      categorySlugs: ["food-cupboard"],
      brandSlug: "napolina",
    },
    {
      slug: "hellmanns-mayonnaise",
      name: "Hellmann's Real Mayonnaise",
      imageUrl: `${IMG}/871/811/472/4485/front_en.46.400.jpg`,
      price: 3.5,
      unitValue: 750,
      unitType: "ml",
      description:
        "Real mayonnaise made with free range eggs.",
      stock: 105,
      categorySlugs: ["cooking-condiments"],
      brandSlug: "hellmanns",
      isPopular: true,
    },
    {
      slug: "colmans-mustard",
      name: "Colman's Mustard",
      imageUrl: `${IMG}/000/005/014/7588/front_en.61.400.jpg`,
      price: 1.6,
      unitValue: 170,
      unitType: "g",
      description:
        "English mustard with a proper kick.",
      stock: 110,
      categorySlugs: ["cooking-condiments"],
      brandSlug: "colmans",
    },
    {
      slug: "lea-perrins",
      name: "Lea & Perrins Worcestershire Sauce",
      imageUrl: `${IMG}/500/011/104/1843/front_en.42.400.jpg`,
      price: 2.2,
      unitValue: 290,
      unitType: "ml",
      description:
        "The original Worcestershire sauce, matured in oak.",
      stock: 95,
      categorySlugs: ["cooking-condiments"],
      brandSlug: "lea-perrins",
    },
    {
      slug: "marmite",
      name: "Marmite Reduced Salt",
      imageUrl: `${IMG}/000/008/734/3397/front_en.19.400.jpg`,
      price: 3.6,
      unitValue: 250,
      unitType: "g",
      description:
        "Love it or hate it — the reduced salt jar.",
      stock: 85,
      categorySlugs: ["cooking-condiments"],
      brandSlug: "marmite",
      isPopular: true,
    },
    {
      slug: "olive-oil",
      name: "Extra Virgin Olive Oil",
      imageUrl: "",
      price: 4.5,
      unitValue: 500,
      unitType: "ml",
      description:
        "Cold pressed extra virgin olive oil for dressings.",
      stock: 90,
      categorySlugs: ["cooking-condiments"],
    },
    {
      slug: "vegetable-oil",
      name: "Vegetable Oil",
      imageUrl: "",
      price: 2.2,
      unitValue: 1000,
      unitType: "ml",
      description:
        "Vegetable oil for frying and roasting.",
      stock: 100,
      categorySlugs: ["cooking-condiments"],
    },
    {
      slug: "table-salt",
      name: "Table Salt",
      imageUrl: "",
      price: 0.65,
      unitValue: 750,
      unitType: "g",
      description:
        "Fine table salt for cooking and the table.",
      stock: 130,
      categorySlugs: ["cooking-condiments"],
    },
    {
      slug: "black-pepper",
      name: "Ground Black Pepper",
      imageUrl: "",
      price: 1.4,
      unitValue: 100,
      unitType: "g",
      description:
        "Ground black pepper, warm and aromatic.",
      stock: 105,
      categorySlugs: ["cooking-condiments"],
    },
    {
      slug: "birds-eye-garden-peas",
      name: "Birds Eye Garden Peas",
      imageUrl: `${IMG}/500/011/612/7771/front_en.3.400.jpg`,
      price: 1.8,
      unitValue: 800,
      unitType: "g",
      description:
        "Garden peas frozen within hours of picking.",
      stock: 125,
      categorySlugs: ["frozen-chilled"],
      brandSlug: "birds-eye",
      isPopular: true,
    },
    {
      slug: "mccain-crispy-fries",
      name: "McCain Crispy French Fries",
      imageUrl: `${IMG}/501/022/800/1838/front_en.31.400.jpg`,
      price: 2.75,
      originalPrice: 3.2,
      unitValue: 900,
      unitType: "g",
      description:
        "Thin crispy fries, oven ready in 15 minutes.",
      stock: 110,
      categorySlugs: ["frozen-chilled"],
      brandSlug: "mccain",
      isPopular: true,
    },
    {
      slug: "youngs-tempura-fish",
      name: "Young's Gastro Tempura Battered Fish",
      imageUrl: `${IMG}/500/020/504/8284/front_en.54.400.jpg`,
      price: 3.5,
      unitValue: 240,
      unitType: "g",
      description:
        "Two tempura battered fish fillets, light and crisp.",
      stock: 85,
      categorySlugs: ["frozen-chilled"],
      brandSlug: "youngs",
    },
    {
      slug: "goodfellas-margherita",
      name: "Goodfella's Stonebaked Thin Margherita",
      imageUrl: `${IMG}/501/100/304/6389/front_en.47.400.jpg`,
      price: 2.5,
      unitValue: 345,
      unitType: "g",
      description:
        "Stonebaked thin crust margherita pizza.",
      stock: 95,
      categorySlugs: ["frozen-chilled"],
      brandSlug: "goodfellas",
      isPopular: true,
    },
    {
      slug: "chicago-town-deep-dish",
      name: "Chicago Town Fully Loaded Deep Dish",
      imageUrl: `${IMG}/501/931/208/1794/front_en.29.400.jpg`,
      price: 2.2,
      unitValue: 320,
      unitType: "g",
      description:
        "Two deep dish pizzas, loaded and ready in 20 minutes.",
      stock: 100,
      categorySlugs: ["frozen-chilled"],
      brandSlug: "chicago-town",
    },
    {
      slug: "snickers-ice-cream",
      name: "Snickers Ice Cream Bars",
      imageUrl: `${IMG}/500/015/954/1374/front_en.4.400.jpg`,
      price: 3.0,
      unitValue: 280,
      unitType: "g",
      description:
        "Four Snickers ice cream bars with peanuts and caramel.",
      stock: 80,
      categorySlugs: ["frozen-chilled"],
      brandSlug: "snickers",
    },
    {
      slug: "swedish-glace",
      name: "Swedish Glace Vanilla",
      imageUrl: `${IMG}/871/410/059/0430/front_en.43.400.jpg`,
      price: 3.25,
      unitValue: 394,
      unitType: "g",
      description:
        "Dairy free vanilla ice cream, smooth and light.",
      stock: 70,
      categorySlugs: ["frozen-chilled"],
      brandSlug: "swedish-glace",
    },
    {
      slug: "frozen-spinach",
      name: "Frozen Spinach",
      imageUrl: "",
      price: 1.3,
      unitValue: 900,
      unitType: "g",
      description:
        "Chopped spinach in frozen portions.",
      stock: 100,
      categorySlugs: ["frozen-chilled"],
    },
    {
      slug: "oven-chips",
      name: "Oven Chips",
      imageUrl: "",
      price: 1.9,
      unitValue: 1500,
      unitType: "g",
      description:
        "Straight cut oven chips, no frying needed.",
      stock: 105,
      categorySlugs: ["frozen-chilled"],
    },
    {
      slug: "galaxy",
      name: "Galaxy Smooth Milk",
      imageUrl: `${IMG}/500/015/955/3018/front_en.50.400.jpg`,
      price: 1.35,
      unitValue: 100,
      unitType: "g",
      description:
        "Smooth milk chocolate that melts as you eat it.",
      stock: 130,
      categorySlugs: ["sweets-snacks"],
      brandSlug: "galaxy",
      isPopular: true,
    },
    {
      slug: "maltesers-pouch",
      name: "Maltesers Pouch",
      imageUrl: `${IMG}/500/015/953/0736/front_en.43.400.jpg`,
      price: 2.0,
      unitValue: 102,
      unitType: "g",
      description:
        "The lighter way to enjoy chocolate, in a sharing pouch.",
      stock: 125,
      categorySlugs: ["sweets-snacks"],
      brandSlug: "maltesers",
      isPopular: true,
    },
    {
      slug: "cadbury-brunch-bar",
      name: "Cadbury Brunch Bar Choc Chip",
      imageUrl: `${IMG}/762/220/182/4334/front_en.8.400.jpg`,
      price: 1.6,
      unitValue: 5,
      unitType: "pcs",
      description:
        "Five chocolate chip cereal bars for the lunchbox.",
      stock: 110,
      categorySlugs: ["sweets-snacks"],
      brandSlug: "cadbury",
    },
    {
      slug: "pringles-smokey-bacon",
      name: "Pringles Smokey Bacon",
      imageUrl: `${IMG}/505/399/016/2765/front_en.22.400.jpg`,
      price: 2.75,
      unitValue: 175,
      unitType: "g",
      description:
        "Once you pop… smokey bacon flavour.",
      stock: 120,
      categorySlugs: ["sweets-snacks"],
      brandSlug: "pringles",
      isPopular: true,
    },
    {
      slug: "doritos-nacho-cheese",
      name: "Doritos Nacho Cheese",
      imageUrl: `${IMG}/590/025/909/4704/front_en.62.400.jpg`,
      price: 2.0,
      unitValue: 100,
      unitType: "g",
      description:
        "Nacho cheese tortilla chips for dipping.",
      stock: 115,
      categorySlugs: ["sweets-snacks"],
      brandSlug: "doritos",
    },
    {
      slug: "bahlsen-biscuits",
      name: "Bahlsen Choco Leibniz",
      imageUrl: `${IMG}/401/710/029/0008/front_en.173.400.jpg`,
      price: 1.9,
      unitValue: 125,
      unitType: "g",
      description:
        "Butter biscuits topped with a thick layer of chocolate.",
      stock: 90,
      categorySlugs: ["sweets-snacks"],
      brandSlug: "bahlsen",
    },
    {
      slug: "kallo-rice-cakes",
      name: "Kallø Wholegrain Rice Cakes",
      imageUrl: `${IMG}/501/366/510/0065/front_en.58.400.jpg`,
      price: 1.3,
      unitValue: 130,
      unitType: "g",
      description:
        "Organic lightly salted wholegrain rice cakes.",
      stock: 95,
      categorySlugs: ["sweets-snacks"],
      brandSlug: "kallo",
    },
    {
      slug: "haribo-starmix",
      name: "Haribo Goldbears",
      imageUrl: `${IMG}/900/297/530/1558/front_en.16.400.jpg`,
      price: 1.2,
      unitValue: 100,
      unitType: "g",
      description:
        "The original gold bears in six fruit flavours.",
      stock: 140,
      categorySlugs: ["sweets-snacks"],
      brandSlug: "haribo",
    },
    {
      slug: "oreo-original",
      name: "Oreo Original",
      imageUrl: `${IMG}/762/221/002/1502/front_en.47.400.jpg`,
      price: 1.75,
      unitValue: 220,
      unitType: "g",
      description:
        "Chocolate sandwich biscuits with vanilla cream.",
      stock: 115,
      categorySlugs: ["sweets-snacks"],
      brandSlug: "oreo",
    },
    {
      slug: "lindt-excellence-70",
      name: "Lindt Excellence 70% Dark",
      imageUrl: `${IMG}/304/692/002/2651/front_en.159.400.jpg`,
      price: 2.2,
      unitValue: 100,
      unitType: "g",
      description:
        "Intense dark chocolate with 70% cocoa.",
      stock: 90,
      categorySlugs: ["sweets-snacks"],
      brandSlug: "lindt",
    },
    {
      slug: "milka-cake-choc",
      name: "Milka Cake & Choc",
      imageUrl: `${IMG}/762/230/078/4751/front_de.111.400.jpg`,
      price: 1.85,
      unitValue: 175,
      unitType: "g",
      description:
        "Soft cakes with a Milka chocolate centre.",
      stock: 95,
      categorySlugs: ["sweets-snacks"],
      brandSlug: "milka",
    },
    {
      slug: "tuc-cheese",
      name: "Tuc Cheese Crackers",
      imageUrl: `${IMG}/762/230/057/1351/front_en.156.400.jpg`,
      price: 1.5,
      unitValue: 100,
      unitType: "g",
      description:
        "Salted crackers with a cheese flavour.",
      stock: 105,
      categorySlugs: ["sweets-snacks"],
      brandSlug: "tuc",
    },
    {
      slug: "coca-cola",
      name: "Coca-Cola",
      imageUrl: `${IMG}/544/900/000/0996/front_en.1107.400.jpg`,
      price: 0.85,
      unitValue: 330,
      unitType: "ml",
      description:
        "Coca-Cola in a can, best served ice cold.",
      stock: 210,
      categorySlugs: ["drinks"],
      brandSlug: "coca-cola",
      sizeVariants: [
        { value: 330, price: 0.85 },
        { value: 1500, price: 2.05 },
      ],
      isPopular: true,
    },
    {
      slug: "fanta-orange",
      name: "Fanta Orange",
      imageUrl: `${IMG}/544/900/001/1527/front_en.376.400.jpg`,
      price: 0.85,
      unitValue: 330,
      unitType: "ml",
      description:
        "Fanta Orange with real fruit juice.",
      stock: 180,
      categorySlugs: ["drinks"],
      brandSlug: "fanta",
    },
    {
      slug: "pepsi-max",
      name: "Pepsi Max",
      imageUrl: `${IMG}/350/211/000/9357/front_en.101.400.jpg`,
      price: 2.1,
      unitValue: 1500,
      unitType: "ml",
      description:
        "Maximum taste, no sugar, in a 1.5 litre bottle.",
      stock: 150,
      categorySlugs: ["drinks"],
      brandSlug: "pepsi",
    },
    {
      slug: "highland-spring",
      name: "Highland Spring Still Water",
      imageUrl: `${IMG}/501/045/900/5025/front_en.30.400.jpg`,
      price: 0.75,
      unitValue: 1500,
      unitType: "ml",
      description:
        "Still spring water from the Ochil Hills.",
      stock: 200,
      categorySlugs: ["drinks"],
      brandSlug: "highland-spring",
      isPopular: true,
    },
    {
      slug: "buxton-still",
      name: "Buxton Still Water",
      imageUrl: `${IMG}/761/303/121/4839/front_en.25.400.jpg`,
      price: 0.65,
      unitValue: 1000,
      unitType: "ml",
      description:
        "Natural mineral water from the Peak District.",
      stock: 190,
      categorySlugs: ["drinks"],
      brandSlug: "buxton",
    },
    {
      slug: "evian",
      name: "evian Natural Mineral Water",
      imageUrl: `${IMG}/306/832/008/4602/front_de.62.400.jpg`,
      price: 0.95,
      unitValue: 1500,
      unitType: "ml",
      description:
        "Natural mineral water filtered through Alpine rock.",
      stock: 170,
      categorySlugs: ["drinks"],
      brandSlug: "evian",
    },
    {
      slug: "volvic",
      name: "Volvic Natural Mineral Water",
      imageUrl: `${IMG}/305/764/010/0178/front_en.71.400.jpg`,
      price: 0.95,
      unitValue: 1500,
      unitType: "ml",
      description:
        "Volcanic natural mineral water, softly mineralised.",
      stock: 165,
      categorySlugs: ["drinks"],
      brandSlug: "volvic",
    },
    {
      slug: "robinsons-squash",
      name: "Robinsons Raspberry & Apple Squash",
      imageUrl: `${IMG}/501/010/224/3705/front_en.3.400.jpg`,
      price: 2.0,
      unitValue: 500,
      unitType: "ml",
      description:
        "Real fruit squash with no added sugar.",
      stock: 130,
      categorySlugs: ["drinks"],
      brandSlug: "robinsons",
      isPopular: true,
    },
    {
      slug: "ribena-blackcurrant",
      name: "Ribena Blackcurrant Squash",
      imageUrl: `${IMG}/505/426/700/3378/front_en.23.400.jpg`,
      price: 2.5,
      unitValue: 850,
      unitType: "ml",
      description:
        "Blackcurrant squash made with British berries.",
      stock: 120,
      categorySlugs: ["drinks"],
      brandSlug: "ribena",
    },
    {
      slug: "tropicana-orange",
      name: "Tropicana Orange Juice with Bits",
      imageUrl: `${IMG}/502/231/300/0282/front_en.26.400.jpg`,
      price: 2.75,
      originalPrice: 3.2,
      unitValue: 900,
      unitType: "ml",
      description:
        "Not from concentrate orange juice with juicy bits.",
      stock: 110,
      categorySlugs: ["drinks"],
      brandSlug: "tropicana",
      isPopular: true,
    },
    {
      slug: "yorkshire-tea",
      name: "Taylors of Harrogate Yorkshire Tea",
      imageUrl: `${IMG}/501/035/711/2061/front_en.27.400.jpg`,
      price: 3.6,
      unitValue: 250,
      unitType: "g",
      description:
        "Proper tea, blended for Yorkshire water.",
      stock: 130,
      categorySlugs: ["tea-coffee"],
      brandSlug: "taylors-of-harrogate",
      isPopular: true,
    },
    {
      slug: "tetley-tea-bags",
      name: "Tetley Tea Bags",
      imageUrl: `${IMG}/500/020/806/9897/front_en.25.400.jpg`,
      price: 5.5,
      originalPrice: 6.25,
      unitValue: 240,
      unitType: "pcs",
      description:
        "Two hundred and forty tea bags — the everyday brew.",
      stock: 110,
      categorySlugs: ["tea-coffee"],
      brandSlug: "tetley",
      isPopular: true,
    },
    {
      slug: "twinings-lemon-ginger",
      name: "Twinings Lemon & Ginger",
      imageUrl: `${IMG}/007/017/707/5101/front_en.27.400.jpg`,
      price: 2.6,
      unitValue: 20,
      unitType: "pcs",
      description:
        "Twenty lemon and ginger infusion bags, caffeine free.",
      stock: 95,
      categorySlugs: ["tea-coffee"],
      brandSlug: "twinings",
    },
    {
      slug: "nescafe-azera",
      name: "Nescafé Azera Americano",
      imageUrl: `${IMG}/844/529/004/4822/front_en.3.400.jpg`,
      price: 5.5,
      unitValue: 90,
      unitType: "g",
      description:
        "Barista-style instant coffee with a fine crema.",
      stock: 100,
      categorySlugs: ["tea-coffee"],
      brandSlug: "nescafe",
    },
    {
      slug: "kenco-instant",
      name: "Kenco Instant Coffee",
      imageUrl: `${IMG}/871/100/051/9417/front_en.25.400.jpg`,
      price: 5.25,
      unitValue: 200,
      unitType: "g",
      description:
        "Smooth instant coffee, rich and rounded.",
      stock: 105,
      categorySlugs: ["tea-coffee"],
      brandSlug: "kenco",
    },
    {
      slug: "douwe-egberts-millicano",
      name: "Douwe Egberts Millicano Decaf",
      imageUrl: `${IMG}/871/100/051/9110/front_en.12.400.jpg`,
      price: 5.75,
      unitValue: 100,
      unitType: "g",
      description:
        "Wholebean instant decaf with real ground coffee.",
      stock: 85,
      categorySlugs: ["tea-coffee"],
      brandSlug: "douwe-egberts",
    },
    {
      slug: "lavazza-qualita-rossa",
      name: "Lavazza Qualità Rossa Ground",
      imageUrl: `${IMG}/800/007/003/6864/front_en.7.400.jpg`,
      price: 4.0,
      unitValue: 250,
      unitType: "g",
      description:
        "Ground coffee with a full, chocolatey body.",
      stock: 95,
      categorySlugs: ["tea-coffee"],
      brandSlug: "lavazza",
    },
    {
      slug: "cadbury-hot-chocolate",
      name: "Cadbury Hot Chocolate",
      imageUrl: `${IMG}/503/466/002/1582/front_en.101.400.jpg`,
      price: 4.0,
      unitValue: 500,
      unitType: "g",
      description:
        "Instant hot chocolate powder — just add hot milk.",
      stock: 90,
      categorySlugs: ["tea-coffee"],
      brandSlug: "cadbury",
    },
    {
      slug: "ground-coffee",
      name: "Ground Coffee",
      imageUrl: "",
      price: 3.8,
      unitValue: 227,
      unitType: "g",
      description:
        "Medium roast ground coffee for cafetières and filters.",
      stock: 100,
      categorySlugs: ["tea-coffee"],
    },
    {
      slug: "washing-up-liquid",
      name: "Washing Up Liquid",
      imageUrl: "",
      price: 1.2,
      unitValue: 500,
      unitType: "ml",
      description:
        "Concentrated washing up liquid that cuts through grease.",
      stock: 120,
      categorySlugs: ["household"],
    },
    {
      slug: "multi-surface-cleaner",
      name: "Multi-Surface Cleaner",
      imageUrl: "",
      price: 1.6,
      unitValue: 750,
      unitType: "ml",
      description:
        "Multi-surface spray for kitchens and bathrooms.",
      stock: 110,
      categorySlugs: ["household"],
    },
    {
      slug: "toilet-roll",
      name: "Toilet Roll 3 Ply",
      imageUrl: "",
      price: 4.0,
      originalPrice: 4.6,
      unitValue: 9,
      unitType: "pcs",
      description:
        "Nine rolls of soft three ply toilet tissue.",
      stock: 135,
      categorySlugs: ["household"],
      isPopular: true,
    },
    {
      slug: "kitchen-roll",
      name: "Kitchen Roll",
      imageUrl: "",
      price: 2.4,
      unitValue: 4,
      unitType: "pcs",
      description:
        "Four rolls of extra absorbent kitchen towel.",
      stock: 120,
      categorySlugs: ["household"],
    },
    {
      slug: "bin-bags",
      name: "Bin Bags 50L",
      imageUrl: "",
      price: 2.1,
      unitValue: 20,
      unitType: "pcs",
      description:
        "Twenty tie handle bin bags, strong and leak resistant.",
      stock: 105,
      categorySlugs: ["household"],
    },
    {
      slug: "laundry-liquid",
      name: "Laundry Liquid",
      imageUrl: "",
      price: 11.5,
      originalPrice: 13.0,
      unitValue: 3000,
      unitType: "ml",
      description:
        "Laundry liquid for 60 washes, effective from 20°C.",
      stock: 70,
      categorySlugs: ["household"],
      isPopular: true,
    },
    {
      slug: "dishwasher-tablets",
      name: "Dishwasher Tablets All in One",
      imageUrl: "",
      price: 12.75,
      unitValue: 60,
      unitType: "pcs",
      description:
        "Sixty all in one tablets with salt and rinse aid.",
      stock: 75,
      categorySlugs: ["household"],
    },
    {
      slug: "toothpaste",
      name: "Toothpaste Complete Care",
      imageUrl: "",
      price: 1.95,
      unitValue: 75,
      unitType: "ml",
      description:
        "Fluoride toothpaste for daily cavity protection.",
      stock: 115,
      categorySlugs: ["household"],
    },
  ],

  coupons: [
    {
      code: "WELCOME10",
      type: "percent",
      value: 10,
      scope: "store",
      minOrderValue: 20,
      maxDiscount: 5,
      usageLimit: 500,
      perUserLimit: 1,
    },
    {
      code: "FRESH5",
      type: "percent",
      value: 5,
      scope: "category",
      targetCategorySlugs: ["fruit-veg"],
      minOrderValue: 10,
      maxDiscount: 3,
      usageLimit: 300,
      perUserLimit: 2,
    },
    {
      code: "BREW15",
      type: "percent",
      value: 15,
      scope: "category",
      targetCategorySlugs: ["tea-coffee"],
      minOrderValue: 15,
      maxDiscount: 5,
      usageLimit: 200,
      perUserLimit: 1,
    },
    {
      code: "TREAT2",
      type: "flat",
      value: 2,
      scope: "category",
      targetCategorySlugs: ["sweets-snacks"],
      minOrderValue: 12,
      maxDiscount: 2,
      usageLimit: 250,
      perUserLimit: 2,
    },
    {
      code: "HOME3",
      type: "flat",
      value: 3,
      scope: "category",
      targetCategorySlugs: ["household"],
      minOrderValue: 25,
      maxDiscount: 3,
      usageLimit: 150,
      perUserLimit: 1,
    },
    {
      code: "PIZZA1",
      type: "flat",
      value: 1,
      scope: "product",
      targetProductSlugs: ["goodfellas-margherita", "chicago-town-deep-dish", "mccain-crispy-fries"],
      minOrderValue: 6,
      maxDiscount: 1,
      usageLimit: 400,
      perUserLimit: 3,
    },
    {
      code: "FREEDELIVERY",
      type: "flat",
      value: 4,
      scope: "store",
      minOrderValue: 40,
      maxDiscount: 4,
      usageLimit: 400,
      perUserLimit: 1,
    },
  ],

  banners: [
    {
      title: "Fresh in every morning",
      subtitle: "Fruit and veg delivered daily",
      imageUrl:
        "https://images.unsplash.com/photo-1542838132-92c53300491e?w=1200&q=80",
      targetCategorySlug: "fruit-veg",
      sortOrder: 0,
      backgroundColor: "#1F6F4A",
    },
    {
      title: "Put the kettle on",
      subtitle: "Up to 15% off tea and ground coffee",
      imageUrl:
        "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=1200&q=80",
      targetCategorySlug: "tea-coffee",
      sortOrder: 1,
      backgroundColor: "#4A2C1A",
    },
    {
      title: "Something sweet",
      subtitle: "Chocolate and biscuits on offer",
      imageUrl:
        "https://images.unsplash.com/photo-1481391319762-47dff72954d9?w=1200&q=80",
      targetCategorySlug: "sweets-snacks",
      sortOrder: 2,
      backgroundColor: "#7A1F3D",
    },
    {
      title: "Stock the cupboard",
      subtitle: "Pasta, rice and tins in bigger packs",
      imageUrl:
        "https://images.unsplash.com/photo-1556909212-d5b604d0c90d?w=1200&q=80",
      targetCategorySlug: "food-cupboard",
      sortOrder: 3,
      backgroundColor: "#2A4C7A",
    },
  ],
};
