// The **United States** sample catalog — a realistic American supermarket
// (Kroger/Publix-style aisles, real US brands, $ retail pricing).
//
// Unlike the four European catalogs this one needs no new language pack: its
// copy is English, which the storefront already speaks. Only the catalog side
// was outstanding for the UK and US.
//
// Prices are Spanish shelf prices, NOT converted from another market. The
// storefront's price filter uses per-currency bands (2/5/10 for USD, same
// shape as euros — see
// cordelia's ProductPriceFilter), and a catalog that leaves a band empty makes
// that chip unmatchable; npm run verify:seed-bands enforces the spread.
//
// Image sources (every URL is verified live by scripts/verify-seed-images.mjs
// — re-run it whenever this file changes):
// - Products: real American product photos from Open Food Facts
//   (images.openfoodfacts.org) — © Open Food Facts contributors, CC-BY-SA
//   4.0. Barcodes were harvested from OFF's US catalogue and every path
//   re-resolved through its product endpoint, because the search index returns
//   unpadded paths and stale revisions for short codes. Loose produce and the
//   whole Household aisle carry imageUrl "" — OFF is a packaged-*food* database —
//   and every consumer renders a placeholder.
// - Banners: landscape photography from Unsplash.
// - Brand logos: Google's favicon endpoint / DiceBear monograms.

import {
  OFF_IMAGE_BASE,
  type GrocerySeed,
} from "./seed-types";

const IMG = OFF_IMAGE_BASE;

export const US_SEED: GrocerySeed = {
  categories: [
    {
      slug: "produce",
      name: "Produce",
      imageUrl: "",
      groupName: "Grocery",
    },
    {
      slug: "dairy-eggs",
      name: "Dairy & Eggs",
      imageUrl: `${IMG}/002/100/061/2239/front_en.60.400.jpg`,
      groupName: "Grocery",
    },
    {
      slug: "bakery-breakfast",
      name: "Bakery & Breakfast",
      imageUrl: `${IMG}/001/600/017/0032/front_en.47.400.jpg`,
      groupName: "Grocery",
    },
    {
      slug: "pantry",
      name: "Pantry",
      imageUrl: `${IMG}/005/100/002/5494/front_en.72.400.jpg`,
      groupName: "Grocery",
    },
    {
      slug: "condiments-sauces",
      name: "Condiments & Sauces",
      imageUrl: `${IMG}/004/800/121/3487/front_en.105.400.jpg`,
      groupName: "Grocery",
    },
    {
      slug: "frozen-meat",
      name: "Frozen & Meat",
      imageUrl: `${IMG}/007/192/121/4579/front_en.21.400.jpg`,
      groupName: "Grocery",
    },
    {
      slug: "snacks-candy",
      name: "Snacks & Candy",
      imageUrl: `${IMG}/002/840/019/9148/front_en.82.400.jpg`,
      groupName: "Snacks & Beverages",
    },
    {
      slug: "beverages",
      name: "Beverages & Water",
      imageUrl: `${IMG}/004/850/020/2746/front_en.11.400.jpg`,
      groupName: "Snacks & Beverages",
    },
    {
      slug: "coffee-tea",
      name: "Coffee & Tea",
      imageUrl: `${IMG}/002/550/088/7524/front_en.6.400.jpg`,
      groupName: "Snacks & Beverages",
    },
    {
      slug: "household",
      name: "Household & Cleaning",
      imageUrl: "",
      groupName: "Household",
    },
  ],

  brands: [
    { slug: "del-monte", name: "Del Monte", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://delmonte.com&size=128" },
    { slug: "land-o-lakes", name: "Land O'Lakes", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Land%20O'Lakes&size=128&fontWeight=600" },
    { slug: "philadelphia", name: "Philadelphia", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Philadelphia&size=128&fontWeight=600" },
    { slug: "sargento", name: "Sargento", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://sargento.com&size=128" },
    { slug: "kraft", name: "Kraft", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://kraftheinz.com&size=128" },
    { slug: "chobani", name: "Chobani", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://chobani.com&size=128" },
    { slug: "fage", name: "Fage", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Fage&size=128&fontWeight=600" },
    { slug: "dannon", name: "Dannon", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Dannon&size=128&fontWeight=600" },
    { slug: "silk", name: "Silk", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://silk.com&size=128" },
    { slug: "almond-breeze", name: "Almond Breeze", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Almond%20Breeze&size=128&fontWeight=600" },
    { slug: "oatly", name: "Oatly", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://oatly.com&size=128" },
    { slug: "daves-killer-bread", name: "Dave's Killer Bread", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Dave's%20Killer%20Bread&size=128&fontWeight=600" },
    { slug: "sara-lee", name: "Sara Lee", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Sara%20Lee&size=128&fontWeight=600" },
    { slug: "thomas", name: "Thomas'", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Thomas'&size=128&fontWeight=600" },
    { slug: "general-mills", name: "General Mills", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://generalmills.com&size=128" },
    { slug: "post", name: "Post", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Post&size=128&fontWeight=600" },
    { slug: "kelloggs", name: "Kellogg's", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Kellogg's&size=128&fontWeight=600" },
    { slug: "quaker", name: "Quaker", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://quakeroats.com&size=128" },
    { slug: "honey-maid", name: "Honey Maid", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Honey%20Maid&size=128&fontWeight=600" },
    { slug: "oreo", name: "Oreo", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://oreo.com&size=128" },
    { slug: "ritz", name: "Ritz", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Ritz&size=128&fontWeight=600" },
    { slug: "jif", name: "Jif", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Jif&size=128&fontWeight=600" },
    { slug: "smuckers", name: "Smucker's", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://smuckers.com&size=128" },
    { slug: "barilla", name: "Barilla", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://barilla.com&size=128" },
    { slug: "prego", name: "Prego", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Prego&size=128&fontWeight=600" },
    { slug: "raos", name: "Rao's", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Rao's&size=128&fontWeight=600" },
    { slug: "campbells", name: "Campbell's", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://campbells.com&size=128" },
    { slug: "hunts", name: "Hunt's", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Hunt's&size=128&fontWeight=600" },
    { slug: "domino", name: "Domino Sugar", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Domino%20Sugar&size=128&fontWeight=600" },
    { slug: "skippy", name: "Skippy", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Skippy&size=128&fontWeight=600" },
    { slug: "hellmanns", name: "Hellmann's", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Hellmann's&size=128&fontWeight=600" },
    { slug: "frenchs", name: "French's", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=French's&size=128&fontWeight=600" },
    { slug: "franks", name: "Frank's RedHot", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Frank's%20RedHot&size=128&fontWeight=600" },
    { slug: "hersheys", name: "Hershey's", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://hershey.com&size=128" },
    { slug: "digiorno", name: "DiGiorno", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=DiGiorno&size=128&fontWeight=600" },
    { slug: "stouffers", name: "Stouffer's", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Stouffer's&size=128&fontWeight=600" },
    { slug: "tyson", name: "Tyson", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://tyson.com&size=128" },
    { slug: "perdue", name: "Perdue", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://perdue.com&size=128" },
    { slug: "tillamook", name: "Tillamook", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://tillamook.com&size=128" },
    { slug: "haagen-dazs", name: "Häagen-Dazs", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Häagen-Dazs&size=128&fontWeight=600" },
    { slug: "ben-jerrys", name: "Ben & Jerry's", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://benjerry.com&size=128" },
    { slug: "snickers", name: "Snickers", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://snickers.com&size=128" },
    { slug: "lays", name: "Lay's", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Lay's&size=128&fontWeight=600" },
    { slug: "doritos", name: "Doritos", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://doritos.com&size=128" },
    { slug: "cheetos", name: "Cheetos", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Cheetos&size=128&fontWeight=600" },
    { slug: "pringles", name: "Pringles", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://pringles.com&size=128" },
    { slug: "goldfish", name: "Goldfish", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Goldfish&size=128&fontWeight=600" },
    { slug: "planters", name: "Planters", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Planters&size=128&fontWeight=600" },
    { slug: "reeses", name: "Reese's", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Reese's&size=128&fontWeight=600" },
    { slug: "nutella", name: "Nutella", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://nutella.com&size=128" },
    { slug: "lindt", name: "Lindt", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://lindtusa.com&size=128" },
    { slug: "haribo", name: "Haribo", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://haribo.com&size=128" },
    { slug: "tuc", name: "Tuc", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Tuc&size=128&fontWeight=600" },
    { slug: "milka", name: "Milka", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Milka&size=128&fontWeight=600" },
    { slug: "coca-cola", name: "Coca-Cola", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://coca-cola.com&size=128" },
    { slug: "dr-pepper", name: "Dr Pepper", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://drpepper.com&size=128" },
    { slug: "gatorade", name: "Gatorade", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://gatorade.com&size=128" },
    { slug: "dasani", name: "Dasani", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Dasani&size=128&fontWeight=600" },
    { slug: "aquafina", name: "Aquafina", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Aquafina&size=128&fontWeight=600" },
    { slug: "poland-spring", name: "Poland Spring", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Poland%20Spring&size=128&fontWeight=600" },
    { slug: "tropicana", name: "Tropicana", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Tropicana&size=128&fontWeight=600" },
    { slug: "minute-maid", name: "Minute Maid", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Minute%20Maid&size=128&fontWeight=600" },
    { slug: "ocean-spray", name: "Ocean Spray", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://oceanspray.com&size=128" },
    { slug: "snapple", name: "Snapple", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Snapple&size=128&fontWeight=600" },
    { slug: "folgers", name: "Folgers", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Folgers&size=128&fontWeight=600" },
    { slug: "starbucks", name: "Starbucks", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://starbucks.com&size=128" },
    { slug: "lavazza", name: "Lavazza", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://lavazza.com&size=128" },
    { slug: "twinings", name: "Twinings", logoUrl: "https://api.dicebear.com/9.x/initials/png?seed=Twinings&size=128&fontWeight=600" },
    { slug: "nescafe", name: "Nescafé", logoUrl: "https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://nescafe.com&size=128" },
  ],

  products: [
    {
      slug: "bananas",
      name: "Bananas",
      imageUrl: "",
      price: 1.75,
      unitValue: 1000,
      unitType: "g",
      description:
        "Sweet yellow bananas, ripe and ready to eat.",
      stock: 150,
      categorySlugs: ["produce"],
      isPopular: true,
    },
    {
      slug: "gala-apples",
      name: "Gala Apples",
      imageUrl: "",
      price: 3.49,
      unitValue: 1360,
      unitType: "g",
      description:
        "Crisp Gala apples, three pound bag.",
      stock: 120,
      categorySlugs: ["produce"],
      isPopular: true,
    },
    {
      slug: "roma-tomatoes",
      name: "Roma Tomatoes",
      imageUrl: "",
      price: 2.99,
      originalPrice: 3.49,
      unitValue: 1000,
      unitType: "g",
      description:
        "Firm Roma tomatoes, great for sauce and salads.",
      stock: 105,
      categorySlugs: ["produce"],
      isPopular: true,
    },
    {
      slug: "baby-carrots",
      name: "Baby Carrots",
      imageUrl: "",
      price: 1.29,
      unitValue: 454,
      unitType: "g",
      description:
        "Peeled baby carrots, washed and snack ready.",
      stock: 130,
      categorySlugs: ["produce"],
    },
    {
      slug: "russet-potatoes",
      name: "Russet Potatoes",
      imageUrl: "",
      price: 3.99,
      unitValue: 2270,
      unitType: "g",
      description:
        "Five pound bag of russet potatoes for baking and fries.",
      stock: 115,
      categorySlugs: ["produce"],
    },
    {
      slug: "yellow-onions",
      name: "Yellow Onions",
      imageUrl: "",
      price: 1.99,
      unitValue: 1360,
      unitType: "g",
      description:
        "Three pound bag of yellow onions.",
      stock: 125,
      categorySlugs: ["produce"],
    },
    {
      slug: "english-cucumber",
      name: "English Cucumber",
      imageUrl: "",
      price: 0.99,
      unitValue: 1,
      unitType: "pcs",
      description:
        "Seedless English cucumber, wrapped for freshness.",
      stock: 110,
      categorySlugs: ["produce"],
    },
    {
      slug: "romaine-hearts",
      name: "Romaine Hearts",
      imageUrl: "",
      price: 2.49,
      unitValue: 3,
      unitType: "pcs",
      description:
        "Three crisp romaine hearts, washed and trimmed.",
      stock: 95,
      categorySlugs: ["produce"],
    },
    {
      slug: "del-monte-pineapple",
      name: "Del Monte Pineapple Chunks",
      imageUrl: `${IMG}/002/400/000/1973/front_en.10.400.jpg`,
      price: 2.29,
      unitValue: 567,
      unitType: "g",
      description:
        "Pineapple chunks in their own juice, no sugar added.",
      stock: 120,
      categorySlugs: ["produce"],
      brandSlug: "del-monte",
    },
    {
      slug: "whole-milk",
      name: "Whole Milk",
      imageUrl: "",
      price: 3.79,
      unitValue: 3785,
      unitType: "ml",
      description:
        "One gallon of grade A whole milk.",
      stock: 160,
      categorySlugs: ["dairy-eggs"],
      sizeVariants: [
        { value: 3785, price: 3.79 },
        { value: 1890, price: 2.49 },
      ],
      isPopular: true,
    },
    {
      slug: "large-eggs",
      name: "Large Eggs",
      imageUrl: "",
      price: 3.99,
      unitValue: 12,
      unitType: "pcs",
      description:
        "One dozen grade A large eggs.",
      stock: 140,
      categorySlugs: ["dairy-eggs"],
      isPopular: true,
    },
    {
      slug: "land-o-lakes-butter",
      name: "Land O'Lakes Butter with Canola Oil",
      imageUrl: `${IMG}/003/450/015/1191/front_en.45.400.jpg`,
      price: 4.99,
      unitValue: 425,
      unitType: "g",
      description:
        "Spreadable butter blended with canola oil.",
      stock: 100,
      categorySlugs: ["dairy-eggs"],
      brandSlug: "land-o-lakes",
      isPopular: true,
    },
    {
      slug: "philadelphia-cream-cheese",
      name: "Philadelphia Original Cream Cheese",
      imageUrl: `${IMG}/002/100/061/2239/front_en.60.400.jpg`,
      price: 3.49,
      unitValue: 226,
      unitType: "g",
      description:
        "The original brick cream cheese, rich and creamy.",
      stock: 115,
      categorySlugs: ["dairy-eggs"],
      brandSlug: "philadelphia",
      isPopular: true,
    },
    {
      slug: "sargento-swiss",
      name: "Sargento Sliced Swiss Cheese",
      imageUrl: `${IMG}/004/610/000/1653/front_en.10.400.jpg`,
      price: 3.99,
      unitValue: 198,
      unitType: "g",
      description:
        "Natural Swiss cheese, sliced for sandwiches.",
      stock: 95,
      categorySlugs: ["dairy-eggs"],
      brandSlug: "sargento",
    },
    {
      slug: "kraft-parmesan",
      name: "Kraft 100% Grated Parmesan",
      imageUrl: `${IMG}/002/100/001/0615/front_en.45.400.jpg`,
      price: 6.49,
      originalPrice: 7.29,
      unitValue: 680,
      unitType: "g",
      description:
        "Grated parmesan cheese in a shaker canister.",
      stock: 80,
      categorySlugs: ["dairy-eggs"],
      brandSlug: "kraft",
    },
    {
      slug: "chobani-nonfat",
      name: "Chobani Nonfat Greek Yogurt",
      imageUrl: `${IMG}/089/470/001/0137/front_en.838.400.jpg`,
      price: 5.49,
      unitValue: 907,
      unitType: "g",
      description:
        "Plain nonfat Greek yogurt, thick and high in protein.",
      stock: 100,
      categorySlugs: ["dairy-eggs"],
      brandSlug: "chobani",
      isPopular: true,
    },
    {
      slug: "fage-total",
      name: "Fage Total 5%",
      imageUrl: `${IMG}/068/954/408/3009/front_en.110.400.jpg`,
      price: 5.99,
      unitValue: 907,
      unitType: "g",
      description:
        "Strained whole milk Greek yogurt, rich and tangy.",
      stock: 85,
      categorySlugs: ["dairy-eggs"],
      brandSlug: "fage",
    },
    {
      slug: "dannon-greek",
      name: "Dannon Original Greek Nonfat",
      imageUrl: `${IMG}/003/663/203/2737/front_en.80.400.jpg`,
      price: 1.29,
      unitValue: 150,
      unitType: "g",
      description:
        "Single serve nonfat Greek yogurt.",
      stock: 130,
      categorySlugs: ["dairy-eggs"],
      brandSlug: "dannon",
    },
    {
      slug: "silk-almond-yogurt",
      name: "Silk Almondmilk Yogurt Vanilla",
      imageUrl: `${IMG}/002/529/300/3972/front_en.50.400.jpg`,
      price: 1.99,
      unitValue: 150,
      unitType: "g",
      description:
        "Dairy free almondmilk yogurt alternative, vanilla.",
      stock: 90,
      categorySlugs: ["dairy-eggs"],
      brandSlug: "silk",
    },
    {
      slug: "almond-breeze",
      name: "Almond Breeze Unsweetened Almondmilk",
      imageUrl: `${IMG}/004/157/005/4130/front_en.52.400.jpg`,
      price: 3.49,
      unitValue: 946,
      unitType: "ml",
      description:
        "Unsweetened almondmilk, only 30 calories a cup.",
      stock: 105,
      categorySlugs: ["dairy-eggs"],
      brandSlug: "almond-breeze",
    },
    {
      slug: "oatly-full-fat",
      name: "Oatly Oatmilk Full Fat",
      imageUrl: `${IMG}/019/064/663/0089/front_en.93.400.jpg`,
      price: 4.99,
      unitValue: 1420,
      unitType: "ml",
      description:
        "Full fat oatmilk that behaves like dairy in coffee.",
      stock: 90,
      categorySlugs: ["dairy-eggs"],
      brandSlug: "oatly",
      isPopular: true,
    },
    {
      slug: "daves-killer-bread",
      name: "Dave's Killer Bread 21 Whole Grains",
      imageUrl: `${IMG}/001/376/402/7053/front_en.527.400.jpg`,
      price: 5.99,
      originalPrice: 6.79,
      unitValue: 765,
      unitType: "g",
      description:
        "Organic 21 whole grains and seeds bread.",
      stock: 95,
      categorySlugs: ["bakery-breakfast"],
      brandSlug: "daves-killer-bread",
      isPopular: true,
    },
    {
      slug: "sara-lee-multigrain",
      name: "Sara Lee Healthy Multi-Grain Bread",
      imageUrl: `${IMG}/007/294/571/5882/front_en.122.400.jpg`,
      price: 3.99,
      unitValue: 567,
      unitType: "g",
      description:
        "Soft multi-grain sandwich bread.",
      stock: 110,
      categorySlugs: ["bakery-breakfast"],
      brandSlug: "sara-lee",
    },
    {
      slug: "thomas-bagels",
      name: "Thomas' Plain Bagels",
      imageUrl: `${IMG}/004/812/127/7079/front_en.156.400.jpg`,
      price: 4.49,
      unitValue: 567,
      unitType: "g",
      description:
        "Six plain New York style bagels, pre-sliced.",
      stock: 100,
      categorySlugs: ["bakery-breakfast"],
      brandSlug: "thomas",
      isPopular: true,
    },
    {
      slug: "cheerios",
      name: "General Mills Cheerios",
      imageUrl: `${IMG}/001/600/017/0032/front_en.47.400.jpg`,
      price: 5.49,
      unitValue: 510,
      unitType: "g",
      description:
        "The original whole grain oat cereal.",
      stock: 120,
      categorySlugs: ["bakery-breakfast"],
      brandSlug: "general-mills",
      isPopular: true,
    },
    {
      slug: "post-great-grains",
      name: "Post Great Grains Raisins & Dates",
      imageUrl: `${IMG}/088/491/212/6115/front_en.77.400.jpg`,
      price: 4.99,
      unitValue: 453,
      unitType: "g",
      description:
        "Whole grain cereal with raisins, dates and pecans.",
      stock: 85,
      categorySlugs: ["bakery-breakfast"],
      brandSlug: "post",
    },
    {
      slug: "kelloggs-coco-pops",
      name: "Kellogg's Coco Pops",
      imageUrl: `${IMG}/505/931/902/4479/front_en.13.400.jpg`,
      price: 4.49,
      unitValue: 375,
      unitType: "g",
      description:
        "Chocolatey rice cereal that turns the milk brown.",
      stock: 95,
      categorySlugs: ["bakery-breakfast"],
      brandSlug: "kelloggs",
    },
    {
      slug: "quaker-oats",
      name: "Quaker Quick Cooking Oats",
      imageUrl: `${IMG}/500/010/802/2824/front_en.8.400.jpg`,
      price: 4.29,
      unitValue: 500,
      unitType: "g",
      description:
        "Quick cooking oats, ready in three minutes.",
      stock: 115,
      categorySlugs: ["bakery-breakfast"],
      brandSlug: "quaker",
    },
    {
      slug: "honey-maid-grahams",
      name: "Honey Maid Graham Crackers",
      imageUrl: `${IMG}/004/400/000/4637/front_en.104.400.jpg`,
      price: 4.49,
      unitValue: 408,
      unitType: "g",
      description:
        "Honey graham crackers — the base of every s'more.",
      stock: 105,
      categorySlugs: ["bakery-breakfast"],
      brandSlug: "honey-maid",
    },
    {
      slug: "oreo-original",
      name: "Oreo Original",
      imageUrl: `${IMG}/762/221/002/1502/front_en.47.400.jpg`,
      price: 4.29,
      unitValue: 220,
      unitType: "g",
      description:
        "Chocolate sandwich cookies with creme filling.",
      stock: 130,
      categorySlugs: ["bakery-breakfast"],
      brandSlug: "oreo",
      isPopular: true,
    },
    {
      slug: "ritz-crackers",
      name: "Ritz Original Crackers",
      imageUrl: `${IMG}/500/013/748/7908/front_en.38.400.jpg`,
      price: 4.49,
      unitValue: 200,
      unitType: "g",
      description:
        "Buttery round crackers, flaky and golden.",
      stock: 110,
      categorySlugs: ["bakery-breakfast"],
      brandSlug: "ritz",
    },
    {
      slug: "jif-peanut-butter",
      name: "Jif Natural Creamy Peanut Butter",
      imageUrl: `${IMG}/005/150/025/5650/front_en.141.400.jpg`,
      price: 3.99,
      unitValue: 454,
      unitType: "g",
      description:
        "Natural creamy peanut butter made with real peanuts.",
      stock: 120,
      categorySlugs: ["bakery-breakfast"],
      brandSlug: "jif",
      isPopular: true,
    },
    {
      slug: "smuckers-strawberry",
      name: "Smucker's Natural Strawberry Fruit Spread",
      imageUrl: `${IMG}/005/150/014/1724/front_en.34.400.jpg`,
      price: 4.29,
      unitValue: 539,
      unitType: "g",
      description:
        "Natural strawberry fruit spread, no high fructose corn syrup.",
      stock: 100,
      categorySlugs: ["bakery-breakfast"],
      brandSlug: "smuckers",
    },
    {
      slug: "barilla-spaghetti",
      name: "Barilla Spaghetti",
      imageUrl: `${IMG}/807/680/019/5057/front_en.3809.400.jpg`,
      price: 1.99,
      unitValue: 500,
      unitType: "g",
      description:
        "Classic spaghetti, al dente in nine minutes.",
      stock: 150,
      categorySlugs: ["pantry"],
      brandSlug: "barilla",
      sizeVariants: [
        { value: 500, price: 1.99 },
        { value: 1000, price: 3.59 },
      ],
      isPopular: true,
    },
    {
      slug: "prego-traditional",
      name: "Prego Traditional Italian Sauce",
      imageUrl: `${IMG}/005/100/002/5494/front_en.72.400.jpg`,
      price: 3.29,
      unitValue: 680,
      unitType: "g",
      description:
        "Traditional Italian pasta sauce made with vine ripened tomatoes.",
      stock: 130,
      categorySlugs: ["pantry"],
      brandSlug: "prego",
      isPopular: true,
    },
    {
      slug: "raos-marinara",
      name: "Rao's Homemade Marinara Sauce",
      imageUrl: `${IMG}/074/747/900/0413/front_en.71.400.jpg`,
      price: 8.99,
      unitValue: 790,
      unitType: "g",
      description:
        "Slow simmered marinara with Italian tomatoes and olive oil.",
      stock: 75,
      categorySlugs: ["pantry"],
      brandSlug: "raos",
      isPopular: true,
    },
    {
      slug: "campbells-cream-chicken",
      name: "Campbell's Cream of Chicken Soup",
      imageUrl: `${IMG}/005/100/001/0315/front_en.60.400.jpg`,
      price: 2.29,
      unitValue: 298,
      unitType: "g",
      description:
        "Condensed cream of chicken soup for casseroles.",
      stock: 140,
      categorySlugs: ["pantry"],
      brandSlug: "campbells",
    },
    {
      slug: "kraft-mac-cheese",
      name: "Kraft Macaroni & Cheese Original",
      imageUrl: `${IMG}/002/100/065/8831/front_en.226.400.jpg`,
      price: 1.79,
      unitValue: 206,
      unitType: "g",
      description:
        "The blue box — macaroni and cheese in seven minutes.",
      stock: 160,
      categorySlugs: ["pantry"],
      brandSlug: "kraft",
      isPopular: true,
    },
    {
      slug: "hunts-ketchup",
      name: "Hunt's Tomato Ketchup",
      imageUrl: `${IMG}/002/700/038/1434/front_en.19.400.jpg`,
      price: 2.99,
      unitValue: 567,
      unitType: "g",
      description:
        "Tomato ketchup made with 100% vine ripened tomatoes.",
      stock: 135,
      categorySlugs: ["pantry"],
      brandSlug: "hunts",
    },
    {
      slug: "domino-sugar",
      name: "Domino Granulated Sugar",
      imageUrl: `${IMG}/004/920/004/5503/front_en.22.400.jpg`,
      price: 3.99,
      unitValue: 1814,
      unitType: "g",
      description:
        "Four pounds of pure cane granulated sugar.",
      stock: 120,
      categorySlugs: ["pantry"],
      brandSlug: "domino",
    },
    {
      slug: "skippy-peanut-butter",
      name: "Skippy Creamy Peanut Butter",
      imageUrl: `${IMG}/003/760/022/3324/front_en.144.400.jpg`,
      price: 7.49,
      unitValue: 1360,
      unitType: "g",
      description:
        "Creamy peanut butter in the three pound jar.",
      stock: 90,
      categorySlugs: ["pantry"],
      brandSlug: "skippy",
    },
    {
      slug: "long-grain-rice",
      name: "Long Grain White Rice",
      imageUrl: "",
      price: 3.49,
      unitValue: 907,
      unitType: "g",
      description:
        "Two pounds of long grain white rice.",
      stock: 125,
      categorySlugs: ["pantry"],
    },
    {
      slug: "all-purpose-flour",
      name: "All Purpose Flour",
      imageUrl: "",
      price: 3.29,
      unitValue: 2270,
      unitType: "g",
      description:
        "Five pounds of enriched all purpose flour.",
      stock: 115,
      categorySlugs: ["pantry"],
    },
    {
      slug: "black-beans",
      name: "Canned Black Beans",
      imageUrl: "",
      price: 1.29,
      unitValue: 425,
      unitType: "g",
      description:
        "Black beans in water, no salt added.",
      stock: 145,
      categorySlugs: ["pantry"],
    },
    {
      slug: "hellmanns-mayonnaise",
      name: "Hellmann's Real Mayonnaise",
      imageUrl: `${IMG}/004/800/121/3487/front_en.105.400.jpg`,
      price: 5.49,
      originalPrice: 6.29,
      unitValue: 887,
      unitType: "ml",
      description:
        "Real mayonnaise made with cage free eggs.",
      stock: 110,
      categorySlugs: ["condiments-sauces"],
      brandSlug: "hellmanns",
      isPopular: true,
    },
    {
      slug: "frenchs-mustard",
      name: "French's Classic Yellow Mustard",
      imageUrl: `${IMG}/004/150/000/0251/front_en.52.400.jpg`,
      price: 2.79,
      unitValue: 397,
      unitType: "g",
      description:
        "Classic yellow mustard made with stone ground seed.",
      stock: 130,
      categorySlugs: ["condiments-sauces"],
      brandSlug: "frenchs",
      isPopular: true,
    },
    {
      slug: "franks-red-hot",
      name: "Frank's RedHot Original",
      imageUrl: `${IMG}/004/150/088/8125/front_en.58.400.jpg`,
      price: 3.49,
      unitValue: 148,
      unitType: "ml",
      description:
        "The original cayenne pepper sauce — put that on everything.",
      stock: 120,
      categorySlugs: ["condiments-sauces"],
      brandSlug: "franks",
    },
    {
      slug: "hersheys-syrup",
      name: "Hershey's Chocolate Syrup",
      imageUrl: `${IMG}/000/000/343/1209/front_en.142.400.jpg`,
      price: 3.29,
      unitValue: 680,
      unitType: "g",
      description:
        "Chocolate syrup for milk, ice cream and sundaes.",
      stock: 115,
      categorySlugs: ["condiments-sauces"],
      brandSlug: "hersheys",
    },
    {
      slug: "olive-oil",
      name: "Extra Virgin Olive Oil",
      imageUrl: "",
      price: 9.99,
      unitValue: 500,
      unitType: "ml",
      description:
        "Cold pressed extra virgin olive oil.",
      stock: 85,
      categorySlugs: ["condiments-sauces"],
    },
    {
      slug: "vegetable-oil",
      name: "Vegetable Oil",
      imageUrl: "",
      price: 4.29,
      unitValue: 1420,
      unitType: "ml",
      description:
        "Forty-eight ounces of vegetable oil for frying and baking.",
      stock: 100,
      categorySlugs: ["condiments-sauces"],
    },
    {
      slug: "table-salt",
      name: "Iodized Table Salt",
      imageUrl: "",
      price: 1.19,
      unitValue: 737,
      unitType: "g",
      description:
        "Iodized table salt in the classic canister.",
      stock: 135,
      categorySlugs: ["condiments-sauces"],
    },
    {
      slug: "black-pepper",
      name: "Ground Black Pepper",
      imageUrl: "",
      price: 3.49,
      unitValue: 85,
      unitType: "g",
      description:
        "Ground black pepper, bold and aromatic.",
      stock: 105,
      categorySlugs: ["condiments-sauces"],
    },
    {
      slug: "digiorno-four-cheese",
      name: "DiGiorno Rising Crust Four Cheese",
      imageUrl: `${IMG}/007/192/121/4579/front_en.21.400.jpg`,
      price: 7.99,
      originalPrice: 8.99,
      unitValue: 800,
      unitType: "g",
      description:
        "Rising crust four cheese pizza that bakes like delivery.",
      stock: 90,
      categorySlugs: ["frozen-meat"],
      brandSlug: "digiorno",
      isPopular: true,
    },
    {
      slug: "stouffers-french-bread-pizza",
      name: "Stouffer's French Bread Pizza",
      imageUrl: `${IMG}/001/380/098/7983/front_en.10.400.jpg`,
      price: 4.49,
      unitValue: 350,
      unitType: "g",
      description:
        "Two french bread pizzas, crisp on the bottom.",
      stock: 95,
      categorySlugs: ["frozen-meat"],
      brandSlug: "stouffers",
    },
    {
      slug: "tyson-chicken-patties",
      name: "Tyson Breaded Chicken Patties",
      imageUrl: `${IMG}/002/370/001/4528/front_en.69.400.jpg`,
      price: 9.99,
      unitValue: 822,
      unitType: "g",
      description:
        "Fully cooked breaded chicken patties, ready in the oven.",
      stock: 80,
      categorySlugs: ["frozen-meat"],
      brandSlug: "tyson",
      isPopular: true,
    },
    {
      slug: "perdue-chicken-tenders",
      name: "Perdue Simply Smart Chicken Tenders",
      imageUrl: `${IMG}/007/274/580/4892/front_en.27.400.jpg`,
      price: 8.99,
      unitValue: 623,
      unitType: "g",
      description:
        "Gluten free breaded chicken tenders, organic.",
      stock: 75,
      categorySlugs: ["frozen-meat"],
      brandSlug: "perdue",
    },
    {
      slug: "tillamook-pepperoni-pizza",
      name: "Tillamook Uncured Pepperoni Stone Baked",
      imageUrl: `${IMG}/081/006/772/6412/front_en.3.400.jpg`,
      price: 6.49,
      unitValue: 400,
      unitType: "g",
      description:
        "Stone baked pepperoni pizza with real Tillamook cheese.",
      stock: 70,
      categorySlugs: ["frozen-meat"],
      brandSlug: "tillamook",
    },
    {
      slug: "haagen-dazs-vanilla",
      name: "Häagen-Dazs Vanilla Ice Cream",
      imageUrl: `${IMG}/007/457/000/7004/front_en.4.400.jpg`,
      price: 5.99,
      unitValue: 828,
      unitType: "ml",
      description:
        "Vanilla ice cream made with five simple ingredients.",
      stock: 85,
      categorySlugs: ["frozen-meat"],
      brandSlug: "haagen-dazs",
      isPopular: true,
    },
    {
      slug: "ben-jerrys-half-baked",
      name: "Ben & Jerry's Half Baked",
      imageUrl: `${IMG}/007/684/010/1535/front_en.9.400.jpg`,
      price: 5.49,
      unitValue: 473,
      unitType: "ml",
      description:
        "Chocolate and vanilla with cookie dough and brownies.",
      stock: 90,
      categorySlugs: ["frozen-meat"],
      brandSlug: "ben-jerrys",
      isPopular: true,
    },
    {
      slug: "snickers-ice-cream",
      name: "Snickers Ice Cream Bars",
      imageUrl: `${IMG}/500/015/954/8496/front_en.60.400.jpg`,
      price: 5.99,
      unitValue: 4,
      unitType: "pcs",
      description:
        "Four Snickers ice cream bars.",
      stock: 80,
      categorySlugs: ["frozen-meat"],
      brandSlug: "snickers",
    },
    {
      slug: "frozen-peas",
      name: "Frozen Sweet Peas",
      imageUrl: "",
      price: 1.99,
      unitValue: 454,
      unitType: "g",
      description:
        "Sweet peas frozen at peak freshness.",
      stock: 110,
      categorySlugs: ["frozen-meat"],
    },
    {
      slug: "frozen-broccoli",
      name: "Frozen Broccoli Florets",
      imageUrl: "",
      price: 2.29,
      unitValue: 340,
      unitType: "g",
      description:
        "Broccoli florets, steam in bag.",
      stock: 100,
      categorySlugs: ["frozen-meat"],
    },
    {
      slug: "lays-classic",
      name: "Lay's Classic Potato Chips",
      imageUrl: `${IMG}/002/840/019/9148/front_en.82.400.jpg`,
      price: 4.99,
      originalPrice: 5.49,
      unitValue: 226,
      unitType: "g",
      description:
        "Classic potato chips — three ingredients, nothing else.",
      stock: 140,
      categorySlugs: ["snacks-candy"],
      brandSlug: "lays",
      isPopular: true,
    },
    {
      slug: "doritos-nacho-cheese",
      name: "Doritos Nacho Cheese",
      imageUrl: `${IMG}/590/025/909/4704/front_en.62.400.jpg`,
      price: 4.49,
      unitValue: 100,
      unitType: "g",
      description:
        "Nacho cheese flavored tortilla chips.",
      stock: 135,
      categorySlugs: ["snacks-candy"],
      brandSlug: "doritos",
      isPopular: true,
    },
    {
      slug: "cheetos-crunchy",
      name: "Cheetos Crunchy",
      imageUrl: `${IMG}/002/840/004/0112/front_en.292.400.jpg`,
      price: 4.49,
      unitValue: 226,
      unitType: "g",
      description:
        "Crunchy cheese flavored snacks. Dangerously cheesy.",
      stock: 130,
      categorySlugs: ["snacks-candy"],
      brandSlug: "cheetos",
    },
    {
      slug: "pringles-sour-cream",
      name: "Pringles Sour Cream & Onion",
      imageUrl: `${IMG}/003/800/013/8430/front_en.93.400.jpg`,
      price: 2.49,
      unitValue: 156,
      unitType: "g",
      description:
        "Sour cream and onion crisps in the classic can.",
      stock: 125,
      categorySlugs: ["snacks-candy"],
      brandSlug: "pringles",
    },
    {
      slug: "goldfish-cheddar",
      name: "Goldfish Xtra Cheddar",
      imageUrl: `${IMG}/001/410/008/5485/front_en.89.400.jpg`,
      price: 3.99,
      unitValue: 187,
      unitType: "g",
      description:
        "The snack that smiles back — extra cheddar.",
      stock: 120,
      categorySlugs: ["snacks-candy"],
      brandSlug: "goldfish",
      isPopular: true,
    },
    {
      slug: "planters-peanuts",
      name: "Planters Cocktail Peanuts",
      imageUrl: `${IMG}/002/900/007/2107/front_en.25.400.jpg`,
      price: 4.49,
      unitValue: 454,
      unitType: "g",
      description:
        "Cocktail peanuts roasted in peanut oil and sea salt.",
      stock: 105,
      categorySlugs: ["snacks-candy"],
      brandSlug: "planters",
    },
    {
      slug: "reeses-cups",
      name: "Reese's Peanut Butter Cups",
      imageUrl: `${IMG}/000/000/344/4009/front_en.142.400.jpg`,
      price: 1.79,
      unitValue: 42,
      unitType: "g",
      description:
        "Two peanut butter cups — there's no wrong way.",
      stock: 180,
      categorySlugs: ["snacks-candy"],
      brandSlug: "reeses",
      isPopular: true,
    },
    {
      slug: "nutella",
      name: "Nutella Hazelnut Spread",
      imageUrl: `${IMG}/301/762/042/5035/front_en.583.400.jpg`,
      price: 8.99,
      unitValue: 1000,
      unitType: "g",
      description:
        "Hazelnut spread with cocoa, in the big jar.",
      stock: 85,
      categorySlugs: ["snacks-candy"],
      brandSlug: "nutella",
    },
    {
      slug: "lindt-excellence-70",
      name: "Lindt Excellence 70% Dark",
      imageUrl: `${IMG}/304/692/002/2651/front_en.159.400.jpg`,
      price: 3.49,
      unitValue: 100,
      unitType: "g",
      description:
        "Intense dark chocolate with 70% cocoa.",
      stock: 95,
      categorySlugs: ["snacks-candy"],
      brandSlug: "lindt",
    },
    {
      slug: "haribo-goldbears",
      name: "Haribo Goldbears",
      imageUrl: `${IMG}/900/297/530/1558/front_en.16.400.jpg`,
      price: 2.49,
      unitValue: 100,
      unitType: "g",
      description:
        "The original gummi bears in five fruit flavors.",
      stock: 140,
      categorySlugs: ["snacks-candy"],
      brandSlug: "haribo",
    },
    {
      slug: "tuc-crackers",
      name: "Tuc Cheese Crackers",
      imageUrl: `${IMG}/762/230/057/1351/front_en.156.400.jpg`,
      price: 2.29,
      unitValue: 100,
      unitType: "g",
      description:
        "Salted crackers with a cheese flavor.",
      stock: 100,
      categorySlugs: ["snacks-candy"],
      brandSlug: "tuc",
    },
    {
      slug: "milka-cake-choc",
      name: "Milka Cake & Choc",
      imageUrl: `${IMG}/762/230/078/4751/front_de.111.400.jpg`,
      price: 2.99,
      unitValue: 175,
      unitType: "g",
      description:
        "Soft cakes with a Milka chocolate center.",
      stock: 90,
      categorySlugs: ["snacks-candy"],
      brandSlug: "milka",
    },
    {
      slug: "diet-coke",
      name: "Diet Coke",
      imageUrl: `${IMG}/000/000/496/5802/front_en.95.400.jpg`,
      price: 0.99,
      unitValue: 355,
      unitType: "ml",
      description:
        "Diet Coke in a can, crisp and cold.",
      stock: 220,
      categorySlugs: ["beverages"],
      brandSlug: "coca-cola",
      sizeVariants: [
        { value: 355, price: 0.99 },
        { value: 2000, price: 2.79 },
      ],
      isPopular: true,
    },
    {
      slug: "dr-pepper",
      name: "Dr Pepper",
      imageUrl: `${IMG}/000/000/783/1504/front_en.222.400.jpg`,
      price: 1.09,
      unitValue: 355,
      unitType: "ml",
      description:
        "Twenty-three flavors in every can.",
      stock: 200,
      categorySlugs: ["beverages"],
      brandSlug: "dr-pepper",
      isPopular: true,
    },
    {
      slug: "gatorade-lemon-lime",
      name: "Gatorade Lemon-Lime Thirst Quencher",
      imageUrl: `${IMG}/005/200/032/8684/front_en.45.400.jpg`,
      price: 1.29,
      unitValue: 828,
      unitType: "ml",
      description:
        "Lemon-lime sports drink with electrolytes.",
      stock: 175,
      categorySlugs: ["beverages"],
      brandSlug: "gatorade",
      isPopular: true,
    },
    {
      slug: "dasani",
      name: "Dasani Purified Water",
      imageUrl: `${IMG}/004/900/002/7624/front_en.38.400.jpg`,
      price: 1.19,
      unitValue: 500,
      unitType: "ml",
      description:
        "Purified water enhanced with minerals.",
      stock: 210,
      categorySlugs: ["beverages"],
      brandSlug: "dasani",
    },
    {
      slug: "aquafina",
      name: "Aquafina Purified Water",
      imageUrl: `${IMG}/000/000/121/0806/front_en.33.400.jpg`,
      price: 1.19,
      unitValue: 500,
      unitType: "ml",
      description:
        "Purified drinking water, pure and simple.",
      stock: 205,
      categorySlugs: ["beverages"],
      brandSlug: "aquafina",
    },
    {
      slug: "poland-spring",
      name: "Poland Spring Natural Spring Water",
      imageUrl: `${IMG}/007/572/000/0814/front_en.31.400.jpg`,
      price: 1.29,
      unitValue: 500,
      unitType: "ml",
      description:
        "Natural spring water sourced in Maine.",
      stock: 195,
      categorySlugs: ["beverages"],
      brandSlug: "poland-spring",
    },
    {
      slug: "tropicana-orange",
      name: "Tropicana Pure Premium Orange Juice",
      imageUrl: `${IMG}/004/850/020/2746/front_en.11.400.jpg`,
      price: 4.99,
      originalPrice: 5.79,
      unitValue: 1750,
      unitType: "ml",
      description:
        "Not from concentrate orange juice, original no pulp.",
      stock: 120,
      categorySlugs: ["beverages"],
      brandSlug: "tropicana",
      isPopular: true,
    },
    {
      slug: "minute-maid-aguas",
      name: "Minute Maid Aguas Frescas",
      imageUrl: `${IMG}/002/500/013/1387/front_en.29.400.jpg`,
      price: 1.49,
      unitValue: 473,
      unitType: "ml",
      description:
        "Aguas frescas with real fruit juice.",
      stock: 140,
      categorySlugs: ["beverages"],
      brandSlug: "minute-maid",
    },
    {
      slug: "ocean-spray-cranberry",
      name: "Ocean Spray Cranberry Juice Cocktail",
      imageUrl: `${IMG}/003/120/020/0075/front_en.31.400.jpg`,
      price: 3.99,
      unitValue: 1890,
      unitType: "ml",
      description:
        "Cranberry juice cocktail, tart and refreshing.",
      stock: 115,
      categorySlugs: ["beverages"],
      brandSlug: "ocean-spray",
    },
    {
      slug: "snapple-apple",
      name: "Snapple Apple",
      imageUrl: `${IMG}/007/618/320/2081/front_en.12.400.jpg`,
      price: 1.79,
      unitValue: 473,
      unitType: "ml",
      description:
        "Made from the best stuff on earth.",
      stock: 150,
      categorySlugs: ["beverages"],
      brandSlug: "snapple",
    },
    {
      slug: "folgers-classic-roast",
      name: "Folgers Classic Roast Ground Coffee",
      imageUrl: `${IMG}/002/550/088/7524/front_en.6.400.jpg`,
      price: 12.99,
      originalPrice: 14.49,
      unitValue: 1446,
      unitType: "g",
      description:
        "The best part of waking up — 51 ounces of classic roast.",
      stock: 80,
      categorySlugs: ["coffee-tea"],
      brandSlug: "folgers",
      isPopular: true,
    },
    {
      slug: "starbucks-espresso-cream",
      name: "Starbucks Espresso and Cream",
      imageUrl: `${IMG}/000/000/121/7702/front_en.52.400.jpg`,
      price: 2.49,
      unitValue: 400,
      unitType: "ml",
      description:
        "Chilled espresso beverage with cream, ready to drink.",
      stock: 130,
      categorySlugs: ["coffee-tea"],
      brandSlug: "starbucks",
      isPopular: true,
    },
    {
      slug: "lavazza-qualita-rossa",
      name: "Lavazza Qualità Rossa Ground",
      imageUrl: `${IMG}/800/007/003/6864/front_en.7.400.jpg`,
      price: 8.99,
      unitValue: 250,
      unitType: "g",
      description:
        "Italian ground coffee with a full, chocolatey body.",
      stock: 85,
      categorySlugs: ["coffee-tea"],
      brandSlug: "lavazza",
    },
    {
      slug: "nescafe-azera",
      name: "Nescafé Azera Americano",
      imageUrl: `${IMG}/844/529/004/4822/front_en.3.400.jpg`,
      price: 7.49,
      unitValue: 90,
      unitType: "g",
      description:
        "Barista style instant coffee with a fine crema.",
      stock: 90,
      categorySlugs: ["coffee-tea"],
      brandSlug: "nescafe",
    },
    {
      slug: "twinings-lemon-ginger",
      name: "Twinings Lemon & Ginger",
      imageUrl: `${IMG}/007/017/707/5101/front_en.27.400.jpg`,
      price: 3.99,
      unitValue: 20,
      unitType: "pcs",
      description:
        "Twenty lemon and ginger herbal tea bags, caffeine free.",
      stock: 100,
      categorySlugs: ["coffee-tea"],
      brandSlug: "twinings",
    },
    {
      slug: "ground-coffee",
      name: "Ground Coffee Medium Roast",
      imageUrl: "",
      price: 8.99,
      unitValue: 340,
      unitType: "g",
      description:
        "Twelve ounces of medium roast ground coffee.",
      stock: 95,
      categorySlugs: ["coffee-tea"],
    },
    {
      slug: "k-cup-pods",
      name: "Coffee Pods Variety Pack",
      imageUrl: "",
      price: 11.99,
      unitValue: 24,
      unitType: "pcs",
      description:
        "Twenty-four single serve coffee pods, variety pack.",
      stock: 85,
      categorySlugs: ["coffee-tea"],
    },
    {
      slug: "green-tea-bags",
      name: "Green Tea Bags",
      imageUrl: "",
      price: 3.49,
      unitValue: 40,
      unitType: "pcs",
      description:
        "Forty green tea bags, smooth and light.",
      stock: 105,
      categorySlugs: ["coffee-tea"],
    },
    {
      slug: "dish-soap",
      name: "Dish Soap",
      imageUrl: "",
      price: 2.49,
      unitValue: 532,
      unitType: "ml",
      description:
        "Concentrated dish soap that cuts through grease.",
      stock: 125,
      categorySlugs: ["household"],
    },
    {
      slug: "all-purpose-cleaner",
      name: "All Purpose Cleaner",
      imageUrl: "",
      price: 3.49,
      unitValue: 946,
      unitType: "ml",
      description:
        "All purpose spray cleaner for kitchens and baths.",
      stock: 110,
      categorySlugs: ["household"],
    },
    {
      slug: "paper-towels",
      name: "Paper Towels",
      imageUrl: "",
      price: 8.99,
      unitValue: 6,
      unitType: "pcs",
      description:
        "Six mega rolls of two ply paper towels.",
      stock: 130,
      categorySlugs: ["household"],
      isPopular: true,
    },
    {
      slug: "toilet-paper",
      name: "Toilet Paper",
      imageUrl: "",
      price: 9.99,
      originalPrice: 11.49,
      unitValue: 12,
      unitType: "pcs",
      description:
        "Twelve mega rolls of soft two ply bath tissue.",
      stock: 135,
      categorySlugs: ["household"],
      isPopular: true,
    },
    {
      slug: "trash-bags",
      name: "Tall Kitchen Trash Bags",
      imageUrl: "",
      price: 6.99,
      unitValue: 40,
      unitType: "pcs",
      description:
        "Forty thirteen gallon drawstring trash bags.",
      stock: 115,
      categorySlugs: ["household"],
    },
    {
      slug: "laundry-detergent",
      name: "Laundry Detergent",
      imageUrl: "",
      price: 13.99,
      originalPrice: 15.99,
      unitValue: 2950,
      unitType: "ml",
      description:
        "Liquid laundry detergent for 64 loads.",
      stock: 75,
      categorySlugs: ["household"],
      isPopular: true,
    },
    {
      slug: "dishwasher-pods",
      name: "Dishwasher Detergent Pods",
      imageUrl: "",
      price: 12.49,
      unitValue: 62,
      unitType: "pcs",
      description:
        "Sixty-two dishwasher pods with rinse aid built in.",
      stock: 80,
      categorySlugs: ["household"],
    },
    {
      slug: "toothpaste",
      name: "Toothpaste Cavity Protection",
      imageUrl: "",
      price: 3.49,
      unitValue: 130,
      unitType: "ml",
      description:
        "Fluoride toothpaste for daily cavity protection.",
      stock: 120,
      categorySlugs: ["household"],
    },
  ],

  coupons: [
    {
      code: "WELCOME10",
      type: "percent",
      value: 10,
      scope: "store",
      minOrderValue: 25,
      maxDiscount: 6,
      usageLimit: 500,
      perUserLimit: 1,
    },
    {
      code: "FRESH5",
      type: "percent",
      value: 5,
      scope: "category",
      targetCategorySlugs: ["produce"],
      minOrderValue: 15,
      maxDiscount: 4,
      usageLimit: 300,
      perUserLimit: 2,
    },
    {
      code: "BREW15",
      type: "percent",
      value: 15,
      scope: "category",
      targetCategorySlugs: ["coffee-tea"],
      minOrderValue: 20,
      maxDiscount: 6,
      usageLimit: 200,
      perUserLimit: 1,
    },
    {
      code: "SNACK2",
      type: "flat",
      value: 2,
      scope: "category",
      targetCategorySlugs: ["snacks-candy"],
      minOrderValue: 15,
      maxDiscount: 2,
      usageLimit: 250,
      perUserLimit: 2,
    },
    {
      code: "HOME3",
      type: "flat",
      value: 3,
      scope: "category",
      targetCategorySlugs: ["household"],
      minOrderValue: 30,
      maxDiscount: 3,
      usageLimit: 150,
      perUserLimit: 1,
    },
    {
      code: "PIZZA1",
      type: "flat",
      value: 1,
      scope: "product",
      targetProductSlugs: ["digiorno-four-cheese", "stouffers-french-bread-pizza", "tillamook-pepperoni-pizza"],
      minOrderValue: 8,
      maxDiscount: 1,
      usageLimit: 400,
      perUserLimit: 3,
    },
    {
      code: "FREESHIP",
      type: "flat",
      value: 5,
      scope: "store",
      minOrderValue: 45,
      maxDiscount: 5,
      usageLimit: 400,
      perUserLimit: 1,
    },
  ],

  banners: [
    {
      title: "Fresh every morning",
      subtitle: "Produce delivered the day it lands",
      imageUrl:
        "https://images.unsplash.com/photo-1542838132-92c53300491e?w=1200&q=80",
      targetCategorySlug: "produce",
      sortOrder: 0,
      backgroundColor: "#1F6F4A",
    },
    {
      title: "Coffee run, at home",
      subtitle: "Up to 15% off ground coffee and pods",
      imageUrl:
        "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=1200&q=80",
      targetCategorySlug: "coffee-tea",
      sortOrder: 1,
      backgroundColor: "#4A2C1A",
    },
    {
      title: "Snack aisle sale",
      subtitle: "Chips, cookies and candy on offer",
      imageUrl:
        "https://images.unsplash.com/photo-1481391319762-47dff72954d9?w=1200&q=80",
      targetCategorySlug: "snacks-candy",
      sortOrder: 2,
      backgroundColor: "#7A1F3D",
    },
    {
      title: "Stock the pantry",
      subtitle: "Pasta, sauce and canned goods in family sizes",
      imageUrl:
        "https://images.unsplash.com/photo-1556909212-d5b604d0c90d?w=1200&q=80",
      targetCategorySlug: "pantry",
      sortOrder: 3,
      backgroundColor: "#2A4C7A",
    },
  ],
};
