// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB92G8FqQJGABm4mqObeMnmHPH3lVT2iKs',
    appId: '1:905460690574:android:63dcbfb9c6037c46ef63df',
    messagingSenderId: '905460690574',
    projectId: 'corderlia-ecom',
    storageBucket: 'corderlia-ecom.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQX9aDWndJkbi-Eb95snwvaDVr4jdilwU',
    appId: '1:905460690574:ios:d9d698dc807730fcef63df',
    messagingSenderId: '905460690574',
    projectId: 'corderlia-ecom',
    storageBucket: 'corderlia-ecom.appspot.com',
    androidClientId:
        '905460690574-7onh4ef26pfvdpihj66equ9gbj2h0t2e.apps.googleusercontent.com',
    iosClientId:
        '905460690574-3269l2pvgdabd86p79jvknvjendappmg.apps.googleusercontent.com',
    iosBundleId: 'com.flutteragentic.gravia',
  );
}
