// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZAuWGgQHnn_yifP-ioT95pXk-6gyo31o',
    appId: '1:905460690574:android:df4ca23d18fbf709ef63df',
    messagingSenderId: '905460690574',
    projectId: 'corderlia-ecom',
    storageBucket: 'corderlia-ecom.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7XyEF7M_ZAJ_voJYJBQ0Ukoa83pdcLVs',
    appId: '1:905460690574:ios:70e3279ad976fd5cef63df',
    messagingSenderId: '905460690574',
    projectId: 'corderlia-ecom',
    storageBucket: 'corderlia-ecom.appspot.com',
    androidClientId: '905460690574-7onh4ef26pfvdpihj66equ9gbj2h0t2e.apps.googleusercontent.com',
    iosClientId: '905460690574-8k7usfvtd30jn9u17v2hm0p2rju4hrb3.apps.googleusercontent.com',
    iosBundleId: 'com.cordeliaapps.superapp',
  );
}
